#!/bin/bash
sha256sum ./de_GWD_amd64.zip | awk '{print$1}' | tee ./de_GWD_amd64.zip.sha256sum
sha256sum ./de_GWD_arm64.zip | awk '{print$1}' | tee ./de_GWD_arm64.zip.sha256sum
sha256sum ./resource/client/Archive.zip | awk '{print$1}' | tee ./resource/client/Archive.zip.sha256sum
sha256sum ./resource/server/sample.zip | awk '{print$1}' | tee ./resource/server/sample.zip.sha256sum
sha256sum ./resource/doh/doh_s_amd64 | awk '{print$1}' | tee ./resource/doh/doh_s_amd64.sha256sum
sha256sum ./resource/doh/doh_s_arm64 | awk '{print$1}' | tee ./resource/doh/doh_s_arm64.sha256sum
sha256sum ./resource/nginx/nginx_amd64 | awk '{print$1}' | tee ./resource/nginx/nginx_amd64.sha256sum
sha256sum ./resource/nginx/nginx_arm64 | awk '{print$1}' | tee ./resource/nginx/nginx_arm64.sha256sum
sha256sum ./resource/nginx/nginxConf.zip | awk '{print$1}' | tee ./resource/nginx/nginxConf.zip.sha256sum
