#!/bin/bash
localip="$(cat /var/www/html/doh.txt | awk 'NR==1{print}')"
upstreamip="$(cat /var/www/html/doh.txt | awk 'NR==2{print}')"


sed -i "/address/c\address $localip"  /etc/network/interfaces
sed -i "/gateway/c\gateway $upstreamip"  /etc/network/interfaces

sed -i "/IPV4_ADDRESS=/c\IPV4_ADDRESS=$localip/24"  /etc/pihole/setupVars.conf

sed -i "/static ip_address=/c\static ip_address=$localip/24" /etc/dhcpcd.conf
sed -i "/static routers=/c\static routers=$upstreamip" /etc/dhcpcd.conf
sed -i "/static domain_name_servers=/c\static domain_name_servers=127.0.0.1" /etc/dhcpcd.conf
sed -i '/nameserver/c\nameserver 127.0.0.1'  /etc/resolv.conf
rm -rf /var/www/html/staticip.txt