#!/bin/bash
doh1="$(awk 'NR==1{print}' /var/www/html/doh.txt)"
doh2="$(awk 'NR==2{print}' /var/www/html/doh.txt)"

doh_upstream1='url = "https:\/\/'$doh1'\/dq"'
doh_upstream2='url = "https:\/\/'$doh2'\/dq"'

sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==1{print}')s/.*/$doh_upstream1/" /etc/dns-over-https/doh-client.conf
sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==2{print}')s/.*/$doh_upstream2/" /etc/dns-over-https/doh-client.conf

doh1ip=$(nslookup $(echo $doh1 | cut -d : -f1) 119.29.29.29| awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2)
doh2ip=$(nslookup $(echo $doh2 | cut -d : -f1) 119.29.29.29| awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2)

sed -i '/doh/,$d' /etc/hosts
cat >> /etc/hosts << EOF
#doh static dns
$doh1ip $doh1
$doh2ip $doh2
EOF

systemctl restart doh-client
systemctl restart iptables-proxy
