#!/bin/bash
localip=$(cat /var/www/html/localip.txt)

jq 'del(.routing.rules[5].source[])' /etc/vtrui/config.json > /etc/vtrui/temp.json
for localippre in $(echo "$localip" | xargs -n1); do
jq --arg localippre $localippre '.routing.rules[5].source+=[$localippre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

systemctl restart vtrui
rm -rf /var/www/html/localip.txt