#!/bin/bash
CFdomain=$(awk 'NR==1{print}' /var/www/html/ddnscf.txt)
CFzoneid=$(awk 'NR==2{print}' /var/www/html/ddnscf.txt)
CFapikey=$(awk 'NR==3{print}' /var/www/html/ddnscf.txt)
CFemail=$(awk 'NR==4{print}' /var/www/html/ddnscf.txt)

{
curl -sX GET "https://api.cloudflare.com/client/v4/zones/$CFzoneid/dns_records" -H "X-Auth-Email: $CFemail" -H "X-Auth-Key: $CFapikey" -H "Content-Type: application/json" | jq .
} > /tmp/ddnscf

jq --arg CFdomain "$CFdomain" -r '.result[] | select(.name == $CFdomain).id' /tmp/ddnscf

