#!/bin/bash
port=$(jq '.outbounds[2].settings.vnext[0].port' /etc/vtrui/config.json)
domain=$(jq -r '.outbounds[2].settings.vnext[0].address' /etc/vtrui/config.json)

if [[ "$port" -eq "443" ]]; then
nodecheck=$domain
else
nodecheck=$domain:$port
fi

sed -n -e "/$nodecheck/=" /var/www/html/domain.txt