#!/bin/bash
nodenum=$(sed -n -e "/$(sed -n -e '/"address": "/p' /etc/v2ray/config.json | awk -F'"' '{print$4}' | awk 'NR==1{print}')/=" /var/www/html/domain.txt)

cat > /etc/v2ray/config.json << EOF
{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "error"
  },
  "inbounds": [
    {
    "port": 9897,
    "protocol": "socks",
    "settings": { "auth": "noauth", "network": "tcp,udp" },
    "sniffing": { "enabled": true, "destOverride": ["http", "tls"] }
    },
    {
    "port": 9896,
    "listen": "127.0.0.1",
    "protocol": "dokodemo-door",
    "settings": { "auth": "noauth", "network": "tcp,udp", "followRedirect": true },
    "sniffing": { "enabled": true, "destOverride": ["http", "tls"] },
    "streamSettings": { "sockopt": { "mark": 255, "tproxy": "tproxy" } }
    }
  ],
  "outbounds": [
    {
    "mux": { "enabled": true },
    "protocol": "vmess",
    "settings": { "vnext": [{
      "address": "xxxx.ooo",
      "port": 443,
      "users": [{
        "id": "00000000-0000-0000-0000-000000000000",
        "level": 1,
        "alterId": 64,
        "security": "aes-128-gcm"
        }]
      }]},
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/000000",
        "headers": {
          "Host": "xxxx.ooo"
          }
        },
      "security": "tls",
      "tlsSettings": {
        "serverName": "xxxx.ooo",
        "allowInsecure": false
        },
      "sockopt": { "mark": 255 }
      }
    },
    {
    "tag": "netflix",
    "protocol": "vmess",
    "settings": { "vnext": [{
      "address": "xxxx.ooo",
      "port": 443,
      "users": [{
        "id": "00000000-0000-0000-0000-000000000000",
        "level": 0,
        "alterId": 64,
        "security": "aes-128-gcm"
        }]
      }]},
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/000000",
        "headers": {
          "Host": "xxxx.ooo"
          }
        },
      "security": "tls",
      "tlsSettings": {
        "serverName": "xxxx.ooo",
        "allowInsecure": false
        },
      "sockopt": { "mark": 255 }
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "streamSettings": {
        "sockopt": { "mark": 255 }
      },
      "settings": {}
    }
  ],
  "routing": {
    "domainStrategy": "AsIs",
    "rules": [
      {
        "type": "field",
        "port": "5380,4711",
        "network": "tcp,udp",
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": ["geosite:cn"],
        "outboundTag": "direct"
      },
      {
        "type": "field",
        "domain": [
          "domain:netflix.com",
          "domain:nflxvideo.net",
          "domain:nflxso.net",
          "domain:nflximg.net",
          "domain:netflix.net",
          "domain:netflixdnstest0.com",
          "domain:netflixdnstest1.com",
          "domain:netflixdnstest2.com",
          "domain:netflixdnstest3.com",
          "domain:netflixdnstest4.com",
          "domain:netflixdnstest5.com",
          "domain:netflixdnstest6.com",
          "domain:netflixdnstest7.com",
          "domain:netflixdnstest8.com",
          "domain:netflixdnstest9.com"
        ],
        "outboundTag": "netflix"
      }
    ]
  }
}
EOF

domain=$(awk "NR==$nodenum{print}" /var/www/html/domain.txt | cut -d : -f1)
port=$(awk "NR==$nodenum{print}" /var/www/html/domain.txt | cut -d : -f2)

if [[ $port =~ ^[1-9]+$ ]]; then
sed -i "$(sed -n -e '/"port":/=' /etc/v2ray/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "$port",/" /etc/v2ray/config.json
sed -i "$(sed -n -e '/"port":/=' /etc/v2ray/config.json | awk 'NR==4{print}')s/.*/"'"port"'": "$port",/" /etc/v2ray/config.json
else
sed -i "$(sed -n -e '/"port":/=' /etc/v2ray/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "443",/" /etc/v2ray/config.json
sed -i "$(sed -n -e '/"port":/=' /etc/v2ray/config.json | awk 'NR==4{print}')s/.*/"'"port"'": "443",/" /etc/v2ray/config.json
fi

sed -i '/"address":/c\"address": "'$domain'",'  /etc/v2ray/config.json
sed -i '/"id":/c\"id": "'$(awk 'NR=='$nodenum'{print}' /var/www/html/uuid.txt)'",'  /etc/v2ray/config.json
sed -i '/"serverName":/c\"serverName": "'$domain'",'  /etc/v2ray/config.json
sed -i '/"path":/c\"path": "'$(awk 'NR=='$nodenum'{print}' /var/www/html/path.txt)'",'  /etc/v2ray/config.json
sed -i '/"Host":/c\"Host": "'$domain'"'  /etc/v2ray/config.json

sed -i '/div id="shnodedt" style=/c\<div id="shnodedt" style="display:none">' /var/www/html/index.php
