#!/bin/bash
port=$(awk '/port/' /etc/v2ray/config.json | awk 'NR==5{print$2}' | cut -d , -f1)

if [[ $port == "443" ]]; then
cat /var/www/html/domain.txt | cut -d : -f2 | sed -n -e "/$(sed -n -e '/"address": "/p' /etc/v2ray/config.json | awk -F'"' '{print$4}' | awk 'NR==3{print}')/="
else
sed -n -e "/$(sed -n -e '/"address": "/p' /etc/v2ray/config.json | awk -F'"' '{print$4}' | awk 'NR==3{print}'):$port/=" /var/www/html/domain.txt
fi