#!/bin/bash
port=$(awk '/port/' /etc/vtrui/config.json | awk 'NR==3{print$2}' | cut -d , -f1)

if [[ $port == 443 ]]; then
cat /var/www/html/domain.txt | cut -d : -f2 2>&1 | sed -n -e "/$(sed -n -e '/"address": "/p' /etc/vtrui/config.json | awk -F'"' '{print$4}' | awk 'NR==1{print}')/="
else
sed -n -e "/$(sed -n -e '/"address": "/p' /etc/vtrui/config.json | awk -F'"' '{print$4}' | awk 'NR==1{print}'):$port/=" /var/www/html/domain.txt
fi