#!/bin/bash

cat > /etc/wireguard/wg0.conf << EOF
[Interface]
PrivateKey = $(cat /etc/wireguard/sprivatekey)
Address = 172.16.66.1/24
ListenPort = 9895
DNS = $(ip -oneline -family inet address show |  awk '{print $4}' | awk 'END {print}' | cut -d '/' -f1)
MTU = 1420
PostUp   = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s $(ip -oneline -family inet address show |  awk '{print $4}' | awk 'END {print}' | cut -d '/' -f1),172.16.66.0/24 -o $(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1) -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s $(ip -oneline -family inet address show |  awk '{print $4}' | awk 'END {print}' | cut -d '/' -f1),172.16.66.0/24 -o $(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1) -j MASQUERADE

[Peer]
PublicKey = $(cat /etc/wireguard/cpublickey)
AllowedIPs = 172.16.66.0/24
EOF
chmod 600 /etc/wireguard/wg0.conf


cat > /etc/wireguard/client.conf << EOF
[Interface]
PrivateKey = $(cat /etc/wireguard/cprivatekey)
Address = 172.16.66.2/32
DNS = $(ip -oneline -family inet address show |  awk '{print $4}' | awk 'END {print}' | cut -d '/' -f1)
MTU = 1420

[Peer]
PublicKey = $(cat /etc/wireguard/spublickey)
Endpoint = $(awk 'NR==1{print}' /var/www/html/ddnscf.txt):9895
AllowedIPs = 0.0.0.0/0
EOF
chmod 600 /etc/wireguard/client.conf

systemctl daemon-reload
systemctl restart wg-quick@wg0
systemctl enable wg-quick@wg0