#!/bin/bash
clear
function blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
function yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
function green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
function red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }



mirrorsite="ucccmi.cf/gwd"

mirrorsiteip="172.247.76.127"



architecture=""
case $(uname -m) in
    x86_64)  architecture="amd64" ;;
    aarch64)  architecture="arm64" ;;
esac



function preinstall(){
apt install -y sudo net-tools dnsutils ipset curl rsync ca-certificates unzip git subversion jq

source /etc/profile

echo "Asia/Shanghai" > /etc/timezone
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

cat > /etc/default/locale << EOF
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
EOF
locale-gen en_US.UTF-8

cat > /etc/security/limits.conf << EOF
* soft nofile 1000000
* hard nofile 1000000
* soft nproc 1000000
* hard nproc 1000000
EOF

echo "ulimit -n 1000000" > ~/.bash_profile

sed -i '/IPv6/d'  /etc/hosts
sed -i '/ip6/d'  /etc/hosts

cat > /etc/sysctl.conf << EOF
vm.overcommit_memory = 1
fs.file-max = 1000000
net.nf_conntrack_max = 1000000
net.netfilter.nf_conntrack_max = 1000000
fs.inotify.max_user_instances = 8192
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_syn_backlog = 16384
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.tcp_max_orphans = 32768
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 87380 8388608
net.core.rmem_max = 8388608
net.core.wmem_max = 8388608
net.core.somaxconn = 32768
net.core.netdev_max_backlog = 32768
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF
sysctl -p

if [[ $architecture = "arm64" ]]; then
sed -i '/GOVERNOR=/c\GOVERNOR=performance' /etc/default/cpufrequtils
/etc/init.d/cpufrequtils restart;
fi
}



function installdoh(){
systemctl stop doh-client
rm -rf ~/dns-over-https
rm -rf /usr/local/bin/doh-client
rm -rf /usr/local/bin/doh-server
rm -rf /etc/NetworkManager/dispatcher.d
rm -rf /usr/lib/systemd/system/doh-client.service
rm -rf /usr/lib/systemd/system/doh-server.service

cd ~
if [[ $architecture = "arm64" ]]; then
  wget -N https://$mirrorsite/doharm64.zip
  unzip doharm64.zip
  mv -f ~/doharm64/doh-client /usr/local/bin/doh-client
  rm -rf ~/doharm64*
elif [[ $architecture = "amd64" ]]; then
  wget -N https://$mirrorsite/dohamd64.zip
  unzip dohamd64.zip
  mv -f ~/dohamd64/doh-client /usr/local/bin/doh-client
  rm -rf ~/dohamd64*
fi
chmod +x /usr/local/bin/doh-client

mkdir -p /etc/dns-over-https/
wget -O /etc/dns-over-https/doh-client.conf https://$mirrorsite/doh-client.conf

doh_upstream='url = "https:\/\/'$doh'\/dq"'

sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==1{print}')s/.*/$doh_upstream/" /etc/dns-over-https/doh-client.conf
sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==2{print}')s/.*/$doh_upstream/" /etc/dns-over-https/doh-client.conf

dohip=$(nslookup $(echo $doh | cut -d : -f1) | awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2)

sed -i '/doh/,$d' /etc/hosts

cat >> /etc/hosts << EOF
#doh static dns
$dohip $doh
$dohip $doh
EOF

mkdir -p /etc/NetworkManager/dispatcher.d/

cat > /etc/NetworkManager/dispatcher.d/doh-client << "EOF"
#!/bin/bash
case "$2" in
    up)
        /usr/bin/systemctl is-active doh-client.service > /dev/null && /usr/bin/systemctl restart doh-client.service
        ;;
    down)
        /usr/bin/systemctl is-active doh-client.service > /dev/null && /usr/bin/systemctl restart doh-client.service
        ;;
    *)
        exit 0
        ;;
esac
EOF
chmod +x /etc/NetworkManager/dispatcher.d/doh-client

cat > /etc/systemd/system/doh-client.service << "EOF"
[Unit]
Description=DNS-over-HTTPS Client
After=network.target
Before=nss-lookup.target
Wants=nss-lookup.target

[Service]
Type=simple
ExecStart=/usr/local/bin/doh-client -conf /etc/dns-over-https/doh-client.conf
LimitNOFILE=1000000
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl restart doh-client
systemctl enable doh-client
}



function installv2ray(){
cd ~
mkdir -p /usr/bin/vtrui
mkdir -p /etc/vtrui
if [[ $architecture = "arm64" ]]; then
    wget -N https://$mirrorsite/vtarm64.zip
    unzip vtarm64.zip
    mv -f ~/vtarm64/vtrui /usr/bin/vtrui/vtrui
    mv -f ~/vtarm64/v2ctl /usr/bin/vtrui/v2ctl
    rm -rf ~/vtarm64*
elif [[ $architecture = "amd64" ]]; then
    wget -N https://$mirrorsite/vtamd64.zip
    unzip vtamd64.zip
    mv -f ~/vtamd64/vtrui /usr/bin/vtrui/vtrui
    mv -f ~/vtamd64/v2ctl /usr/bin/vtrui/v2ctl
    rm -rf ~/vtamd64*
fi
chmod +x /usr/bin/vtrui/vtrui
chmod +x /usr/bin/vtrui/v2ctl

cat > /etc/systemd/system/vtrui.service << EOF
[Unit]
Description=vtrui Service
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/run/vtrui.pid
ExecStart=/usr/bin/vtrui/vtrui -config /etc/vtrui/config.json
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

wget -N https://$mirrorsite/vtpre.zip
unzip vtpre.zip
mv -f ~/vtpre/geoip.dat /usr/bin/vtrui/geoip.dat
mv -f ~/vtpre/v2wt-client.json /etc/vtrui/config.json
rm -rf ~/vtpre*

result=$(echo $port | grep '^[0-9]\+$')
if [[ $result = "" ]]; then
port="443"
fi

jq --arg domain "$domain" '.outbounds[0].settings.vnext[0].address=$domain' /etc/vtrui/config.json |\
jq --argjson port "$port" '.outbounds[0].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[0].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[0].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[0].streamSettings.wsSettings.headers.Host=$domain' |\
jq --arg domain "$domain" '.outbounds[0].streamSettings.tlsSettings.serverName=$domain' > /etc/vtrui/temp.json && mv -f /etc/vtrui/temp.json /etc/vtrui/config.json


systemctl daemon-reload
systemctl restart vtrui
systemctl enable vtrui
}



function installiptablesproxy(){
cat > /usr/local/bin/iptables-proxy-up << "EOF"
#!/bin/bash
ipset -X chnroute
ipset -X lanip
ipset -X listwlan
ipset -X listw

lanip="0.0.0.0/8 \
100.64.0.0/10 \
127.0.0.0/8 \
169.254.0.0/16 \
10.0.0.0/8 \
172.16.0.0/12 \
192.168.0.0/16 \
255.255.255.255/32 \
114.114.114.114/32 \
114.114.115.115/32 \
119.29.29.29/32 \
119.28.28.28/32 \
223.5.5.5/32 \
223.6.6.6/32"

ipset -R < /usr/local/bin/chnrouteset

ipset -N lanip hash:net maxelem 65535
for iplanip in $lanip; do
  ipset add lanip $iplanip
done

ipset -N listwlan hash:net maxelem 65535
for iplistwlan in $(cat /var/www/html/listwlan.txt); do
  ipset add listwlan $iplistwlan
done

ipset -N listw hash:net maxelem 65535
for iplistw in $(cat /var/www/html/listw.txt); do
  ipset add listw $iplistw
done
for vtruinodeip in $(cat /usr/local/bin/vtruinodeip.txt); do
  ipset add listw $vtruinodeip
done
ipset add listw $(awk "NR==$(echo $[$(sed -n -e '/doh/=' /etc/hosts) + 1]){print}" /etc/hosts | cut -d " " -f1)
ipset add listw $(awk "NR==$(echo $[$(sed -n -e '/doh/=' /etc/hosts) + 2]){print}" /etc/hosts | cut -d " " -f1)


ip rule add fwmark 0x9 table 100 pref 100
ip route add local default dev lo table 100

iptables -t mangle -N V2PROXY
iptables -t mangle -A V2PROXY -p tcp --dport 53 -j ACCEPT
iptables -t mangle -A V2PROXY -p udp --dport 53 -j ACCEPT
iptables -t mangle -A V2PROXY -p tcp --dport 5380 -j ACCEPT
iptables -t mangle -A V2PROXY -p udp --dport 5380 -j ACCEPT
iptables -t mangle -A V2PROXY -p tcp --dport 5390 -j ACCEPT
iptables -t mangle -A V2PROXY -p udp --dport 5390 -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set lanip dst -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set listwlan src -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set listw dst -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set chnroute dst -j ACCEPT
iptables -t mangle -A V2PROXY -m mark --mark 0xff -j ACCEPT

iptables -t mangle -A V2PROXY -p tcp -j MARK --set-mark 0x9
iptables -t mangle -A V2PROXY -p udp -j MARK --set-mark 0x9

iptables -t mangle -A OUTPUT -p tcp -j V2PROXY
iptables -t mangle -A OUTPUT -p udp -j V2PROXY

iptables -t mangle -A PREROUTING -p tcp -m mark ! --mark 0x9 -j V2PROXY
iptables -t mangle -A PREROUTING -p udp -m mark ! --mark 0x9 -j V2PROXY

iptables -t mangle -A PREROUTING -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 9896 --tproxy-mark 0x9
iptables -t mangle -A PREROUTING -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 9896 --tproxy-mark 0x9
systemctl restart vtrui

if [[ "$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1)" =~ "wg0" ]]; then
systemctl restart wg-quick@wg0
fi
EOF
chmod +x /usr/local/bin/iptables-proxy-up

cat > /usr/local/bin/iptables-proxy-down << EOF
#!/bin/bash
systemctl stop vtrui

iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -F
iptables -X

ipset -F chnroute
ipset -F lanip
ipset -F listwlan
ipset -F listw

ip route flush table 100
ip rule del fwmark 0x9
EOF
chmod +x /usr/local/bin/iptables-proxy-down

cat > /etc/systemd/system/iptables-proxy.service << EOF
[Unit]
Description=iptables-proxy
After=network.target
Wants=network.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/iptables-proxy-up
ExecStop=/usr/local/bin/iptables-proxy-down
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl restart iptables-proxy
systemctl enable iptables-proxy

systemctl mask systemd-resolved --now
}



function installpihole(){
rm -rf /var/www/html/admin

mkdir -p /etc/pihole

cat > /etc/pihole/setupVars.conf << EOF
PIHOLE_INTERFACE=$ethernetnum
IPV4_ADDRESS=$localaddr/24
IPV6_ADDRESS=
PIHOLE_DNS_1=119.29.29.29
PIHOLE_DNS_2=119.28.28.28
QUERY_LOGGING=true
INSTALL_WEB_SERVER=true
INSTALL_WEB_INTERFACE=true
LIGHTTPD_ENABLED=true
BLOCKING_ENABLED=true
WEBPASSWORD=0000000000000000000000000000000000000000000000000000000000000000
DNSMASQ_LISTENING=single
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true
DNSSEC=false
CONDITIONAL_FORWARDING=false
EOF

curl -sSL https://raw.githubusercontent.com/pi-hole/pi-hole/master/automated%20install/basic-install.sh | bash /dev/stdin --unattended

cat > /etc/pihole/dns-servers.conf << EOF
 114DNS;114.114.114.114;114.114.115.115
 DNSpod;119.29.29.29;119.28.28.28
 阿里DNS;223.5.5.5;223.6.6.6
EOF

sed -i '/PIHOLE_DNS/d'  /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_6=223.6.6.6' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_5=223.5.5.5' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_4=119.28.28.28' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_3=119.29.29.29' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_2=114.114.115.115' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_1=114.114.114.114' /etc/pihole/setupVars.conf
sed -i '/server=/d'  /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=114.114.114.114' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=114.114.115.115' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=119.29.29.29' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=119.28.28.28' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=223.5.5.5' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=223.6.6.6' /etc/dnsmasq.d/01-pihole.conf

echo "" > /etc/pihole/adlists.list
pihole -g
}


function piholesetting(){
cat > /etc/dnsmasq.conf << EOF
conf-dir=/etc/dnsmasq.d
port=5390
EOF

cat > /etc/resolv.conf << EOF
nameserver 127.0.0.1
EOF

pihole restartdns
}



function installwg(){
systemctl stop wg-quick@wg0

apt install -y wireguard qrencode

if [[ ! -d "/etc/wireguard" ]]; then
mkdir -p /etc/wireguard
cd /etc/wireguard

wg genkey | tee sprivatekey | wg pubkey > spublickey
wg genkey | tee cprivatekey | wg pubkey > cpublickey

cd ~
fi
}



function postinstall(){
cat > /usr/local/bin/updateGWD << "EOF"
#!/bin/bash
wget -O /usr/bin/vtrui/geosite.dat https://raw.githubusercontent.com/gwdburst/de_GWD/master/de_GWD_Client/dlc.dat
wget -O /usr/bin/vtrui/h2y.dat https://raw.githubusercontent.com/ToutyRater/V2Ray-SiteDAT/master/geofiles/h2y.dat                

curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /usr/local/bin/chnroute.txt

{
echo "create chnroute hash:net family inet hashsize 2048 maxelem 65535"
chnroute=`cat /usr/local/bin/chnroute.txt`
for chnroute in $chnroute ; do
 echo "add chnroute $chnroute"
done
} > /usr/local/bin/chnrouteset

ipset -F chnroute
for ipchnroute in $(cat /usr/local/bin/chnroute.txt); do
  ipset add chnroute $ipchnroute
done
EOF
chmod +x /usr/local/bin/updateGWD
/usr/local/bin/updateGWD

cat > /usr/local/bin/clearcache << "EOF"
#!/bin/bash
date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
hwclock -w

rm -rf ~/client
rm -rf /var/log/*1*
rm -rf /var/log/*2*
rm -rf /var/log/*.gz
rm -rf /var/www/html/log.log
EOF
chmod +x /usr/local/bin/clearcache
/usr/local/bin/clearcache

cat > ~/now.cron << EOF
0 4 * * * /usr/local/bin/updateGWD
0 */4 * * * /usr/local/bin/clearcache
EOF
crontab ~/now.cron
rm -rf ~/now.cron

svn export https://github.com/gwdburst/de_GWD/trunk/de_GWD_Client/ui-script
svn export https://github.com/gwdburst/de_GWD/trunk/de_GWD_Client/ui-web

rsync -r ~/ui-script/* /usr/local/bin
chmod +x /usr/local/bin/*
rsync -r ~/ui-web/* /var/www/html
rm -rf ~/ui-*

wget -O /var/www/html/version.php https://raw.githubusercontent.com/gwdburst/de_GWD/master/de_GWD_Client/version.php

/usr/local/bin/ui-nodedthide
/usr/local/bin/ui-changedoh
}



installgwd(){
    green "==============="
    green "本机地址"
    green "==============="
    read localaddr

    green "==============="
    green "上级路由地址"
    green "==============="
    read gatewayaddr

    green "==============="
    green "v2ray节点域名"
    green "==============="
    read v2servn

    green "==============="
    green "输入v2ray uuid"
    green "==============="
    read uuidnum

    green "==============="
    green "输入path"
    green "==============="
    read v2path

cd ~

cat > /etc/resolv.conf << EOF
nameserver 119.29.29.29
nameserver 119.28.28.28
EOF

if [[ $architecture = "amd64" ]] && [[ $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1) = "buster" ]]; then
cat > /etc/apt/sources.list << EOF
deb http://mirrors.aliyun.com/debian buster main contrib non-free
deb http://mirrors.aliyun.com/debian buster-proposed-updates main contrib non-free
deb http://mirrors.aliyun.com/debian buster-updates main contrib non-free
deb http://mirrors.aliyun.com/debian-security/ buster/updates main non-free contrib
EOF
elif [[ $architecture = "amd64" ]] && [[ $(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1) = "stretch" ]]; then
cat > /etc/apt/sources.list << EOF
deb http://mirrors.aliyun.com/debian stretch main contrib non-free
deb http://mirrors.aliyun.com/debian stretch-proposed-updates main contrib non-free
deb http://mirrors.aliyun.com/debian stretch-updates main contrib non-free
deb http://mirrors.aliyun.com/debian-security/ stretch/updates main non-free contrib
EOF
fi

apt update && apt upgrade -y

preinstall

domain=$(echo $v2servn | cut -d : -f1)
port=$(echo $v2servn | cut -d : -f2)
doh=$(echo $v2servn | cut -d : -f1)
ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1 | awk 'NR==1{print}')

sed -i "1i $mirrorsiteip $(echo $mirrorsite | cut -d "/" -f1)" /etc/hosts

installdoh

echo -e $(nslookup $(echo $v2servn | cut -d : -f1) -port=5380 | awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2) > /usr/local/bin/vtruinodeip.txt

wget -O /usr/local/bin/chnroute.txt https://$mirrorsite/ui-cnr.txt

{
echo "create chnroute hash:net family inet hashsize 2048 maxelem 65535"
chnroute=`cat /usr/local/bin/chnroute.txt`
for chnroute in $chnroute ; do
 echo "add chnroute $chnroute"
done
} > /usr/local/bin/chnrouteset

installv2ray

installiptablesproxy

debianx=$(cat /etc/os-release | grep VERSION= | cut -d '(' -f2 | cut -d ')' -f1)

wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $debianx main" > /etc/apt/sources.list.d/php.list

echo "deb http://deb.debian.org/debian/ unstable main" > /etc/apt/sources.list.d/unstable.list
printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable

apt update

installpihole

piholesetting

sed -i "/static ip_address=/d" /etc/dhcpcd.conf
sed -i "/static routers=/d" /etc/dhcpcd.conf
sed -i "/static domain_name_servers=/d" /etc/dhcpcd.conf

echo -e "static ip_address=$localaddr/24" >> /etc/dhcpcd.conf
echo -e "static routers=$gatewayaddr" >> /etc/dhcpcd.conf
echo -e "static domain_name_servers=127.0.0.1" >> /etc/dhcpcd.conf

cat > /etc/network/interfaces << EOF
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $ethernetnum
iface $ethernetnum inet static
  address $localaddr
  netmask 255.255.255.0
  gateway $gatewayaddr
EOF

pihole restartdns

if [[ $architecture = "amd64" ]]; then
installwg
fi

sed -i "/Allow members of group sudo to execute any command/a\www-data ALL=(root)  NOPASSWD:ALL" /etc/sudoers

sed -i "/$(echo $mirrorsite | cut -d "/" -f1)/d" /etc/hosts

echo "$v2servn" > /var/www/html/nodename.txt
echo "$v2servn" > /var/www/html/domain.txt
echo "$v2servn" > /var/www/html/doh.txt
echo "$v2servn" >> /var/www/html/doh.txt
echo "$uuidnum" > /var/www/html/uuid.txt
echo "$v2path" > /var/www/html/path.txt
chown -R www-data:www-data /var/www/html/*.txt

postinstall

blue "-----------------"
blue  "安装de_GWD [完毕]"
blue "-----------------"
}


change_piholeadmin(){
pihole -a -p
blue "----------------------"
blue  "更改Pi-hole密码 [完毕]"
blue "----------------------"
}


updatepihole(){
ethernetnum="$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1)"
localaddr="$(ip -oneline -family inet address show |  awk '{print $4}' | awk 'END {print}' | cut -d '/' -f1)"

installpihole

piholesetting

pihole restartdns

blue "-------------------"
blue  "更新Pi-hole [完毕]"
blue "-------------------"
}


updategwd(){
port=$(jq '.outbounds[0].settings.vnext[0].port' /etc/vtrui/config.json)

result=$(echo $port | grep '^[0-9]\+$')
if [[ $result = "" ]]; then
port="443"
fi

domain=$(jq -r '.outbounds[0].settings.vnext[0].address' /etc/vtrui/config.json)
uuidnum=$(jq -r '.outbounds[0].settings.vnext[0].users[0].id' /etc/vtrui/config.json)
v2path=$(jq -r '.outbounds[0].streamSettings.wsSettings.path' /etc/vtrui/config.json)
doh=$(awk '/https:/' /etc/dns-over-https/doh-client.conf | awk -F'//' 'NR==1{print $2}' | cut -d'/' -f1)

echo "$doh" > /var/www/html/doh.txt
echo "$doh" >> /var/www/html/doh.txt
chown -R www-data:www-data /var/www/html/*.txt

cd ~

preinstall

installdoh

installv2ray

installiptablesproxy

piholesetting

if [[ $architecture = "amd64" ]]; then
installwg
fi

postinstall

blue "------------------"
blue  "更新de_GWD [完毕]"
blue "------------------"
}


start_menu(){
statusgod=$(green "✔︎")
statusbad=$(red "✘")

if [[ $(systemctl is-active vtrui) = "active" ]]; then
    echo "[$statusgod] v2ray     进程正常"
elif [[ ! -f "/usr/bin/vtrui" ]]; then
    echo "[$statusbad] v2ray     进程未安装"
else
    echo "[$statusbad] v2ray     进程出错"
fi


if [[ $(systemctl is-active iptables-proxy) = "active" ]]; then
    echo "[$statusgod] 代理规则  进程正常"
elif [[ ! -f "/etc/systemd/system/iptables-proxy.service" ]]; then
    echo "[$statusbad] 代理规则  进程未安装"
else
    echo "[$statusbad] 代理规则  进程出错"
fi


if [[ $(systemctl is-active doh-client) = "active" ]]; then
    echo "[$statusgod] DoH客户端 进程正常"
elif [[ ! -f "/usr/local/bin/doh-client" ]]; then
    echo "[$statusbad] DoH客户端 进程未安装"
else
    echo "[$statusbad] DoH客户端 进程出错"
fi


if [[ $(systemctl is-active pihole-FTL) = "active" ]]; then
    echo "[$statusgod] pihole    进程正常"
elif [ ! -f "/usr/local/bin/pihole" ]; then
    echo "[$statusbad] pihole    进程未安装"
else
    echo "[$statusbad] pihole    进程出错"
fi

    green "===================================="
    green "              客户端                 "
    green "介绍：一键安装de_GWD                  "
    green "系统：仅测于Debian9+ (amd64 & arm64)  "
    green "作者：GWDburst                       "
    green "网站：GWDburst.github.io             "
    green "===================================="
    echo
    green  "1. 安装de_GWD"
    green  "2. 更改Pi-hole密码"
    yellow "9. 更新Pi-hole"
    yellow "0. 更新de_GWD"
    red    "CTRL+C退出"
    echo
    read -p "请输入数字:" num
    case "$num" in
    1)
    installgwd
    start_menu
    ;;
    2)
    change_piholeadmin
    start_menu
    ;;
    9)
    updatepihole
    start_menu
    ;;
    0)
    updategwd
    start_menu
    ;;
    *)
    clear
    red "请输入正确数字"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu
