#!/bin/bash
clear
function blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
function yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
function green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
function red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }


architecture=""
case $(uname -m) in
    x86_64)  architecture="amd64" ;;
    aarch64)  architecture="arm64" ;;
esac


function preinstall(){
echo "Asia/Shanghai" > /etc/timezone
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

cat > /etc/default/locale << EOF
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
EOF
locale-gen en_US.UTF-8

sed -i '/65535/d' /etc/security/limits.conf
sed -i '/# End of file/i\* soft nproc 65535' /etc/security/limits.conf
sed -i '/# End of file/i\* hard nproc 65535' /etc/security/limits.conf
sed -i '/# End of file/i\* soft nofile 65535' /etc/security/limits.conf
sed -i '/# End of file/i\* hard nofile 65535' /etc/security/limits.conf
echo "ulimit -n 65535" > ~/.bash_profile

cat > /etc/sysctl.conf << EOF
vm.overcommit_memory = 1
kernel.pid_max = 65535
fs.file-max = 1000000
fs.inotify.max_user_instances = 8192
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv4.conf.all.route_localnet = 1
net.ipv4.ip_forward = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 1
net.ipv4.tcp_synack_retries = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_syn_backlog = 16384
net.ipv4.tcp_max_tw_buckets = 6000
net.ipv4.tcp_max_orphans = 32768
net.ipv4.tcp_rmem = 4096 87380 8388608
net.ipv4.tcp_wmem = 4096 87380 8388608
net.core.rmem_max = 8388608
net.core.wmem_max = 8388608
net.core.somaxconn = 32768
net.core.netdev_max_backlog = 32768
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF
sysctl -p

if [[ $architecture = "arm64" ]]; then
sed -i '/GOVERNOR=/c\GOVERNOR=performance' /etc/default/cpufrequtils
/etc/init.d/cpufrequtils restart;
fi

if [[ $architecture = "amd64" ]]; then
cat > /etc/apt/sources.list << EOF
deb http://mirrors.163.com/debian/ stretch main non-free contrib
deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib
deb http://mirrors.163.com/debian/ stretch-backports main non-free contrib
deb-src http://mirrors.163.com/debian/ stretch main non-free contrib
deb-src http://mirrors.163.com/debian/ stretch-updates main non-free contrib
deb-src http://mirrors.163.com/debian/ stretch-backports main non-free contrib
deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib
deb-src http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib
EOF
fi
apt update && apt -y upgrade
apt install -y net-tools curl rsync ca-certificates unzip git build-essential ipset
}


function predownload(){
cd ~
wget -N https://gwdbase.xyz/ui-script.zip
wget -N https://gwdbase.xyz/ui-web.zip
wget -O /usr/local/bin/chnroute.txt https://gwdbase.xyz/ui-cnr.txt
}


function installv2ray(){
rm -rf /etc/v2ray
rm -rf /usr/bin/v2ray
rm -rf /etc/systemd/system/v2ray.service

mkdir -p /var/log/v2ray
mkdir -p /usr/bin/vtrui
mkdir -p /etc/vtrui
if [[ $architecture = "arm64" ]]; then
    wget -N https://gwdbase.xyz/vtarm64.zip
    unzip vtarm64.zip
    mv -f ~/vtarm64/vtrui /usr/bin/vtrui/vtrui
    mv -f ~/vtarm64/v2ctl /usr/bin/vtrui/v2ctl
    rm -rf ~/vtarm64
    rm -rf ~/vtarm64.zip
elif [[ $architecture = "amd64" ]]; then
    wget -N https://gwdbase.xyz/vtamd64.zip
    unzip vtamd64.zip
    mv -f ~/vtamd64/vtrui /usr/bin/vtrui/vtrui
    mv -f ~/vtamd64/v2ctl /usr/bin/vtrui/v2ctl
    rm -rf ~/vtamd64
    rm -rf ~/vtamd64.zip
fi
chmod +x /usr/bin/vtrui/vtrui
chmod +x /usr/bin/vtrui/v2ctl

cat > /etc/systemd/system/vtrui.service << EOF
[Unit]
Description=vtrui Service
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/run/vtrui.pid
ExecStart=/usr/bin/vtrui/vtrui -config /etc/vtrui/config.json
Restart=on-failure
RestartPreventExitStatus=23

[Install]
WantedBy=multi-user.target
EOF
wget -O /usr/bin/vtrui/geosite.dat https://gwdbase.xyz/geosite.dat
wget -O /etc/vtrui/config.json https://raw.githubusercontent.com/gwdburst/de_GWD/master/de_GWD_Client/v2wt-client.json
}


function installiptablesproxy(){
cat > /usr/local/bin/iptables-proxy-up << "EOF"
#!/bin/bash
ipset -X chnroute
ipset -X lanip
ipset -X listwlan
ipset -X listw
ipset -X listb

lanip="0.0.0.0/8 \
100.64.0.0/10 \
127.0.0.0/8 \
169.254.0.0/16 \
10.0.0.0/8 \
172.16.0.0/12 \
192.168.0.0/16 \
255.255.255.255/32 \
114.114.114.114 \
114.114.115.115 \
119.29.29.29 \
119.28.28.28 \
223.5.5.5 \
223.6.6.6 "

ipset -N chnroute hash:net maxelem 65535
for ipchnroute in $(cat /usr/local/bin/chnroute.txt); do
  ipset add chnroute $ipchnroute
done

ipset -N lanip hash:net maxelem 65535
for iplanip in $lanip; do
  ipset add lanip $iplanip
done

ipset -N listwlan hash:net maxelem 65535
for iplistwlan in $(cat /var/www/html/listwlan.txt); do
  ipset add listwlan $iplistwlan
done

ipset -N listw hash:net maxelem 65535
for iplistw in $(cat /var/www/html/listw.txt); do
  ipset add listw $iplistw
done
for ipdomain in $(cat /var/www/html/domain.txt); do
  ipset add listw $(echo -e $ipdomain | cut -d : -f1)
done

ipset -N listb hash:net maxelem 65535
for iplistb in $(cat /var/www/html/listb.txt); do
  ipset add listb $iplistb
done

ip rule add fwmark 0x9 table 100 pref 100
ip route add local default dev lo table 100

iptables -t mangle -N V2PROXY
iptables -t mangle -A V2PROXY -p tcp --dport 4711 -j ACCEPT
iptables -t mangle -A V2PROXY -p udp --dport 4711 -j ACCEPT
iptables -t mangle -A V2PROXY -p tcp --dport 5380 -j ACCEPT
iptables -t mangle -A V2PROXY -p udp --dport 5380 -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set listb dst -j MARK --set-mark 0x9
iptables -t mangle -A V2PROXY -m set --match-set lanip dst -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set listwlan src -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set listw dst -j ACCEPT
iptables -t mangle -A V2PROXY -m set --match-set chnroute dst -j ACCEPT
iptables -t mangle -A V2PROXY -m mark --mark 0xff -j ACCEPT
iptables -t mangle -A V2PROXY -p tcp -j MARK --set-mark 0x9
iptables -t mangle -A V2PROXY -p udp -j MARK --set-mark 0x9

iptables -t mangle -A OUTPUT -p tcp -j V2PROXY
iptables -t mangle -A OUTPUT -p udp -j V2PROXY

iptables -t mangle -A PREROUTING -m mark ! --mark 0x9 -j V2PROXY

iptables -t mangle -A PREROUTING -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port 9896 --tproxy-mark 0x9
iptables -t mangle -A PREROUTING -p udp -j TPROXY --on-ip 127.0.0.1 --on-port 9896 --tproxy-mark 0x9
systemctl restart vtrui
EOF
chmod +x /usr/local/bin/iptables-proxy-up

cat > /usr/local/bin/iptables-proxy-down << EOF
#!/bin/bash
systemctl stop vtrui

ip route flush table 100
ip rule delete fwmark 0x9

iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -F
iptables -X

ipset -F chnroute
ipset -F lanip
ipset -F listwlan
ipset -F listw
ipset -F listb
EOF
chmod +x /usr/local/bin/iptables-proxy-down

cat > /etc/systemd/system/iptables-proxy.service << EOF
[Unit]
Description=iptables-proxy
After=network.target
Wants=network.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/bin/iptables-proxy-up
ExecStop=/usr/local/bin/iptables-proxy-down

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl start iptables-proxy
systemctl enable iptables-proxy
}


function installdoh(){
mkdir -p ~/gopath
source ~/.profile
rm -rf ~/dns-over-https
rm -rf /usr/local/bin/doh-client
rm -rf /usr/local/bin/doh-server
rm -rf /etc/NetworkManager/dispatcher.d
rm -rf /usr/lib/systemd/system/doh-client.service
rm -rf /usr/lib/systemd/system/doh-server.service
git clone https://github.com/m13253/dns-over-https.git
cd dns-over-https
make && make install
cd ~
wget -O /etc/dns-over-https/doh-client.conf https://raw.githubusercontent.com/gwdburst/de_GWD/master/de_GWD_Client/doh-client.conf
rm -rf ~/dns-over-https
rm -rf ~/gopath
}


function installpihole(){
rm -rf /var/www/html/admin

git clone --depth 1 https://github.com/pi-hole/pi-hole.git Pi-hole
cd "Pi-hole/automated install/"
bash basic-install.sh
cd ~
rm -rf ~/Pi-hole
}


function piholesetting(){
cat > /etc/pihole/adlists.list << EOF
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
https://hosts.nfz.moe/127.0.0.1/full/hosts
EOF
pihole -g

cat > /etc/pihole/dns-servers.conf << EOF
 114DNS;114.114.114.114;114.114.115.115
 DNSpod;119.29.29.29;119.28.28.28
 阿里DNS;223.5.5.5;223.6.6.6
 DNS派;101.226.4.6;218.30.118.6
 中科大防污染DNS;202.141.162.123;202.141.176.93
 Hi!XNS;40.73.101.101
 Dns-over-https;127.0.0.1#5380
EOF

sed -i '/PIHOLE_DNS/d'  /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_6=127.0.0.1#5380' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_5=223.5.5.5' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_4=119.28.28.28' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_3=119.29.29.29' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_2=114.114.115.115' /etc/pihole/setupVars.conf
sed -i '/IPV6_ADDRESS=/a\PIHOLE_DNS_1=114.114.114.114' /etc/pihole/setupVars.conf
sed -i '/server=/d'  /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=114.114.114.114' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=114.114.115.115' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=119.29.29.29' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=119.28.28.28' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=223.5.5.5' /etc/dnsmasq.d/01-pihole.conf
sed -i '/interface=/i\server=127.0.0.1#5380' /etc/dnsmasq.d/01-pihole.conf

sed -i '/nameserver/c\nameserver 127.0.0.1'  /etc/resolv.conf
}


function postinstall(){
doh_upstream='url = "https:\/\/'$doh'\/dq"'
sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==1{print}')s/.*/$doh_upstream/" /etc/dns-over-https/doh-client.conf
sed -i "$(sed -n -e '/url =/=' /etc/dns-over-https/doh-client.conf | awk 'NR==2{print}')s/.*/$doh_upstream/" /etc/dns-over-https/doh-client.conf
dohip=$(nslookup $(echo -e $doh | cut -d : -f1) | awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2)
sed -i '/doh/,$d' /etc/hosts
cat >> /etc/hosts << EOF
#doh static dns
$dohip $doh
$dohip $doh
EOF

cat > /usr/local/bin/updateGWD << "EOF"
#!/bin/bash
curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /usr/local/bin/chnroute.txt

ipset -F chnroute
for ipchnroute in $(cat /usr/local/bin/chnroute.txt); do
  ipset add chnroute $ipchnroute
done
EOF
chmod +x /usr/local/bin/updateGWD
/usr/local/bin/updateGWD

cat > /usr/local/bin/clearcache << "EOF"
#!/bin/bash
date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
hwclock -w

rm -rf /var/log/*1
rm -rf /var/log/*2
rm -rf /var/log/*gz
rm -rf ~/client
rm -rf /var/www/html/log.log
EOF
chmod +x /usr/local/bin/clearcache

crontab -l > now.cron
if [[ "$(crontab -l | grep 'updateGWD' | awk '{print $6}')" != "/usr/local/bin/updateGWD" ]]; then
  echo '0 4 * * * /usr/local/bin/updateGWD' >> now.cron
fi
if [[ "$(crontab -l | grep 'clearcache' | awk '{print $6}')" != "/usr/local/bin/clearcache" ]]; then
  echo '0 */4 * * * /usr/local/bin/clearcache' >> now.cron
fi
crontab now.cron
rm -rf now.cron

rm -rf /usr/local/bin/ui-*
unzip ui-script.zip
unzip ui-web.zip
rsync -r ~/ui-script/* /usr/local/bin
chmod +x /usr/local/bin/*
rsync -r ~/ui-web/* /var/www/html
rm -rf ~/ui-*

wget -O /var/www/html/version.php https://raw.githubusercontent.com/gwdburst/de_GWD/master/de_GWD_Client/version.php

}



installgwd(){
    green "==============="
    green "本机地址"
    green "==============="
    read localaddr

    green "==============="
    green "上级路由地址"
    green "==============="
    read gatewayaddr

    green "==============="
    green "v2ray节点域名"
    green "==============="
    read v2servn

    green "==============="
    green "输入v2ray uuid"
    green "==============="
    read uuidnum

    green "==============="
    green "输入path"
    green "==============="
    read v2path

doh=$v2servn

cd ~

preinstall

predownload

installv2ray
domain=$(echo -e $v2servn | cut -d : -f1)
port=$(echo -e $v2servn | cut -d : -f2)

if [[ $port =~ ^[1-9]+$ ]]; then
sed -i "$(sed -n -e '/"port":/=' /etc/vtrui/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "$port",/" /etc/vtrui/config.json
else
sed -i "$(sed -n -e '/"port":/=' /etc/vtrui/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "443",/" /etc/vtrui/config.json
fi

sed -i '/"address":/c\"address": "'$domain'",'  /etc/vtrui/config.json
sed -i '/"id":/c\"id": "'$uuidnum'",'  /etc/vtrui/config.json
sed -i '/"serverName":/c\"serverName": "'$domain'",'  /etc/vtrui/config.json
sed -i '/"path":/c\"path": "'$v2path'",'  /etc/vtrui/config.json
sed -i '/"Host":/c\"Host": "'$domain'"'  /etc/vtrui/config.json
systemctl start vtrui
systemctl enable vtrui

installiptablesproxy

if [[ $architecture = "arm64" ]]; then
    wget -N https://dl.google.com/go/go1.11.9.linux-arm64.tar.gz
    tar -xvf go*linux-arm64.tar.gz
    rm -rf ~/go*linux-arm64.tar.gz
elif [[ $architecture = "amd64" ]]; then
    wget -N https://dl.google.com/go/go1.11.9.linux-amd64.tar.gz
    tar -xvf go*linux-amd64.tar.gz
    rm -rf ~/go*linux-amd64.tar.gz
fi
rsync -r ~/go /usr/local
cat > ~/.profile << "EOF"
if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true

export GOROOT=/usr/local/go
export GOPATH=~/gopath
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
EOF
rm -rf ~/go

installdoh
systemctl stop systemd-resolved
systemctl disable systemd-resolved
systemctl mask systemd-resolved
systemctl daemon-reload
systemctl start doh-client
systemctl enable doh-client

installpihole
piholesetting

sed -i "/IPV4_ADDRESS=/c\IPV4_ADDRESS=$localaddr/24"  /etc/pihole/setupVars.conf
sed -i "/static ip_address=/c\static ip_address=$localaddr/24" /etc/dhcpcd.conf
sed -i "/static routers=/c\static routers=$gatewayaddr" /etc/dhcpcd.conf
sed -i "/static domain_name_servers=/c\static domain_name_servers=127.0.0.1" /etc/dhcpcd.conf
ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1 | awk 'NR==1{print}')
route del default
route add default gw $gatewayaddr $ethernetnum
cat > /etc/network/interfaces << EOF
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $ethernetnum
iface $ethernetnum inet static
  address $localaddr
  netmask 255.255.255.0
  gateway $gatewayaddr
EOF

pihole restartdns
systemctl restart pihole-FTL

sed -i "/Allow members of group sudo to execute any command/a\www-data ALL=(root)  NOPASSWD:ALL" /etc/sudoers

echo -e "$v2servn" > /var/www/html/nodename.txt
echo -e "$v2servn" > /var/www/html/domain.txt
echo -e "$uuidnum" > /var/www/html/uuid.txt
echo -e "$v2path" > /var/www/html/path.txt
chown -R www-data:www-data /var/www/html/*.txt

postinstall

blue "-----------------"
blue  "安装de_GWD [完毕]"
blue "-----------------"
}


change_piholeadmin(){
pihole -a -p
blue "----------------------"
blue  "更改Pi-hole密码 [完毕]"
blue "----------------------"
}



updatepihole(){
installpihole
piholesetting

pihole restartdns
systemctl restart pihole-FTL

blue "-------------------"
blue  "更新Pi-hole [完毕]"
blue "-------------------"
}


updategwd(){
doh=$(awk 'NR==1{print}' /var/www/html/domain.txt)

cd ~
systemctl stop iptables-proxy

preinstall

predownload

installv2ray

domain=$(awk 'NR==1{print}' /var/www/html/domain.txt | cut -d : -f1)
port=$(awk 'NR==1{print}' /var/www/html/domain.txt | cut -d : -f2)

if [[ $port =~ ^[1-9]+$ ]]; then
sed -i "$(sed -n -e '/"port":/=' /etc/vtrui/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "$port",/" /etc/vtrui/config.json
else
sed -i "$(sed -n -e '/"port":/=' /etc/vtrui/config.json | awk 'NR==3{print}')s/.*/"'"port"'": "443",/" /etc/vtrui/config.json
fi

sed -i '/"address":/c\"address": "'$domain'",'  /etc/vtrui/config.json
sed -i '/"id":/c\"id": "'$(awk 'NR==1{print}' /var/www/html/uuid.txt)'",'  /etc/vtrui/config.json
sed -i '/"serverName":/c\"serverName": "'$domain'",'  /etc/vtrui/config.json
sed -i '/"path":/c\"path": "'$(awk 'NR==1{print}' /var/www/html/path.txt)'",'  /etc/vtrui/config.json
sed -i '/"Host":/c\"Host": "'$domain'"'  /etc/vtrui/config.json
systemctl daemon-reload
systemctl restart vtrui
systemctl enable vtrui

installiptablesproxy

installdoh
systemctl daemon-reload
systemctl restart doh-client
systemctl enable doh-client

piholesetting
pihole restartdns
systemctl restart pihole-FTL

postinstall

blue "------------------"
blue  "更新de_GWD [完毕]"
blue "------------------"
}


start_menu(){
statusgod=$(green "✔︎")
statusbad=$(red "✘")

if [[ $(systemctl is-active vtrui) = "active" ]]; then
    echo "[$statusgod] v2ray     进程正常"
elif [[ ! -d "/usr/bin/vtrui" ]]; then
    echo "[$statusbad] v2ray     进程未安装"
else
    echo "[$statusbad] v2ray     进程出错"
fi


if [[ $(systemctl is-active iptables-proxy) = "active" ]]; then
    echo "[$statusgod] 代理规则  进程正常"
elif [[ ! -f "/etc/systemd/system/iptables-proxy.service" ]]; then
    echo "[$statusbad] 代理规则  进程未安装"
else
    echo "[$statusbad] 代理规则  进程出错"
fi


if [[ $(systemctl is-active doh-client) = "active" ]]; then
    echo "[$statusgod] DoH客户端 进程正常"
elif [[ ! -d "/usr/local/bin/doh-client" ]]; then
    echo "[$statusbad] DoH客户端 进程未安装"
else
    echo "[$statusbad] DoH客户端 进程出错"
fi


if [[ $(systemctl is-active pihole-FTL) = "active" ]]; then
    echo "[$statusgod] pihole    进程正常"
elif [ ! -d "/usr/local/bin/pihole" ]; then
    echo "[$statusbad] pihole    进程未安装"
else
    echo "[$statusbad] pihole    进程出错"
fi

    green "===================================="
    green "              客户端                 "
    green "介绍：一键安装de_GWD                  "
    green "系统：仅测于Debian9 (amd64 & arm64)   "
    green "作者：GWDburst                       "
    green "网站：GWDburst.github.io             "
    green "===================================="
    echo
    green  "1. 安装de_GWD"
    green  "2. 更改Pi-hole密码"
    yellow "9. 更新Pi-hole"
    yellow "0. 更新de_GWD"
    red    "CTRL+C退出"
    echo
    read -p "请输入数字:" num
    case "$num" in
    1)
    installgwd
    start_menu
    ;;
    2)
    change_piholeadmin
    start_menu
    ;;
    9)
    updatepihole
    start_menu
    ;;
    0)
    updategwd
    start_menu
    ;;
    *)
    clear
    red "请输入正确数字"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu
