#!/bin/bash

mkdir -p ~/de_GWD_backup

cp -f /var/www/html/*.txt ~/de_GWD_backup
cp -f /etc/wireguard/*key* ~/de_GWD_backup

cd ~
zip -r de_GWD_backup.zip de_GWD_backup
mv -f ~/de_GWD_backup.zip /var/www/html

rm -rf ~/de_GWD_backup*
