#!/bin/bash
localip=$(jq -r '.divertLan | to_entries[] | .value' /usr/local/bin/0conf)

jq 'del(.routing.rules[4].source[])' /etc/vtrui/config.json > /etc/vtrui/temp.json

for localippre in $localip; do
jq --arg localippre $localippre '.routing.rules[4].source+=[$localippre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

systemctl restart vtrui
