#!/bin/bash
localaddr=$(jq -r '.address.localIP' /usr/local/bin/0conf | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
upstreamip=$(jq -r '.address.upstreamIP' /usr/local/bin/0conf | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

if [[ -n $localaddr ]] && [[ -n $upstreamip ]]; then
	sed -i "/address/c\address $localaddr" /etc/network/interfaces
	sed -i "/gateway/c\gateway $upstreamip" /etc/network/interfaces

	reboot
fi