#!/bin/bash
nodenum=$(cat /var/www/html/nodepre.txt)

v2servn=$(jq --argjson nodenum $nodenum -r '.v2node[$nodenum-1].domain' /usr/local/bin/0conf)
uuidnum=$(jq --argjson nodenum $nodenum -r '.v2node[$nodenum-1].uuid' /usr/local/bin/0conf)
v2path=$(jq --argjson nodenum $nodenum -r '.v2node[$nodenum-1].path' /usr/local/bin/0conf)

domain=$(echo -e $v2servn | cut -d: -f1)
port=$(echo -e $v2servn | cut -d: -f2)

portCheck=$(echo $port | grep '^[0-9]\+$')
if [[ $portCheck = "" ]]; then
port="443"
fi

jq --arg domain "$domain" '.outbounds[0].settings.vnext[0].address=$domain' /etc/vtrui/config.json |\
jq --argjson port "$port" '.outbounds[0].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[0].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[0].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[0].streamSettings.wsSettings.headers.Host=$domain' |\
jq --arg domain "$domain" '.outbounds[0].streamSettings.tlsSettings.serverName=$domain' >/tmp/vtrui_temp && mv -f /tmp/vtrui_temp /etc/vtrui/config.json

jq --arg domain "$domain" '.v2nodeForUpdate.address=$domain' /usr/local/bin/0conf |\
jq --arg port "$port" '.v2nodeForUpdate.port=$port' |\
jq --arg uuidnum "$uuidnum" '.v2nodeForUpdate.uuid=$uuidnum' |\
jq --arg v2path "$v2path" '.v2nodeForUpdate.path=$v2path' >/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

chmod 666 /etc/vtrui/config.json
chmod 666 /usr/local/bin/0conf

rm -rf /var/www/html/nodepre.txt
