#!/bin/bash
port=$(jq '.outbounds[2].settings.vnext[0].port' /etc/vtrui/config.json)
domain=$(jq -r '.outbounds[2].settings.vnext[0].address' /etc/vtrui/config.json)

if [[ "$port" -eq "443" ]]; then
nodecheck=$domain
else
nodecheck=$domain:$port
fi

nodecheck2=$(echo $nodecheck | cut -d . -f1)

jq -r '.v2node | keys[] as $k | "\($k+1) \(.[$k] | .domain)"' /usr/local/bin/0conf | awk '/'$nodecheck'/ {print$1}' > /tmp/nodecheckdt
jq -r '.v2node | keys[] as $k | "\($k+1) \(.[$k] | .domain)"' /usr/local/bin/0conf | cut -d . -f1 | awk '/'$nodecheck2'/ {print$1}' >> /tmp/nodecheckdt

sort /tmp/nodecheckdt | uniq -d
