#!/bin/bash
if [[ -f "/lib/modules/$(uname -r | awk NR==1)/extra/wireguard.ko" ]] || [[ $(uname -r) > "5.6" ]]; then
	echo "installed"
elif [[ $(uname -m) = "aarch64" ]] && [[ -f "/lib/modules/$(uname -r | awk NR==1)/kernel/net/wireguard/wireguard.ko" ]]; then
	echo "installed"
elif [[ $(uname -m) = "aarch64" ]] && [[ -d "/var/lib/dkms/wireguard" ]]; then
	echo "installed"
fi
