#!/bin/bash
v2servn=$(awk 'NR==1{print}' /var/www/html/nodedtpre.txt)
uuidnum=$(awk 'NR==2{print}' /var/www/html/nodedtpre.txt)
v2path=$(awk 'NR==3{print}' /var/www/html/nodedtpre.txt)

domain=$(echo -e $v2servn | cut -d : -f1)
port=$(echo -e $v2servn | cut -d : -f2)

result=$(echo $port | grep '^[0-9]\+$')
if [[ $result = "" ]]; then
port="443"
fi

jq --arg domain "$domain" '.outbounds[2].settings.vnext[0].address=$domain' /etc/vtrui/config.json |\
jq --argjson port "$port" '.outbounds[2].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[2].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[2].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[2].streamSettings.wsSettings.headers.Host=$domain' |\
jq --arg domain "$domain" '.outbounds[2].streamSettings.tlsSettings.serverName=$domain' > /etc/vtrui/temp.json && mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

systemctl restart vtrui
rm -rf /var/www/html/nodedtpre.txt
