#!/bin/bash
port=$(jq '.outbounds[1].settings.vnext[0].port' /usr/local/bin/vtrui/config.json)
domain=$(jq -r '.outbounds[1].settings.vnext[0].address' /usr/local/bin/vtrui/config.json)

if [[ "$port" -eq "443" ]]; then
nodecheck=$domain
else
nodecheck=$domain:$port
fi

nodecheck2=$(echo $nodecheck | cut -d. -f1)

jq -r '.v2node | keys[] as $k | "\($k) \(.[$k] | .domain)"' /usr/local/bin/0conf | awk '/'$nodecheck'/ {print$1}' >/tmp/nodechecknf
jq -r '.v2node | keys[] as $k | "\($k) \(.[$k] | .domain)"' /usr/local/bin/0conf | cut -d. -f1 | awk '/'$nodecheck2'/ {print$1}' >>/tmp/nodechecknf

sort /tmp/nodechecknf | uniq -d
