#!/bin/bash
nodenfnum=$(cat /var/www/html/nodenfpre.txt)

v2servn=$(jq --argjson nodenfnum $nodenfnum -r '.v2node[$nodenfnum-1].domain' /usr/local/bin/0conf)
uuidnum=$(jq --argjson nodenfnum $nodenfnum -r '.v2node[$nodenfnum-1].uuid' /usr/local/bin/0conf)
v2path=$(jq --argjson nodenfnum $nodenfnum -r '.v2node[$nodenfnum-1].path' /usr/local/bin/0conf)

domain=$(echo -e $v2servn | cut -d : -f1)
port=$(echo -e $v2servn | cut -d : -f2)

result=$(echo $port | grep '^[0-9]\+$')
if [[ $result = "" ]]; then
port="443"
fi

jq --arg domain "$domain" '.outbounds[1].settings.vnext[0].address=$domain' /etc/vtrui/config.json |\
jq --argjson port "$port" '.outbounds[1].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[1].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[1].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[1].streamSettings.wsSettings.headers.Host=$domain' |\
jq --arg domain "$domain" '.outbounds[1].streamSettings.tlsSettings.serverName=$domain' > /tmp/vtrui_temp && mv -f /tmp/vtrui_temp /etc/vtrui/config.json

chmod 666 /etc/vtrui/config.json

rm -rf /var/www/html/nodenfpre.txt
