#!/bin/bash
address=$(jq -r --argjson domainNUM $1 '.v2node | to_entries[] | select(.key == $domainNUM) | .value.domain' /opt/de_GWD/0conf)
path=$(jq -r --argjson domainNUM $1 '.v2node | to_entries[] | select(.key == $domainNUM) | .value.path' /opt/de_GWD/0conf)
uuid=$(jq -r --argjson domainNUM $1 '.v2node | to_entries[] | select(.key == $domainNUM) | .value.uuid' /opt/de_GWD/0conf)

domain=$(echo -e $address | cut -d: -f1)
port=$(echo -e $address | cut -d: -f2 | grep '^[[:digit:]]*$')
[ -z $port ] && port="443"

jq --arg domain $domain '.update.v2node.domain=$domain' /opt/de_GWD/0conf |\
jq --arg port $port '.update.v2node.port=$port' |\
jq --arg path $path '.update.v2node.path=$path' |\
jq --arg uuid $uuid '.update.v2node.uuid=$uuid' | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

cat << EOF >/tmp/OBdefault
{
      "tag": "default",
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "$domain",
            "port": $port,
            "users": [
              {
                "id": "$uuid",
                "encryption": "none",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "$path"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "$domain",
          "allowInsecure": false
        },
        "sockopt": {
          "mark": 255,
          "domainStrategy": "UseIPv4"
        }
      }
}
EOF

jq '.outbounds[0]=input' /opt/de_GWD/vtrui/config.json /tmp/OBdefault | sponge /opt/de_GWD/vtrui/config.json
chmod 666 /opt/de_GWD/vtrui/config.json

systemctl restart vtrui

rm -rf /tmp/OBdefault
