#!/bin/bash
nodedtnum=$(cat /var/www/html/act/nodedtpre.txt)

v2servn=$(jq --argjson nodedtnum "$nodedtnum" -r '.v2node[$nodedtnum].domain' /usr/local/bin/0conf)
uuidnum=$(jq --argjson nodedtnum "$nodedtnum" -r '.v2node[$nodedtnum].uuid' /usr/local/bin/0conf)
v2path=$(jq --argjson nodedtnum "$nodedtnum" -r '.v2node[$nodedtnum].path' /usr/local/bin/0conf)

domain=$(echo -e $v2servn | cut -d: -f1)
port=$(echo -e $v2servn | cut -d: -f2)

portCheck=$(echo $port | grep '^[0-9]\+$')
if [[ $portCheck = "" ]]; then
port="443"
fi

jq --arg domain "$domain" '.outbounds[2].settings.vnext[0].address=$domain' /usr/local/bin/vtrui/config.json |\
jq --argjson port "$port" '.outbounds[2].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[2].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[2].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[2].streamSettings.tlsSettings.serverName=$domain' | sponge /usr/local/bin/vtrui/config.json

jq --arg domain "$domain" '.v2nodeForUpdate[2].address=$domain' /usr/local/bin/0conf |\
jq --arg port "$port" '.v2nodeForUpdate[2].port=$port' |\
jq --arg uuidnum "$uuidnum" '.v2nodeForUpdate[2].uuid=$uuidnum' |\
jq --arg v2path "$v2path" '.v2nodeForUpdate[2].path=$v2path' | sponge /usr/local/bin/0conf

chmod 666 /usr/local/bin/vtrui/config.json

rm -rf /var/www/html/act/nodedtpre.txt
