#!/bin/bash
read -d '' gfwl << EOF
[
{"address":"127.0.0.1","port":5370},
{"address":"127.0.0.1","port":5390,"domains":["ext:h2y.dat:gfw"]},
{"address":"127.0.0.1","port":5370,"domains":["domain:baidu.com"]},
{"address":"127.0.0.1","port":5390,"domains":["domain:google.com"]}
]
EOF

jq --argjson gfwl "$gfwl" '.dns.servers = $gfwl'  /etc/vtrui/config.json > /etc/vtrui/temp.json && mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
