#!/bin/bash
port=$(jq '.outbounds[0].settings.vnext[0].port' /opt/de_GWD/vtrui/config.json)
domain=$(jq -r '.outbounds[0].settings.vnext[0].address' /opt/de_GWD/vtrui/config.json)

if [[ "$port" -eq "443" ]]; then
nodecheck=$domain
else
nodecheck=$domain:$port
fi

nodecheck2=$(echo $nodecheck | cut -d. -f1)

jq -r '.v2node | keys[] as $k | "\($k) \(.[$k] | .domain)"' /opt/de_GWD/0conf | awk '/'$nodecheck'/ {print$1}' >/tmp/nodecheck
jq -r '.v2node | keys[] as $k | "\($k) \(.[$k] | .domain)"' /opt/de_GWD/0conf | cut -d. -f1 | awk '/'$nodecheck2'/ {print$1}' >>/tmp/nodecheck

sort /tmp/nodecheck | uniq -d
