#!/bin/bash
port=$(jq '.outbounds[1].settings.vnext[0].port' /etc/vtrui/config.json)
domain=$(jq -r '.outbounds[1].settings.vnext[0].address' /etc/vtrui/config.json)

if [[ "$port" -eq "443" ]]; then
nodecheck=$domain
else
nodecheck=$domain:$port
fi

nodecheck2=$(echo $nodecheck | cut -d . -f1)

sed -n -e "/$nodecheck/=" /var/www/html/domain.txt > /tmp/nodechecknf
awk -F. '{print$1}' /var/www/html/domain.txt | sed -n -e "/$nodecheck2/=" >> /tmp/nodechecknf

sort /tmp/nodechecknf | uniq -d
