#!/bin/bash
read -d '' chnwl << EOF
[
{"address":"127.0.0.1","port":5390},
{"address":"127.0.0.1","port":5390,"domains":["domain:google.com"]},
{"address":"127.0.0.1","port":5310,"domains":["domain:baidu.com"]},
{"address":"127.0.0.1","port":5310,"domains":["geosite:cn"]}
]
EOF

jq --argjson chnwl "$chnwl" '.dns.servers = $chnwl' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp && mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json
jq --arg splitDNS "chnw" '.splitDNS=$splitDNS' /usr/local/bin/0conf >/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /etc/vtrui/config.json
chmod 666 /usr/local/bin/0conf
