#!/bin/bash
read -d '' gfwl << EOF
[
{"address":"127.0.0.1","port":5310},
{"address":"127.0.0.1","port":5390,"domains":["ext:h2y.dat:gfw"]},
{"address":"127.0.0.1","port":5310,"domains":["domain:baidu.com"]},
{"address":"127.0.0.1","port":5390,"domains":["domain:google.com"]}
]
EOF

jq --argjson gfwl "$gfwl" '.dns.servers = $gfwl'  /etc/vtrui/config.json > /etc/vtrui/temp.json && mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
jq --arg splitDNS "gfw" '.splitDNS=$splitDNS' /usr/local/bin/0conf > /tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf
chmod -R 666 /usr/local/bin/0conf
