#!/bin/bash
doh1=$(jq -r '.dns.doh1' /opt/de_GWD/0conf)
doh2=$(jq -r '.dns.doh2' /opt/de_GWD/0conf)

doh1Domain=$(echo $doh1 | cut -d/ -f1 | cut -d: -f1)
doh2Domain=$(echo $doh2 | cut -d/ -f1 | cut -d: -f1)

doh1IP=$(dig @127.0.0.1 $doh1Domain -p 5310 +short | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
doh2IP=$(dig @127.0.0.1 $doh2Domain -p 5310 +short | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

doh1Port=$(echo $doh1 | cut -d/ -f1 | cut -d: -f2 | grep -Po '\d+')
doh2Port=$(echo $doh2 | cut -d/ -f1 | cut -d: -f2 | grep -Po '\d+')

doh1PortStr=$([ -n "$doh1Port" ] && echo $doh1Port | sed 's/^/:/')
doh2PortStr=$([ -n "$doh2Port" ] && echo $doh2Port | sed 's/^/:/')

echo $doh1IP $doh2IP | sort | uniq | sed '/^\s*$/d' >/opt/de_GWD/IPdoh

if [[ -z $(jq -r '.dns.china' /opt/de_GWD/0conf) ]] || [[ $(jq -r '.dns.china' /opt/de_GWD/0conf) = "null" ]]; then
  jq --arg dnsChina "114.114.114.114 114.114.115.115 119.29.29.29 119.28.28.28 223.5.5.5 223.6.6.6" '.dns.china=$dnsChina' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
fi

sed -i '/server /d' /etc/smartdns/smartdns.conf
sed -i '/server-https /d' /etc/smartdns/smartdns.conf
for dnsChina in $(jq -r '.dns.china' /opt/de_GWD/0conf); do
  if [[ -n $dnsChina ]]; then
    echo "server $dnsChina" >>/etc/smartdns/smartdns.conf
  fi
done
echo "server-https https://$doh1IP$doh1PortStr/dq -host-name $doh1Domain -group doh -exclude-default-group" >>/etc/smartdns/smartdns.conf
echo "server-https https://$doh2IP$doh2PortStr/dq -host-name $doh2Domain -group doh -exclude-default-group" >>/etc/smartdns/smartdns.conf

cat << EOF >/tmp/v2dns_config
{
"dns":{
  "hosts":{"localhost":"127.0.0.1"},
  "servers":[
  {"address":"127.0.0.1","port":5310},
  {"address":"127.0.0.1","port":5310,"domains":["domain:baidu.com"]},
  {"address":"127.0.0.1","port":5320,"domains":["domain:google.com"]},
  {"address":"127.0.0.1","port":5320,"domains":["geosite:geolocation-!cn","geosite:tld-!cn","geosite:gfw","geosite:greatfire"]}
  ],
  "tag":"dnsflow"
},
"inbounds":[
  {
    "port":5350,
    "listen":"127.0.0.1",
    "protocol":"dokodemo-door",
    "settings":{"network":"tcp,udp","address":"0.0.0.0","port":53},
    "tag":"dnsin"
  }
],
"outbounds":[
  {
    "protocol":"dns",
    "streamSettings":{"sockopt":{"mark":255}},
    "tag":"dnsout"
  },
  {
    "protocol":"freedom",
    "settings":{"domainStrategy":"UseIPv4"},
    "streamSettings":{"sockopt":{"mark":255}},
    "tag":"direct"
  }
],
"routing":{
  "domainStrategy":"AsIs",
  "rules":[
    {"type":"field","inboundTag":["dnsflow"],"outboundTag":"direct"},
    {"type":"field","inboundTag":["dnsin"],"outboundTag":"dnsout"},
    {"type":"field","port":"53","network":"tcp,udp","outboundTag":"dnsout"}
  ]
}
}
EOF



jq --arg key1 "$doh1Domain" --arg value1 "$doh1IP" '.dns.hosts += {($key1): ($value1)}' /tmp/v2dns_config |\
jq --arg key2 "$doh2Domain" --arg value2 "$doh2IP" '.dns.hosts += {($key2): ($value2)}' | sponge /tmp/v2dns_config

>/opt/de_GWD/IPv2node
jq -r '.v2node[].domain' /opt/de_GWD/0conf | cut -d: -f1 | sort | uniq | sed '/^\s*$/d' | xargs -n 8 | while read line
do
  for domainV2node in $line
  do
  key=$domainV2node
  value=$(dig @127.0.0.1 $domainV2node -p 5310 +short | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
  echo $value >>/opt/de_GWD/IPv2node
  jq --arg key "$key" --arg value "$value" '.dns.hosts += {($key): ($value)}' /tmp/v2dns_config | sponge /tmp/v2dns_config &
  done
  wait
done

if [[ -n $(jq -r '.dns.hosts' /opt/de_GWD/0conf) ]] && [[ $(jq -r '.dns.hosts' /opt/de_GWD/0conf) != "null" ]]; then
jq -r '.dns.hosts | to_entries[] | [.key, .value] | @tsv' /opt/de_GWD/0conf | while read line
do
  key=$(echo $line | awk '{print$1}')
  value=$(echo $line | awk '{print$2}')
  jq --arg key "$key" --arg value "$value" '.dns.hosts += {($key): ($value)}' /tmp/v2dns_config | sponge /tmp/v2dns_config
done
fi

jq 'del(.dns.hosts[] | select(. == ""))' /tmp/v2dns_config | sponge /tmp/v2dns_config
jq '.dns.DNSsplit="gfw"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

/opt/de_GWD/ui-saveListBW
