#!/bin/bash
dhcpStart=$(jq -r '.address.dhcpStart' /usr/local/bin/0conf)
dhcpEnd=$(jq -r '.address.dhcpEnd' /usr/local/bin/0conf)
localIP=$(jq -r '.address.localIP' /usr/local/bin/0conf)

sudo pihole -a enabledhcp "$dhcpStart" "$dhcpEnd" "$localIP" "24" "lan"
/usr/local/bin/pihole_hotfix
