#!/bin/bash
dhcpStart=$(jq -r '.address.dhcpStart' /usr/local/bin/0conf)
dhcpEnd=$(jq -r '.address.dhcpEnd' /usr/local/bin/0conf)
localIP=$(jq -r '.address.localIP' /usr/local/bin/0conf)

sudo pihole -a enabledhcp "$dhcpStart" "$dhcpEnd" "$localIP" "24" "lan"
/usr/local/bin/pihole_hotfix

jq '.address.dhcp="on"' /usr/local/bin/0conf>/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

chmod 666 /usr/local/bin/0conf
