#!/bin/bash
wanIP=$(curl http://members.3322.org/dyndns/getip)

CFdomain=$(awk 'NR==1{print}' /var/www/html/ddnsCF.txt)
CFzoneid=$(awk 'NR==2{print}' /var/www/html/ddnsCF.txt)
CFapikey=$(awk 'NR==3{print}' /var/www/html/ddnsCF.txt)
CFemail=$(awk 'NR==4{print}' /var/www/html/ddnsCF.txt)
CFdomainid=$(awk 'NR==5{print}' /var/www/html/ddnsCF.txt)

CFdomainip=$(dig $CFdomain -p 5380 | sed -n '/ANSWER SECTION:/{N;p}' | sed -n '2p' | awk '{print$5}')

if [[ "$wanIP" != "$CFdomainip" ]]; then
curl -X PUT "https://api.cloudflare.com/client/v4/zones/$CFzoneid/dns_records/$CFdomainid" \
     -H "X-Auth-Email: $CFemail" \
     -H "X-Auth-Key: $CFapikey" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'$CFdomain'","content":"'$wanIP'","ttl":1,"proxied":false}'
fi
