#!/bin/bash
CFdomain=$(jq -r '.ddns.ddnsCF.cfDomain' /opt/de_GWD/0conf)
CFzoneid=$(jq -r '.ddns.ddnsCF.cfZoneID' /opt/de_GWD/0conf)
CFapikey=$(jq -r '.ddns.ddnsCF.cfAPIkey' /opt/de_GWD/0conf)
CFemail=$(jq -r '.ddns.ddnsCF.cfEmail' /opt/de_GWD/0conf)

CFdomainid=$(curl -sX GET "https://api.cloudflare.com/client/v4/zones/$CFzoneid/dns_records" -H "X-Auth-Email: $CFemail" -H "X-Auth-Key: $CFapikey" -H "Content-Type: application/json" | jq --arg CFdomain "$CFdomain" -r '.result[] | select(.name == $CFdomain).id')

jq --arg cfDomainID "$CFdomainid" '.ddns.ddnsCF.cfDomainID=$cfDomainID' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

chmod 666 /opt/de_GWD/0conf
