#!/bin/bash
cat << EOF >/tmp/v2dns_config
{
"dns":{
  "hosts":{"localhost":"127.0.0.1"},
  "servers":[
  {"address":"127.0.0.1","port":5310},
  {"address":"127.0.0.1","port":5310,"domains":["domain:baidu.com"]},
  {"address":"127.0.0.1","port":5320,"domains":["domain:google.com"]},
  {"address":"127.0.0.1","port":5320,"domains":["geosite:geolocation-!cn","geosite:tld-!cn","geosite:gfw","geosite:greatfire"]}
  ],
  "tag":"dnsflow"
},
"inbounds":[
  {
    "port":5350,
    "listen":"127.0.0.1",
    "protocol":"dokodemo-door",
    "settings":{"network":"tcp,udp","address":"0.0.0.0","port":53},
    "tag":"dnsin"
  }
],
"outbounds":[
  {
    "protocol":"dns",
    "streamSettings":{"sockopt":{"mark":255}},
    "tag":"dnsout"
  },
  {
    "protocol":"freedom",
    "settings":{"domainStrategy":"UseIPv4"},
    "streamSettings":{"sockopt":{"mark":255}},
    "tag":"direct"
  }
],
"routing":{
  "domainStrategy":"AsIs",
  "rules":[
    {"type":"field","inboundTag":["dnsflow"],"outboundTag":"direct"},
    {"type":"field","inboundTag":["dnsin"],"outboundTag":"dnsout"},
    {"type":"field","port":"53","network":"tcp,udp","outboundTag":"dnsout"}
  ]
}
}
EOF

>/opt/de_GWD/IPv2node
jq -r '.v2node[].domain' /opt/de_GWD/0conf | cut -d: -f1 | sort | uniq | sed '/^\s*$/d' | xargs -n 8 | while read line
do
  for domainV2node in $line
  do
  echo $(dig @127.0.0.1 $domainV2node -p 5310 +short +tcp | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}') >>/opt/de_GWD/IPv2node &
  done
  wait
done

if [[ -n $(jq -r '.dns.hosts' /opt/de_GWD/0conf) ]] && [[ $(jq -r '.dns.hosts' /opt/de_GWD/0conf) != "null" ]]; then
jq -r '.dns.hosts | to_entries[] | [.key, .value] | @tsv' /opt/de_GWD/0conf | while read line
do
  key=$(echo $line | awk '{print$1}')
  value=$(echo $line | awk '{print$2}')
  jq --arg key "$key" --arg value "$value" '.dns.hosts += {($key): ($value)}' /tmp/v2dns_config | sponge /tmp/v2dns_config
done
fi

jq 'del(.dns.hosts[] | select(. == ""))' /tmp/v2dns_config | sponge /tmp/v2dns_config
jq '.dns.DNSsplit="gfw"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

/opt/de_GWD/ui-saveListBW
