#!/bin/bash
wanIP=$(curl http://members.3322.org/dyndns/getip)

domain=$(jq -r '.ddns.ddns3322.domain' /usr/local/bin/0conf)
user=$(jq -r '.ddns.ddns3322.user' /usr/local/bin/0conf)
pwd=$(jq -r '.ddns.ddns3322.pwd' /usr/local/bin/0conf)

domainip=$(dig @127.0.0.1 $domain -p 5380 +short | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

if [[ $wanIP != $domainip ]]; then
curl -u $user:$pwd "http://www.3322.org/dyndns/update?hostname=$domain&myip=$domainip"
fi
