#!/bin/bash
CFdomain=$(jq -r '.ddns.ddnsCF.cfDomain' /usr/local/bin/0conf)
CFzoneid=$(jq -r '.ddns.ddnsCF.cfZoneID' /usr/local/bin/0conf)
CFapikey=$(jq -r '.ddns.ddnsCF.cfAPIkey' /usr/local/bin/0conf)
CFemail=$(jq -r '.ddns.ddnsCF.cfEmail' /usr/local/bin/0conf)

CFdomainid=$(curl -sX GET "https://api.cloudflare.com/client/v4/zones/$CFzoneid/dns_records" -H "X-Auth-Email: $CFemail" -H "X-Auth-Key: $CFapikey" -H "Content-Type: application/json" | jq --arg CFdomain "$CFdomain" -r '.result[] | select(.name == $CFdomain).id')

jq --arg cfDomainID "$CFdomainid" '.ddns.ddnsCF.cfDomainID=$cfDomainID' /usr/local/bin/0conf > /tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

chmod 666 /usr/local/bin/0conf
