#!/bin/bash
ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)

if [[ $(jq -r '.FORWARD.PortCheck1' /opt/de_GWD/0conf) == "checked" ]];then

sed -i '/--dport 53 -i/d' /opt/de_GWD/iptables-proxy-up
sed -i '/--dport 53 -i/d' /opt/de_GWD/ui-onUDP
sed -i '/--dport 53 -i/d' /opt/de_GWD/ui-offUDP

addRule1="iptables -A INPUT -p udp --dport 53 -i $ethernetnum -j DROP"
addRule2="iptables -A INPUT -p tcp --dport 53 -i $ethernetnum -j DROP"

sed -i "/iptables -t mangle -N V2PROXY/i$addRule1" /opt/de_GWD/iptables-proxy-up
sed -i "/iptables -t mangle -N V2PROXY/i$addRule2" /opt/de_GWD/iptables-proxy-up

sed -i "/iptables -t mangle -N V2PROXY/i$addRule1" /opt/de_GWD/ui-onUDP
sed -i "/iptables -t mangle -N V2PROXY/i$addRule2" /opt/de_GWD/ui-onUDP
sed -i "/iptables -t mangle -N V2PROXY/i$addRule1" /opt/de_GWD/ui-offUDP
sed -i "/iptables -t mangle -N V2PROXY/i$addRule2" /opt/de_GWD/ui-offUDP

systemctl restart iptables-proxy

sed -i "/net.ipv4.ip_forward/c\net.ipv4.ip_forward = 0" /etc/sysctl.conf
sysctl -p >/dev/null
fi
