#!/bin/bash
rm -rf /usr/local/bin/vtrui1
mkdir -p /usr/local/bin/vtrui1
cp -f /usr/local/bin/vtrui/vtrui /usr/local/bin/vtrui1/vtrui1
cp -f /usr/local/bin/vtrui/v2ctl /usr/local/bin/vtrui1/v2ctl
chmod -R +x /usr/local/bin/vtrui1

cat << "EOF" > /lib/systemd/system/vtrui1.service
[Unit]
Description=vtrui1 Service
After=network.target nss-lookup.target
Wants=network-online.target

[Service]
User=root
Type=simple
LimitNPROC=64000
LimitNOFILE=1000000
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN CAP_NET_BIND_SERVICE
NoNewPrivileges=yes
ExecStart=/usr/local/bin/vtrui1/vtrui1 -config /usr/local/bin/vtrui1/config.json
Restart=always
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable vtrui1
systemctl restart vtrui1


v2nodeID=$(jq -r '.FORWARD.FWD1.upstream' /usr/local/bin/0conf)
FWD1path=$(jq -r '.FORWARD.FWD1.path' /usr/local/bin/0conf)
FWD1uuid=$(jq -r '.FORWARD.FWD1.uuid[]' /usr/local/bin/0conf)

v2servn=$(jq -r --arg v2nodeID "$v2nodeID" ".v2node[$v2nodeID].domain" /usr/local/bin/0conf)
domain=$(echo $v2servn | cut -d: -f1)
port=$(echo $v2servn | cut -d: -f2)
portCheck=$(echo $port | grep '^[0-9]\+$')
if [[ -z $portCheck ]]; then
port="443"
fi

uuidnum=$(jq -r --arg v2nodeID "$v2nodeID" ".v2node[$v2nodeID].uuid" /usr/local/bin/0conf)
v2path=$(jq -r --arg v2nodeID "$v2nodeID" ".v2node[$v2nodeID].path" /usr/local/bin/0conf)

cat > /usr/local/bin/vtrui1/config.json << EOF
{
  "dns":{"servers":["localhost"]},
  "inbounds":[
   {
      "port": 11811,
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "00000000-0000-0000-0000-000000000000",
            "level": 1
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/000000"
        }
      }
    }
  ],
  "outbounds": [
    {
      "tag": "proxy",
      "mux": {
        "enabled": true,
        "concurrency": 24
      },
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "xxxx.ooo",
            "port": 443,
            "users": [
              {
                "id": "00000000-0000-0000-0000-000000000000",
                "security": "auto",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "/000000"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "xxxx.ooo",
          "allowInsecure": false
        },
        "sockopt": {
          "mark": 255
        }
      }
    }
  ]
}
EOF

jq '.inbounds[0].settings.clients=[]' /usr/local/bin/vtrui1/config.json |\
jq --arg FWD1path "$FWD1path" '.inbounds[0].streamSettings.wsSettings.path=$FWD1path' |\
jq --arg domain "$domain" '.outbounds[0].settings.vnext[0].address=$domain' |\
jq --argjson port "$port" '.outbounds[0].settings.vnext[0].port=$port' |\
jq --arg uuidnum "$uuidnum" '.outbounds[0].settings.vnext[0].users[0].id=$uuidnum' |\
jq --arg v2path "$v2path" '.outbounds[0].streamSettings.wsSettings.path=$v2path' |\
jq --arg domain "$domain" '.outbounds[0].streamSettings.tlsSettings.serverName=$domain' >/tmp/vtrui1_temp

{
for v2uuids in $FWD1uuid; do
echo '{"id": "'$v2uuids'", "level": 1}'
done
} >/tmp/v2uuids

cat /tmp/v2uuids | while read v2uuids
do
jq --argjson v2uuids "$v2uuids" '.inbounds[0].settings.clients+=[$v2uuids]' /tmp/vtrui1_temp >/tmp/vtrui1_temp2 && mv -f /tmp/vtrui1_temp2 /tmp/vtrui1_temp
done

mv -f /tmp/vtrui1_temp /usr/local/bin/vtrui1/config.json

rm -rf /tmp/v2uuids

chmod 666 /usr/local/bin/vtrui1/config.json
