#!/bin/bash
FWD1port=$(jq -r '.FORWARD.FWD1.port' /usr/local/bin/0conf)
FWD1path=$(jq -r '.FORWARD.FWD1.path' /usr/local/bin/0conf)

cat << EOF >/etc/nginx/conf.d/forward1.conf
server {
  listen $FWD1port quic reuseport;
  listen $FWD1port ssl http2 fastopen=128 reuseport;
  root /var/www/html;
  
  ssl_certificate /var/www/ssl/de_GWD.cer;
  ssl_certificate_key /var/www/ssl/de_GWD.key;
  ssl_dhparam /var/www/ssl/dhparam.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers TLS13+AESGCM+AES128:TLS13+AESGCM+AES256:TLS13+CHACHA20:EECDH+ECDSA+AESGCM+AES128:EECDH+ECDSA+CHACHA20:EECDH+ECDSA+AESGCM+AES256:EECDH+ECDSA+AES128+SHA:EECDH+ECDSA+AES256+SHA:EECDH+aRSA+AESGCM+AES128:EECDH+aRSA+CHACHA20:EECDH+aRSA+AESGCM+AES256:EECDH+aRSA+AES128+SHA:EECDH+aRSA+AES256+SHA:RSA+AES128+SHA:RSA+AES256+SHA:RSA+3DES;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 4k;

  ssl_early_data on;
  proxy_set_header Early-Data \$ssl_early_data;

  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_stapling_file /var/www/ssl/ocsp.resp;

  add_header alt-svc 'quic=":$FWD1port"; h3-27=":$FWD1port"; h3-25=":$FWD1port"; h3-T050=":$FWD1port"; h3-Q050=":$FWD1port"; h3-Q049=":$FWD1port"; h3-Q048=":$FWD1port"; h3-Q046=":$FWD1port"; h3-Q043=":$FWD1port"; ma=86400';
  add_header Referrer-Policy                    no-referrer;
  add_header X-Content-Type-Options             nosniff;
  add_header X-Download-Options                 noopen;
  add_header X-Frame-Options                    DENY;
  add_header X-Permitted-Cross-Domain-Policies  none;
  add_header X-Robots-Tag                       none;
  add_header X-XSS-Protection                   "1; mode=block";
  add_header Strict-Transport-Security          "max-age=63072000" always;

location ~ /\.(?!well-known).* {
  deny all;
}

location $FWD1path {
  proxy_pass                http://127.0.0.1:11811;
  proxy_http_version        1.1;
  proxy_set_header          Host \$http_host;
  proxy_set_header          Upgrade "WebSocket";
  proxy_set_header          Connection "upgrade";
  proxy_set_header          X-Real-IP \$remote_addr;
  proxy_set_header          X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_redirect            off;
  keepalive_requests        25600;
  keepalive_timeout         300 300;
  proxy_buffering           off;
  proxy_buffer_size         8k;
}
}
EOF

if [[ -f "/lib/systemd/system/nginx.service" ]];then
    sed -i '/ssl_early_data/d' /etc/nginx/conf.d/forward1.conf
    sed -i '/quic/d' /etc/nginx/conf.d/forward1.conf
fi

/etc/nginx/conf.d/merge.sh
