#!/bin/bash
FWD0path=$(jq -r '.FORWARD.FWD0.path' /usr/local/bin/0conf)
FWD0uuid=$(jq -r '.FORWARD.FWD0.uuid[]' /usr/local/bin/0conf)

vtruiIn='{"port":11810,"listen":"127.0.0.1","protocol":"vmess","settings":{"clients":[]},"streamSettings":{"network":"ws","wsSettings":{"path":"/0000"}}}'

jq --argjson vtruiIn "$vtruiIn" '.inbounds[1] = $vtruiIn' /usr/local/bin/vtrui/config.json |\
jq --arg FWD0path "$FWD0path" '.inbounds[1].streamSettings.wsSettings.path=$FWD0path' >/tmp/vtrui_temp

{
for v2uuids in $FWD0uuid; do
echo '{"id": "'$v2uuids'", "level": 1, "alterId": 0}'
done
} >/tmp/v2uuids

cat /tmp/v2uuids | while read v2uuids
do
jq --argjson v2uuids "$v2uuids" '.inbounds[1].settings.clients+=[$v2uuids]' /tmp/vtrui_temp >/tmp/vtrui_temp2 && mv -f /tmp/vtrui_temp2 /tmp/vtrui_temp
done

mv -f /tmp/vtrui_temp /usr/local/bin/vtrui/config.json

rm -rf /tmp/v2uuids

chmod 666 /usr/local/bin/vtrui/config.json
