#!/bin/bash
rm -rf /etc/nginx/conf.d/forward0.conf
jq "del(.inbounds[1])" /opt/de_GWD/vtrui/config.json | sponge /opt/de_GWD/vtrui/config.json
systemctl restart vtrui >/dev/null
systemctl reload nginx >/dev/null
