#!/bin/bash
FWD1port=$(jq -r '.FORWARD.FWD1.port' /usr/local/bin/0conf)
FWD1path=$(jq -r '.FORWARD.FWD1.path' /usr/local/bin/0conf)

cat << EOF >/etc/nginx/conf.d/forward1.conf
server {
  listen $FWD1port ssl http2 fastopen=128 reuseport;

  ssl_certificate /var/www/ssl/de_GWD.cer;
  ssl_certificate_key /var/www/ssl/de_GWD.key;
  ssl_dhparam /var/www/ssl/dhparam.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers TLS13+AESGCM+AES128:TLS13+AESGCM+AES256:TLS13+CHACHA20:EECDH+ECDSA+AESGCM+AES128:EECDH+ECDSA+CHACHA20:EECDH+ECDSA+AESGCM+AES256:EECDH+ECDSA+AES128+SHA:EECDH+ECDSA+AES256+SHA:EECDH+aRSA+AESGCM+AES128:EECDH+aRSA+CHACHA20:EECDH+aRSA+AESGCM+AES256:EECDH+aRSA+AES128+SHA:EECDH+aRSA+AES256+SHA:RSA+AES128+SHA:RSA+AES256+SHA:RSA+3DES;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 4k;

  ssl_early_data on;
  proxy_set_header Early-Data \$ssl_early_data;

  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_stapling_file /var/www/ssl/ocsp.resp;

  add_header Referrer-Policy "no-referrer" always;
  add_header X-Content-Type-Options "nosniff" always;
  add_header X-Download-Options "noopen" always;
  add_header X-Frame-Options "SAMEORIGIN" always;
  add_header X-Permitted-Cross-Domain-Policies "none" always;
  add_header X-Robots-Tag "none" always;
  add_header X-XSS-Protection "1; mode=block" always;
  add_header Strict-Transport-Security "max-age=63072000" always;

location $FWD1path {
  proxy_pass                http://127.0.0.1:11811;
  proxy_http_version        1.1;
  proxy_set_header          Host \$http_host;
  proxy_set_header          Upgrade "WebSocket";
  proxy_set_header          Connection "upgrade";
  proxy_set_header          X-Real-IP \$remote_addr;
  proxy_set_header          X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_connect_timeout     432000;
  proxy_send_timeout        432000;
  proxy_read_timeout        432000;
  proxy_redirect            off;
  proxy_buffering           off;
  proxy_buffer_size         4k;
}
}
EOF

if [[ -f "/lib/systemd/system/nginx.service" ]];then
    sed -i '/ssl_early_data/d' /etc/nginx/conf.d/forward1.conf
fi

rm -rf /usr/local/bin/vtrui1
mkdir -p /usr/local/bin/vtrui1
cp -f /usr/local/bin/vtrui/vtrui /usr/local/bin/vtrui1/vtrui1
cp -f /usr/local/bin/vtrui/v2ctl /usr/local/bin/vtrui1/v2ctl
chmod -R +x /usr/local/bin/vtrui1

cat << "EOF" > /lib/systemd/system/vtrui1.service
[Unit]
Description=vtrui1 Service
After=network.target nss-lookup.target
Wants=network-online.target

[Service]
User=root
Type=simple
LimitNPROC=64000
LimitNOFILE=1000000
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
ExecStart=/usr/local/bin/vtrui1/vtrui1 -config /usr/local/bin/vtrui1/config.json
Restart=always
RestartSec=2
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable vtrui1
systemctl restart vtrui1
