#!/bin/bash
jq 'del(.dns.hosts[])' /etc/vtrui/config.json |\
jq --arg key "geosite:category-ads" --arg value "127.0.0.1" '.dns.hosts += {($key): ($value)}' |\
jq --arg key "ext:h2y.dat:ad" --arg value "127.0.0.1" '.dns.hosts += {($key): ($value)}' |\
jq --arg key "localhost" --arg value "127.0.0.1" '.dns.hosts += {($key): ($value)}' > /etc/vtrui/temp.json

cat /var/www/html/hostscustomize.txt >> /tmp/hostsdefault

cat /tmp/hostsdefault | while read line 
do
	key=$(echo $line | awk '{print$1}')
	value=$(echo $line | awk '{print$2}')
jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

systemctl restart vtrui

rm -rf /etc/vtrui/temp*.json
rm -rf /tmp/hostsdefault
