#!/bin/bash
clear
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }


installWGcore(){
echo "deb http://deb.debian.org/debian/ unstable main" > /etc/apt/sources.list.d/unstable.list
printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable
apt update

if [[ $(uname -m) == "x86_64" ]] && [[ $(uname -r) < "5.6" ]]; then
    red "Update kernel first!"
elif [[ $(uname -m) == "x86_64" ]] && [[ $(uname -r) > "5.6" ]]; then
    apt install wireguard-tools
elif [[ $(uname -m) == "aarch64" ]]; then
    apt install wireguard-dkms wireguard-tools
fi

if [[ $(jq -r '.wireguard.sprivatekey' /opt/de_GWD/0conf) = "null" ]]; then
    /opt/de_GWD/ui-WGchangeKey
fi

blue "------------------------"
blue "Install WireGuard [done]"
blue "------------------------"
}


start_menu(){
    green "==============================="
    green "         Wireguard"
    green "==============================="
    green  "1. Install Wireguard"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installWGcore
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu