#!/bin/bash
installFRPcmd=$(jq -r '.updateCMD' /usr/local/bin/0conf)
CMD="/usr/local/bin/ttyd -p 3000 -o $installFRPcmd"

popupWindow="window.open('"http://$localIP:3000"', 'popupWindow', 'width=800, height=600, scrollbars=yes');"

sed -i "/popupWindow/c\\$popupWindow" /var/www/html/!ddns.php

cat << EOF >/usr/local/bin/ui-installFRP
#!/bin/bash
$CMD
EOF
chmod +x ui-installFRP

cat << EOF >/lib/systemd/system/ttyd.service
[Unit]
Description=ttyd
After=network.target

[Service]
User=root
Type=oneshot
ExecStart=/bin/bash /usr/local/bin/ui-installFRP
ExecStop=/bin/kill -9 \$MAINPID
KillMode=process
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload >/dev/null 2>&1

chmod 666 /usr/local/bin/0conf
