#!/bin/bash
cat << "EOF" >/usr/local/bin/ui-installFRP
#!/bin/bash
clear

deployFRP(){
cd ~
wget --no-check-certificate -O ~/frp.tar.gz https://raw.githubusercontent.com/jacyl4/de_GWD/master/resource/frp_linux_amd64.tar.gz
tar zxvf ~/frp.tar.gz

mkdir -p /usr/local/bin/frp
mv -f ~/frp_*/frpc /usr/local/bin/frp/frpc
chmod +x /usr/local/bin/frp/frpc
}

read -p "Do you wish to install FRP?" yn
    case $yn in
        [Yy]* ) deployFRP;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
EOF
chmod +x /usr/local/bin/ui-installFRP

rm -rf /lib/systemd/system/ttyd.service
cat << EOF >/lib/systemd/system/ttyd.service
[Unit]
Description=ttyd
After=network.target

[Service]
User=root
Type=oneshot
ExecStart=/usr/local/bin/ttyd -p 3000 -o  /usr/local/bin/ui-installFRP
KillMode=process
StartLimitBurst=0

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload >/dev/null 2>&1

chmod 666 /usr/local/bin/0conf
