#!/bin/bash
clear
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }


installFRP(){
cd ~
wget --no-check-certificate -O ~/frp.tar.gz https://raw.githubusercontent.com/jacyl4/de_GWD/master/resource/frp_linux_amd64.tar.gz
tar zxvf ~/frp.tar.gz

mkdir -p /usr/local/bin/frp
mv -f ~/frp_*/frpc /usr/local/bin/frp/frpc
chmod +x /usr/local/bin/frp/frpc

rm -rf ~/frp*
}


start_menu(){
    green "==============================="
    green "         FRP"
    green "==============================="
    green  "1. Install FRP"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installFRP
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu