#!/bin/bash
clear
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }


installNetdata(){
if [[ -f "/usr/libexec/netdata/netdata-updater.sh" ]]; then
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --dont-start-it --stable-channel --disable-telemetry --reinstall
else
bash <(curl -Ss https://my-netdata.io/kickstart.sh) --dont-wait --dont-start-it --stable-channel --disable-telemetry
fi

systemctl restart netdata
blue "----------------------"
blue "Install Netdata [done]"
blue "----------------------"
}



updateNetdata(){
if [[ -f "/usr/libexec/netdata/netdata-updater.sh" ]]; then
/usr/libexec/netdata/netdata-updater.sh

blue "---------------------"
blue "Update Netdata [done]"
blue "---------------------"
fi
}



start_menu(){
    green "==============================="
    green "         Netdata"
    green "==============================="
    green  "1. Install Netdata"
    green  "2. Update Netdata"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installNetdata
    start_menu
    ;;
    2)
    updateNetdata
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu