#!/bin/bash
listB=$(cat /var/www/html/listB.txt | xargs echo -n | xargs -n1)
listW=$(cat /var/www/html/listW.txt | xargs echo -n | xargs -n1)

echo "$listB" > /var/www/html/listB.txt
echo "$listW" > /var/www/html/listW.txt

jq 'del(.dns.servers[2].domains[])' /etc/vtrui/config.json > /etc/vtrui/temp.json

if [[ ! -n "$listW" ]]; then
	jq '.dns.servers[2].domains=["domain:baidu.com"]' /etc/vtrui/temp.json > /etc/vtrui/config.json
else
	for listWpre in $listW; do
	jq --arg listWpre "domain:$listWpre" '.dns.servers[2].domains+=[$listWpre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
	done
	mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
fi

jq 'del(.dns.servers[3].domains[])' /etc/vtrui/config.json > /etc/vtrui/temp.json

if [[ ! -n "$listB" ]]; then
	jq '.dns.servers[3].domains=["domain:google.com"]' /etc/vtrui/temp.json > /etc/vtrui/config.json
else
	for listBpre in $listB; do
	jq --arg listBpre "domain:$listBpre" '.dns.servers[3].domains+=[$listBpre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
	done
	mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
fi
