#!/bin/bash
sed -i '1,$d' /var/www/html/listBip.txt
sed -i '1,$d' /var/www/html/listWip.txt

for listB in $(cat /var/www/html/listB.txt); do
  echo $(nslookup -port=5380 $listB | awk '/Address/ {print$2}' | sed '1d') >> /var/www/html/listBip.txt
done

for listW in $(cat /var/www/html/listW.txt); do
  echo $(nslookup -port=5370 $listW | awk '/Address/ {print$2}' | sed '1d') >> /var/www/html/listWip.txt
done

sed -i '/[a-z]/d' /var/www/html/listBip.txt
sed -i '/[a-z]/d' /var/www/html/listWip.txt
