#!/bin/bash
listw=$(cat /var/www/html/listw.txt | xargs echo -n | xargs -n1)
listb=$(cat /var/www/html/listb.txt | xargs echo -n | xargs -n1)

echo "$listw" > /var/www/html/listw.txt
echo "$listb" > /var/www/html/listb.txt

jq 'del(.dns.servers[1].domains[])' /etc/vtrui/config.json > /etc/vtrui/temp.json

if [[ ! -n "$listw" ]]; then
	jq '.dns.servers[1].domains=["domain:baidu.com"]' /etc/vtrui/temp.json > /etc/vtrui/config.json
else
	for listwpre in $(echo "$listw" | xargs -n1); do
	jq --arg listwpre "domain:$listwpre" '.dns.servers[1].domains+=[$listwpre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
	done
	mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
fi

jq 'del(.dns.servers[2].domains[])' /etc/vtrui/config.json > /etc/vtrui/temp.json

if [[ ! -n "$listb" ]]; then
	jq '.dns.servers[2].domains=["domain:google.com"]' /etc/vtrui/temp.json > /etc/vtrui/config.json
else
	for listbpre in $(echo "$listb" | xargs -n1); do
	jq --arg listbpre "domain:$listbpre" '.dns.servers[2].domains+=[$listbpre]' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
	done
	mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
fi
