#!/bin/bash
jq 'del(.dns.hosts[])' /etc/vtrui/config.json |\
jq --arg key "localhost" --arg value "127.0.0.1" '.dns.hosts += {($key): ($value)}' > /etc/vtrui/temp.json

for node in $(jq -r '.v2node[].domain' /usr/local/bin/0conf | cut -d: -f1); do
	nodename=$(echo $node | cut -d : -f1)
	nodeip=$(nslookup -port=5370 $nodename | awk '/Address/ {print$2}' | sed '1d' | sed '/[a-z]/d')
jq --arg key $nodename --arg value $nodeip '.dns.hosts += {($key): ($value)}' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

jq -r '.hosts | to_entries[] | [.key, .value] | @tsv' /usr/local/bin/0conf > /etc/vtrui/hosts
cat /etc/vtrui/hosts | while read line 
do
	key=$(echo $line | awk '{print$1}')
	value=$(echo $line | awk '{print$2}')
jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done
mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

if [[ $(jq -r '.v2ad' /usr/local/bin/0conf) == "on" ]]; then
/usr/local/bin/ui-v2adADD
fi

rm -rf /etc/vtrui/hosts
