#!/bin/bash
domain=$(jq -r '.v2nodeDIV.nodeCU.domain' /opt/de_GWD/0conf)
port=$(jq -r '.v2nodeDIV.nodeCU.port' /opt/de_GWD/0conf)
path=$(jq -r '.v2nodeDIV.nodeCU.path' /opt/de_GWD/0conf)
uuid=$(jq -r '.v2nodeDIV.nodeCU.uuid' /opt/de_GWD/0conf)

if [[ -z $domain ]] || [[ $domain = "null" ]]; then
domain=$(jq -r '.update.v2node.domain' /opt/de_GWD/0conf)
port=$(jq -r '.update.v2node.port' /opt/de_GWD/0conf)
path=$(jq -r '.update.v2node.path' /opt/de_GWD/0conf)
uuid=$(jq -r '.update.v2node.uuid' /opt/de_GWD/0conf)
fi

jq '.v2nodeDIV.nodeCU.display="on"' /opt/de_GWD/0conf |\
jq --arg domain $domain '.v2nodeDIV.nodeCU.domain=$domain' |\
jq --arg port $port '.v2nodeDIV.nodeCU.port=$port' |\
jq --arg path $path '.v2nodeDIV.nodeCU.path=$path' |\
jq --arg uuid $uuid '.v2nodeDIV.nodeCU.uuid=$uuid' | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

cat << EOF >/tmp/OBcu
{
      "tag": "custom",
      "mux": {
        "enabled": true,
        "concurrency": 8
      },
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "$domain",
            "port": $port,
            "users": [
              {
                "id": "$uuid",
                "encryption": "none",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "$path"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "$domain",
          "allowInsecure": false
        },
        "sockopt": {
          "mark": 255,
          "domainStrategy": "UseIPv4"
        }
      }
}
EOF

jq 'del(.outbounds[] | select(.tag == "custom"))' /opt/de_GWD/vtrui/config.json |\
jq --slurpfile OBcu /tmp/OBcu '.outbounds+=$OBcu' | sponge /opt/de_GWD/vtrui/config.json
chmod 666 /opt/de_GWD/vtrui/config.json

if [[ $1 == "r" ]]; then
  systemctl restart vtrui >/dev/null
fi

rm -rf /tmp/OBcu
