#!/bin/bash
domain=$(jq -r '.update.v2node.domain' /opt/de_GWD/0conf)
port=$(jq -r '.update.v2node.port' /opt/de_GWD/0conf)
path=$(jq -r '.update.v2node.path' /opt/de_GWD/0conf)
uuid=$(jq -r '.update.v2node.uuid' /opt/de_GWD/0conf)

jq '.v2nodeDIV.nodeNF.display="off"' /opt/de_GWD/0conf |\
jq '.v2nodeDIV.nodeCU.display="off"' |\
jq '.v2nodeDIV.nodeDT.display="off"' | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

cat << EOF >/opt/de_GWD/vtrui/config.json
{
"dns":{"servers":[{"address":"127.0.0.1","port":53}]},
"routing":{
  "rules":[
    {
      "type":"field",
      "ip":["geoip:private"],
      "outboundTag": "direct"
    },
    {
      "type":"field",
      "port":"53,4711,5310,5311,5320,5321,5350",
      "outboundTag": "direct"
    }
  ]
},
"inbounds":[
  {
    "port":9896,
    "listen":"127.0.0.1",
    "protocol":"dokodemo-door",
    "settings":{"network":"tcp,udp","followRedirect":true},
    "sniffing":{"enabled":true,"destOverride":["http","tls"]},
    "streamSettings":{"sockopt":{"tproxy":"tproxy"}}
  }
],
"outbounds":[
  {
    "tag":"default",
    "mux":{"enabled":true,"concurrency":8},
    "protocol":"vless",
    "settings":{"vnext":[{
          "address":"$domain",
          "port":$port,
          "users":[
            {
              "id":"$uuid",
              "encryption":"none",
              "level": 1
            }
          ]
        }
      ]
    },
    "streamSettings":{
      "network":"ws",
      "wsSettings":{
        "path":"$path"
      },
      "security":"tls",
      "tlsSettings":{
        "serverName":"$domain",
        "allowInsecure":false
      },
      "sockopt":{"mark":255,"domainStrategy":"UseIPv4"}
    }
  },
  {
    "tag":"direct",
    "protocol":"freedom",
    "settings":{"domainStrategy":"UseIPv4"},
    "streamSettings":{"sockopt":{"mark":255}}
  }
]
}
EOF
chmod 666 /opt/de_GWD/vtrui/config.json

systemctl restart vtrui
