#!/bin/bash
jq 'del(.dns.hosts[])' /etc/vtrui/config.json |\
jq --arg key "localhost" --arg value "127.0.0.1" '.dns.hosts += {($key): ($value)}' > /etc/vtrui/temp.json

for node in $(cat /var/www/html/domain.txt); do
	nodename=$(echo $node | cut -d : -f1)
	nodeip=$(nslookup -port=5391 $nodename | awk '/Address/' | awk 'NR==2{print}' | cut -d ' ' -f2)
jq --arg key $nodename --arg value $nodeip '.dns.hosts += {($key): ($value)}' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

cat /var/www/html/hostscustomize.txt > /etc/vtrui/hosts

cat /etc/vtrui/hosts | while read line 
do
	key=$(echo $line | awk '{print$1}')
	value=$(echo $line | awk '{print$2}')
jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /etc/vtrui/temp.json > /etc/vtrui/temp2.json && mv -f /etc/vtrui/temp2.json /etc/vtrui/temp.json
done

mv -f /etc/vtrui/temp.json /etc/vtrui/config.json

rm -rf /etc/vtrui/temp*.json
rm -rf /etc/vtrui/hosts
