#!/bin/bash
sed -i '/Nice=/d' /lib/systemd/system/smartdns.service
sed -i '/CPUSchedulingPolicy=/d' /lib/systemd/system/smartdns.service
sed -i '/CPUSchedulingPriority=/d' /lib/systemd/system/smartdns.service

sed -i '/Nice=/d' /lib/systemd/system/v2dns.service
sed -i '/CPUSchedulingPolicy=/d' /lib/systemd/system/v2dns.service
sed -i '/CPUSchedulingPriority=/d' /lib/systemd/system/v2dns.service

systemctl daemon-reload
systemctl restart smartdns
systemctl restart v2dns

jq --arg boostDNS "off" '.dns.boostDNS=$boostDNS' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
