#!/bin/bash
ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print$2;exit}' | cut -d':' -f1 | cut -d'@' -f1)
localaddr=$(ip a | grep "$ethernetnum" | awk '{print $2}' | awk 'END {print}' | cut -d'/' -f1)

dhcpStart=$(jq -r '.address.dhcpStart' /opt/de_GWD/0conf | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
dhcpEnd=$(jq -r '.address.dhcpEnd' /opt/de_GWD/0conf | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')

if [[ -n $dhcpStart ]] && [[ -n $dhcpEnd ]]; then
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.enabled "true"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.interface_name "$ethernetnum"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.dhcpv4.gateway_ip "$localaddr"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.dhcpv4.subnet_mask "255.255.255.0"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.dhcpv4.range_start "$dhcpStart"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.dhcpv4.range_end "$dhcpEnd"
	yq w -i /opt/AdGuardHome/AdGuardHome.yaml dhcp.dhcpv4.lease_duration "86400"

	systemctl restart AdGuardHome
fi