#!/bin/bash
server2=$(jq '.dns.servers[3].domains - ["geosite:apple","domain:icloud.com","domain:icloud-content.com"] ' /opt/de_GWD/v2dns/config.json)

jq --argjson server1 "$server2" '.dns.servers[3].domains=$server1' /opt/de_GWD/v2dns/config.json >/tmp/v2dns_config

jq 'del(.dns.APPLEdir)' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

if [[ -n $(cat /tmp/v2dns_config) ]]; then
  mv -f /tmp/v2dns_config /opt/de_GWD/v2dns/config.json
fi

chmod 666 /opt/de_GWD/v2dns/config.json
chmod 666 /opt/de_GWD/0conf
