#!/bin/bash
FRPdomain=$(jq -r '.FRP.domain' /opt/de_GWD/0conf)
FRPbindPort=$(jq -r '.FRP.bindPort' /opt/de_GWD/0conf)
FRPtoken=$(jq -r '.FRP.token' /opt/de_GWD/0conf)
FRPbindProtocol=$(jq -r '.FRP.bindProtocol' /opt/de_GWD/0conf)

FRPremotePort=$(jq -r '.FRP.remotePort' /opt/de_GWD/0conf)
FRPlocalPort=$(jq -r '.FRP.localPort' /opt/de_GWD/0conf)
FRPprotocol=$(jq -r '.FRP.protocol' /opt/de_GWD/0conf)

cat << EOF >/lib/systemd/system/frpc.service
[Unit]
Description=Frp Client Service
After=network.target

[Service]
User=root
Type=simple
CapabilityBoundingSet=CAP_NET_RAW CAP_NET_ADMIN
ExecStart=/opt/de_GWD/frp/frpc -c /opt/de_GWD/frp/frpc.ini
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload

cat << EOF >/opt/de_GWD/frp/frpc.ini
[common]
server_addr = $FRPdomain
server_port = $FRPbindPort
protocol = $(echo $FRPbindProtocol | tr '[:upper:]' '[:lower:]')
token = $FRPtoken

[FRP]
type = $(echo $FRPprotocol | tr '[:upper:]' '[:lower:]')
local_ip = 127.0.0.1
remote_port = $FRPremotePort
local_port = $FRPlocalPort
EOF
