#!/bin/bash
server1=$(jq '.dns.servers[1].domains - ["geosite:apple-cn"]' /usr/local/bin/v2dns/config.json)

jq --argjson server1 "$server1" '.dns.servers[1].domains=$server1' /usr/local/bin/v2dns/config.json >/tmp/v2dns_config

jq 'del(.dns.APPLEdir)' /usr/local/bin/0conf >/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

if [[ -n $(cat /tmp/v2dns_config) ]]; then
  mv -f /tmp/v2dns_config /usr/local/bin/v2dns/config.json
fi

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /usr/local/bin/0conf
