#!/bin/bash
systemctl stop v2dns
systemctl stop vtrui
systemctl stop iptables-proxy

rm -rf /etc/resolv.conf
rm -rf /run/resolvconf/interface
cat /dev/null >/etc/resolvconf/resolv.conf.d/head
cat /dev/null >/etc/resolvconf/resolv.conf.d/original
cat /dev/null >/etc/resolvconf/resolv.conf.d/tail
echo "nameserver 127.0.0.1" >/etc/resolvconf/resolv.conf.d/base
ln -fs /etc/resolvconf/run/resolv.conf /etc/resolv.conf
resolvconf -u

yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.upstream_dns[0] "127.0.0.1:5310"
yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.bootstrap_dns[0] "127.0.0.1:5310"
systemctl restart AdGuardHome
