#!/bin/bash
dohNUM=$1
url=$(awk '/url =/' /etc/dns-over-https/doh-client.conf | cut -d/ -f3 | awk NR==$dohNUM)
echo "$(curl -o /dev/null -Isw '%{time_starttransfer}\n' $url) * 1000" | bc | awk '{printf ("%.0f\n",$1)}' 
