#!/bin/bash
/opt/de_GWD/ui_2h

>/etc/resolvconf/resolv.conf.d/head
>/etc/resolvconf/resolv.conf.d/original
>/etc/resolvconf/resolv.conf.d/tail
rm -rf /etc/resolv.conf
rm -rf /run/resolvconf/interface
echo "nameserver 127.0.0.1" >/etc/resolvconf/resolv.conf.d/base
ln -fs /etc/resolvconf/run/resolv.conf /etc/resolv.conf
resolvconf -u

yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.upstream_dns ""
yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.upstream_dns[0] "127.0.0.1:5350"
yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.bootstrap_dns ""
yq w -i /opt/AdGuardHome/AdGuardHome.yaml dns.bootstrap_dns[0] "127.0.0.1:5350"
systemctl reload AdGuardHome >/dev/null 2>&1
systemctl restart iptables-proxy

/opt/de_GWD/tcpTime

systemctl restart v2dns
systemctl restart vtrui
