#!/bin/bash
cd /var/www/html/restore

unzip /var/www/html/restore/de_GWD_backup.zip

mv -f /var/www/html/restore/de_GWD_backup/*.txt /var/www/html/
mv -f /var/www/html/restore/de_GWD_backup/*key /etc/wireguard/

chown -R www-data:www-data /var/www/html/*.txt

rm -rf /var/www/html/de_GWD_backup.zip
rm -rf /var/www/html/restore/de_GWD_backup.zip
