#!/bin/bash
doh1=$(jq -r '.dns.doh1' /opt/de_GWD/0conf)
doh2=$(jq -r '.dns.doh2' /opt/de_GWD/0conf)

doh1Domain=$(echo $doh1 | cut -d/ -f1 | cut -d: -f1)
doh2Domain=$(echo $doh2 | cut -d/ -f1 | cut -d: -f1)

doh1IP=$(dig @127.0.0.1 $doh1Domain -4p 5310 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
doh2IP=$(dig @127.0.0.1 $doh2Domain -4p 5310 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

doh1Port=$(echo $doh1 | cut -d/ -f1 | cut -d: -f2 | grep '^[[:digit:]]*$')
doh2Port=$(echo $doh2 | cut -d/ -f1 | cut -d: -f2 | grep '^[[:digit:]]*$')

doh1PortStr=$([ -n "$doh1Port" ] && echo $doh1Port | sed 's/^/:/')
doh2PortStr=$([ -n "$doh2Port" ] && echo $doh2Port | sed 's/^/:/')

echo $doh1IP $doh2IP | xargs -n 1 | sort | uniq >/opt/de_GWD/IPdoh
sed -i '/^\s*$/d' /opt/de_GWD/IPdoh
sed -i 's/^/add doh &/g' /opt/de_GWD/IPdoh
mv -f /opt/de_GWD/IPdoh /opt/de_GWD/IPdohSET
ipset -! -R </opt/de_GWD/IPdohSET

if [[ -z $(jq -r '.dns.china' /opt/de_GWD/0conf) ]] || [[ $(jq -r '.dns.china' /opt/de_GWD/0conf) = "null" ]]; then
  jq --arg dnsChina "114.114.114.114 114.114.115.115 119.29.29.29 119.28.28.28 182.254.118.118 223.5.5.5 223.6.6.6" '.dns.china=$dnsChina' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
fi
chmod 666 /opt/de_GWD/0conf

sed -i '/server /,$d' /etc/smartdns/smartdns.conf
for dnsChina in $(jq -r '.dns.china' /opt/de_GWD/0conf); do
  if [[ -n $dnsChina ]]; then
    echo "server $dnsChina" >>/etc/smartdns/smartdns.conf
  fi
done

if [[ -n $doh1IP ]] && [[ $doh1IP != "127.0.0.1" ]]; then
if [[ -z $doh2IP ]]; then
doh2Domain=$doh1Domain
doh2IP=$doh1IP
doh2PortStr=$doh1PortStr
fi

sed -i '/server-https /,$d' /etc/smartdns/smartdns.conf
cat << EOF >>/etc/smartdns/smartdns.conf

server-https https://$doh1IP$doh1PortStr/dq -host-name $doh1Domain -exclude-default-group -group doh
server-https https://$doh2IP$doh2PortStr/dq -host-name $doh2Domain -exclude-default-group -group doh
EOF
fi

systemctl restart smartdns >/dev/null

jq '.dns.servers[4].domains=[]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
jq --arg doh1Domain $doh1Domain '.dns.servers[4].domains+=[$doh1Domain]' /opt/de_GWD/v2dns/config.json |\
jq --arg doh2Domain $doh2Domain '.dns.servers[4].domains+=[$doh2Domain]' | sponge /opt/de_GWD/v2dns/config.json

chmod 666 /opt/de_GWD/v2dns/config.json
