#!/bin/bash
jq '.dns.hosts={"localhost": "127.0.0.1"}' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp

jq -r '.hosts | to_entries[] | [.key, .value] | @tsv' /usr/local/bin/0conf >/tmp/hosts
cat /tmp/hosts | while read hosts 
do
	key=$(echo $hosts | awk '{print$1}')
	value=$(echo $hosts | awk '{print$2}')
	jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /tmp/v2dns_temp >/tmp/v2dns_temp2 && mv -f /tmp/v2dns_temp2 /tmp/v2dns_temp
done

if [[ $(awk '/listW/ {print;exit}' /usr/local/bin/0conf) =~ "[" ]]; then
	listW=$(jq -r '.listW[]' /usr/local/bin/0conf)
elif [[ $(awk '/listW/ {print;exit}' /usr/local/bin/0conf) =~ "{" ]]; then
	listW=$(jq -r '.listW | keys[]' /usr/local/bin/0conf)
fi

jq -r '.v2node[].domain' /usr/local/bin/0conf | cut -d: -f1 >/tmp/listW
if [[ -n "$listW" ]]; then
	echo $listW  >>/tmp/listW
fi
jq '.listW=[]' /usr/local/bin/0conf >/tmp/0conf_temp
for listWpre in $(cat /tmp/listW); do
	jq --arg listWpre $listWpre '.listW += [$listWpre]' /tmp/0conf_temp >/tmp/0conf_temp2 && mv -f /tmp/0conf_temp2 /tmp/0conf_temp
done

mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json
mv -f /tmp/0conf_temp /usr/local/bin/0conf

if [[ $(jq -r '.v2ad' /usr/local/bin/0conf) == "on" ]]; then
/usr/local/bin/ui-v2adADD
else
/usr/local/bin/ui-v2adDEL
fi

/usr/local/bin/ui-changeDOH

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /usr/local/bin/vtrui/config.json
chmod 666 /usr/local/bin/0conf
