#!/bin/bash
jq 'del(.dns.hosts[])' /usr/local/bin/v2dns/config.json |\
jq '.dns.hosts += {"localhost": "127.0.0.1"}' >/tmp/v2dns_temp

jq -r '.hosts | to_entries[] | [.key, .value] | @tsv' /usr/local/bin/0conf >>/tmp/hosts

cat /tmp/hosts | while read line 
do
	key=$(echo $line | awk '{print$1}')
	value=$(echo $line | awk '{print$2}')
jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /tmp/v2dns_temp >/tmp/v2dns_temp2 && mv -f /tmp/v2dns_temp2 /tmp/v2dns_temp
done
mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json

rm -rf /tmp/v2dns_temp*
rm -rf /tmp/hosts

if [[ $(jq -r '.v2ad' /usr/local/bin/0conf) == "on" ]]; then
output=`/usr/local/bin/ui-v2adADD`
else
output=`/usr/local/bin/ui-v2adDEL`
fi

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /usr/local/bin/0conf