#!/bin/bash
if [[ $(awk '/listB/ {print;exit}' /opt/de_GWD/0conf) =~ "[" ]]; then
	jq -r '.listB[]' /opt/de_GWD/0conf >/tmp/listBpre2
elif [[ $(awk '/listB/ {print;exit}' /opt/de_GWD/0conf) =~ "{" ]]; then
	jq -r '.listB | keys[]' /opt/de_GWD/0conf >/tmp/listBpre2
fi

sort /tmp/listBpre2 | uniq | sed '/^\s*$/d' >/tmp/listBpre

cat /dev/null >/opt/de_GWD/IPlistB
jq '.dns.servers[1].domains=["keyword:play.googleapi.cn"]' /opt/de_GWD/v2dns/config.json >/tmp/v2dns_temp
if [[ -n $(cat /tmp/listBpre) ]]; then
	jq '.listB={}' /opt/de_GWD/0conf >/tmp/0conf_temp
	cat /dev/null > /opt/de_GWD/IPlistB
	cat /tmp/listBpre | while read listB 
	do
		jq --arg listB "keyword:$listB" '.dns.servers[1].domains+=[$listB]' /tmp/v2dns_temp | sponge /tmp/v2dns_temp
		listBIP=$(dig @127.0.0.1 $listB -p 5390 +short | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
		echo $listBIP | sed 's/ /\n/g ' >> /opt/de_GWD/IPlistB
		jq -n --arg listBIP "$listBIP" '$listBIP | split("\n") | to_entries[] | [.value] | @tsv' >/tmp/listBIPs
		jq --arg key "$listB" --slurpfile value /tmp/listBIPs '.listB += {($key):$value}' /tmp/0conf_temp | sponge /tmp/0conf_temp
	done
	mv -f /tmp/0conf_temp /opt/de_GWD/0conf
fi
mv -f /tmp/v2dns_temp /opt/de_GWD/v2dns/config.json



if [[ $(awk '/listW/ {print;exit}' /opt/de_GWD/0conf) =~ "[" ]]; then
	jq -r '.listW[]' /opt/de_GWD/0conf >/tmp/listWpre2
elif [[ $(awk '/listW/ {print;exit}' /opt/de_GWD/0conf) =~ "{" ]]; then
	jq -r '.listW | keys[]' /opt/de_GWD/0conf >/tmp/listWpre2
fi

sort /tmp/listWpre2 | uniq | sed '/^\s*$/d' >/tmp/listWpre

cat /dev/null >/opt/de_GWD/IPlistW
jq '.dns.servers[3].domains=["keyword:live.com"]' /opt/de_GWD/v2dns/config.json >/tmp/v2dns_temp
if [[ -n $(cat /tmp/listWpre) ]]; then
	jq '.listW={}' /opt/de_GWD/0conf >/tmp/0conf_temp
	cat /dev/null > /opt/de_GWD/IPlistW
	cat /tmp/listWpre | while read listW
	do
		jq --arg listW "keyword:$listW" '.dns.servers[3].domains+=[$listW]' /tmp/v2dns_temp | sponge /tmp/v2dns_temp
		listWIP=$(dig @127.0.0.1 $listW -p 5310 +short | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$')
		echo $listWIP | sed 's/ /\n/g ' >> /opt/de_GWD/IPlistW
		jq -n --arg listWIP "$listWIP" '$listWIP | split("\n") | to_entries[] | [.value] | @tsv' >/tmp/listWIPs
		jq --arg key "$listW" --slurpfile value /tmp/listWIPs '.listW += {($key):$value}' /tmp/0conf_temp | sponge /tmp/0conf_temp
	done
	mv -f /tmp/0conf_temp /opt/de_GWD/0conf		
fi
mv -f /tmp/v2dns_temp /opt/de_GWD/v2dns/config.json



if [[ -n $(awk '/listBlan/ {print;exit}' /opt/de_GWD/0conf) ]]; then
	cat /dev/null >/opt/de_GWD/IPlistBlan
	listBlan=$(jq -r '.listBlan[]' /opt/de_GWD/0conf)
	if [[ -n $listBlan ]]; then
		echo $listBlan >/opt/de_GWD/IPlistBlan
	fi
fi



if [[ -n $(awk '/listWlan/ {print;exit}' /opt/de_GWD/0conf) ]]; then
	cat /dev/null >/opt/de_GWD/IPlistWlan
	listWlan=$(jq -r '.listWlan[]' /opt/de_GWD/0conf)
	if [[ -n $listWlan ]]; then
		echo $listWlan >/opt/de_GWD/IPlistWlan
	fi
fi



if [[ $(jq -r '.dns.APPLEdir' /opt/de_GWD/0conf) == "on" ]]; then
/opt/de_GWD/ui-onAPPLE
else
/opt/de_GWD/ui-offAPPLE
fi

rm -rf /tmp/listB*
rm -rf /tmp/listW*
rm -rf /tmp/v2dns*

chmod 666 /opt/de_GWD/v2dns/config.json
chmod 666 /opt/de_GWD/0conf
