#!/bin/bash
jq 'del(.dns.hosts[])' /etc/vtrui/config.json |\
jq '.dns.hosts += {"localhost": "127.0.0.1"}' > /tmp/vtrui_temp

jq -r '.hosts | to_entries[] | [.key, .value] | @tsv' /usr/local/bin/0conf > /etc/vtrui/hosts
cat /etc/vtrui/hosts | while read line 
do
	key=$(echo $line | awk '{print$1}')
	value=$(echo $line | awk '{print$2}')
jq --arg key $key --arg value $value '.dns.hosts += {($key): ($value)}' /tmp/vtrui_temp > /tmp/vtrui_temp2 && mv -f /tmp/vtrui_temp2 /tmp/vtrui_temp
done

jq -r '.v2node[].domain' /usr/local/bin/0conf | cut -d: -f1 > /tmp/node
cat /tmp/node | while read line 
do
	jq --arg node "$line" '.listW+=[$node]' /usr/local/bin/0conf > /tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf
done

mv -f /tmp/vtrui_temp /etc/vtrui/config.json

if [[ $(jq -r '.v2ad' /usr/local/bin/0conf) == "on" ]]; then
/usr/local/bin/ui-v2adADD
else
/usr/local/bin/ui-v2adDEL
fi

/usr/local/bin/ui-changeDOH
/usr/local/bin/ui-saveListBW

rm -rf /etc/vtrui/temp*.json
rm -rf /etc/vtrui/hosts
