#!/bin/bash
sed -i '/server /d' /etc/smartdns/smartdns.conf

if [[ -z $(jq -r '.dns.china' /opt/de_GWD/0conf 2>/dev/null) ]] || [[ $(jq -r '.dns.china' /opt/de_GWD/0conf) = "null" ]]; then
	jq --arg dnsChina "114.114.114.114 114.114.115.115 119.29.29.29 119.28.28.28 223.5.5.5 223.6.6.6" '.dns.china=$dnsChina' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
fi

for dnsChina in $(jq -r '.dns.china' /opt/de_GWD/0conf); do
	if [[ -n $dnsChina ]]; then
		echo "server $dnsChina" >>/etc/smartdns/smartdns.conf
	fi
done
