#!/bin/bash
jq -r '.listB | keys[]' /usr/local/bin/0conf >/tmp/listBpre2

jq -r '.listW | keys[]' /usr/local/bin/0conf >/tmp/listWpre2

sort /tmp/listBpre2 | uniq | sed '/^\s*$/d' >/tmp/listBpre

jq 'del(.dns.servers[1].domains[])' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp
if [[ -z $(cat /tmp/listBpre) ]]; then
	jq '.dns.servers[1].domains=["domain:google.com"]' /tmp/v2dns_temp > /usr/local/bin/v2dns/config.json
else
	jq '.listB={}' /usr/local/bin/0conf >/tmp/0conf_temp
	cat /tmp/listBpre | while read listB 
	do
		jq --arg listB "keyword:$listB" '.dns.servers[1].domains+=[$listB]' /tmp/v2dns_temp >/tmp/v2dns_temp2 && mv -f /tmp/v2dns_temp2 /tmp/v2dns_temp
		listBIP=$(nslookup -port=5380 $listB | awk '/Address/ {print$2}' | sed '1d' | sed '/[a-z]/d')
		jq -n --arg listBIP "$listBIP" '$listBIP | split("\n") | to_entries[] | [.value] | @tsv' >/tmp/listBIPs
		jq --arg key "$listB" --slurpfile value /tmp/listBIPs '.listB += {($key):$value}' /tmp/0conf_temp >/tmp/0conf_temp2 && mv -f /tmp/0conf_temp2 /tmp/0conf_temp
	done
	mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json
	mv -f /tmp/0conf_temp /usr/local/bin/0conf
fi

jq -r '.v2node[].domain' /usr/local/bin/0conf | cut -d: -f1 >>/tmp/listWpre2
sort /tmp/listWpre2 | uniq | sed '/^\s*$/d' >/tmp/listWpre

jq 'del(.dns.servers[2].domains[])' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp
if [[ -z $(cat /tmp/listWpre) ]]; then
	jq '.dns.servers[2].domains=["domain:baidu.com"]' /tmp/v2dns_temp > /usr/local/bin/v2dns/config.json
else
	jq '.listW={}' /usr/local/bin/0conf >/tmp/0conf_temp
	cat /tmp/listWpre | while read listW
	do
		jq --arg listW "keyword:$listW" '.dns.servers[2].domains+=[$listW]' /tmp/v2dns_temp >/tmp/v2dns_temp2 && mv -f /tmp/v2dns_temp2 /tmp/v2dns_temp
		listWIP=$(nslookup -port=5310 $listW | awk '/Address/ {print$2}' | sed '1d' | sed '/[a-z]/d')
		jq -n --arg listWIP "$listWIP" '$listWIP | split("\n") | to_entries[] | [.value] | @tsv' >/tmp/listWIPs
		jq --arg key "$listW" --slurpfile value /tmp/listWIPs '.listW += {($key):$value}' /tmp/0conf_temp >/tmp/0conf_temp2 && mv -f /tmp/0conf_temp2 /tmp/0conf_temp
	done
	mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json
	mv -f /tmp/0conf_temp /usr/local/bin/0conf
fi

rm -rf /tmp/listB*
rm -rf /tmp/listW*
rm -rf /tmp/v2dns_temp*

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /usr/local/bin/0conf
