#!/bin/bash
cat << EOF >/usr/local/bin/ui-update
#!/bin/bash
/usr/local/bin/ttyd -p 3000 -o $(jq -r '.updateCMD' /usr/local/bin/0conf)
EOF
chmod +x /usr/local/bin/ui-update

nohup /usr/local/bin/ui-update >/dev/null 2>&1
