#!/bin/bash
systemctl stop ttyd

systemctl stop v2dns
systemctl stop vtrui
systemctl stop iptables-proxy

rm -rf /etc/resolv.conf
cat > /etc/resolv.conf << EOF
nameserver 119.29.29.29
nameserver 119.28.28.28
nameserver 223.5.5.5
nameserver 223.6.6.6
EOF
