#!/bin/bash
systemctl stop updateGWD

systemctl stop iptables-proxy
systemctl stop vtrui
systemctl stop v2dns
systemctl stop AdGuardHome

rm -rf /etc/resolv.conf
cat << EOF >/etc/resolv.conf
nameserver 114.114.114.114
nameserver 114.114.115.115
nameserver 119.29.29.29
nameserver 119.28.28.28
nameserver 223.5.5.5
nameserver 223.6.6.6
EOF

sed -i '/^\s*$/d' /opt/de_GWD/0conf
if [[ -z $(cat /opt/de_GWD/0conf) ]]; then
	cp -f /opt/de_GWD/0conf_bak /opt/de_GWD/0conf
	chmod 666 /opt/de_GWD/0conf
fi