#!/bin/bash
systemctl stop updateGWD

systemctl stop v2dns
systemctl stop vtrui
systemctl stop iptables-proxy

rm -rf /etc/resolv.conf
cat > /etc/resolv.conf << EOF
nameserver 119.29.29.29
nameserver 119.28.28.28
nameserver 114.114.114.114
nameserver 114.114.115.115
EOF

sed -i '/^\s*$/d' /usr/local/bin/0conf
if [[ -z $(cat /usr/local/bin/0conf) ]]; then
	cp -f /usr/local/bin/0conf_bak /usr/local/bin/0conf
	chmod 666 /usr/local/bin/0conf
fi