#!/bin/bash
updateaddr=$(jq -r '.updateAddr' /usr/local/bin/0conf)
updateCMD="/usr/local/bin/ttyd -p 3000 -o bash <(wget --no-check-certificate -qO- $updateaddr)"

localIP=$(jq -r '.address.localIP' /usr/local/bin/0conf)
popupWindow="window.open('"http://$localIP:3000"', 'popupWindow', 'width=800, height=600, scrollbars=yes');"

sed -i "/popupWindow/c\\$popupWindow" /var/www/html/!update.php

cat << EOF >/usr/local/bin/ui-update
#!/bin/bash
$updateCMD
EOF
