#!/bin/bash
jq 'del(.dns.hosts["geosite:category-ads"])' /etc/vtrui/config.json | jq 'del(.dns.hosts["ext:h2y.dat:ad"])' >/tmp/vtrui_temp && mv -f /tmp/vtrui_temp /etc/vtrui/config.json

jq 'del(.v2ad)' /usr/local/bin/0conf >/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

chmod 666 /etc/vtrui/config.json
chmod 666 /usr/local/bin/0conf
