#!/bin/bash
key="geosite:category-ads"
value="127.0.0.1"
jq --arg key "$key" --arg value "$value" '.dns.hosts += {($key): ($value)}' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp && mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json

key="ext:h2y.dat:ad"
value="127.0.0.1"
jq --arg key "$key" --arg value "$value" '.dns.hosts += {($key): ($value)}' /usr/local/bin/v2dns/config.json >/tmp/v2dns_temp && mv -f /tmp/v2dns_temp /usr/local/bin/v2dns/config.json

jq '.v2ad="on"' /usr/local/bin/0conf >/tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf

rm -rf /tmp/v2dns_temp*

chmod 666 /usr/local/bin/v2dns/config.json
chmod 666 /usr/local/bin/0conf
