#!/bin/bash
ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1 | awk 'NR==1{print}')

WGaddress=$(jq -r '.wireguard.WGdomain' /opt/de_GWD/0conf)
WGaddressport=$(jq -r '.wireguard.WGport' /opt/de_GWD/0conf)

cat > /etc/wireguard/wg0.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.sprivatekey' /opt/de_GWD/0conf)
Address = 172.16.66.1/32
ListenPort = $WGaddressport
DNS = 127.0.0.1
MTU = 1420
PostUp   = iptables -I FORWARD -i wg0 -j ACCEPT; iptables -I FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -s 172.16.66.0/24 -o $ethernetnum -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -s 172.16.66.0/24 -o $ethernetnum -j MASQUERADE

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey1' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.11/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey2' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.12/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey3' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.13/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey4' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.14/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey5' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.15/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey6' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.16/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey7' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.17/32

[Peer]
PublicKey = $(jq -r '.wireguard.cpublickey8' /opt/de_GWD/0conf)
AllowedIPs = 172.16.66.18/32
EOF
chmod 600 /etc/wireguard/wg0.conf


cat > /etc/wireguard/client1.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey1' /opt/de_GWD/0conf)
Address = 172.16.66.11/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client2.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey2' /opt/de_GWD/0conf)
Address = 172.16.66.12/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client3.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey3' /opt/de_GWD/0conf)
Address = 172.16.66.13/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client4.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey4' /opt/de_GWD/0conf)
Address = 172.16.66.14/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client5.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey5' /opt/de_GWD/0conf)
Address = 172.16.66.15/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client6.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey6' /opt/de_GWD/0conf)
Address = 172.16.66.16/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client7.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey7' /opt/de_GWD/0conf)
Address = 172.16.66.17/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF

cat > /etc/wireguard/client8.conf << EOF
[Interface]
PrivateKey = $(jq -r '.wireguard.cprivatekey8' /opt/de_GWD/0conf)
Address = 172.16.66.18/32
DNS = 172.16.66.1
MTU = 1420

[Peer]
PublicKey = $(jq -r '.wireguard.spublickey' /opt/de_GWD/0conf)
Endpoint = $WGaddress:$WGaddressport
AllowedIPs = 0.0.0.0/0
EOF
chmod 600 /etc/wireguard/client*.conf

systemctl enable wg-quick@wg0
systemctl restart wg-quick@wg0
