#!/bin/bash
systemctl stop wg-quick@wg0

cd /etc/wireguard

wg genkey | tee sprivatekey | wg pubkey > spublickey
wg genkey | tee cprivatekey1 | wg pubkey > cpublickey1
wg genkey | tee cprivatekey2 | wg pubkey > cpublickey2
wg genkey | tee cprivatekey3 | wg pubkey > cpublickey3
wg genkey | tee cprivatekey4 | wg pubkey > cpublickey4
wg genkey | tee cprivatekey5 | wg pubkey > cpublickey5
wg genkey | tee cprivatekey6 | wg pubkey > cpublickey6
wg genkey | tee cprivatekey7 | wg pubkey > cpublickey7
wg genkey | tee cprivatekey8 | wg pubkey > cpublickey8

sprivatekey=$(cat /etc/wireguard/sprivatekey)
spublickey=$(cat /etc/wireguard/spublickey)
cprivatekey1=$(cat /etc/wireguard/cprivatekey1)
cprivatekey2=$(cat /etc/wireguard/cprivatekey2)
cprivatekey3=$(cat /etc/wireguard/cprivatekey3)
cprivatekey4=$(cat /etc/wireguard/cprivatekey4)
cprivatekey5=$(cat /etc/wireguard/cprivatekey5)
cprivatekey6=$(cat /etc/wireguard/cprivatekey6)
cprivatekey7=$(cat /etc/wireguard/cprivatekey7)
cprivatekey8=$(cat /etc/wireguard/cprivatekey8)
cpublickey1=$(cat /etc/wireguard/cpublickey1)
cpublickey2=$(cat /etc/wireguard/cpublickey2)
cpublickey3=$(cat /etc/wireguard/cpublickey3)
cpublickey4=$(cat /etc/wireguard/cpublickey4)
cpublickey5=$(cat /etc/wireguard/cpublickey5)
cpublickey6=$(cat /etc/wireguard/cpublickey6)
cpublickey7=$(cat /etc/wireguard/cpublickey7)
cpublickey8=$(cat /etc/wireguard/cpublickey8)

jq --arg sprivatekey "$sprivatekey" '.wireguard.sprivatekey=$sprivatekey' /usr/local/bin/0conf |\
jq --arg spublickey "$spublickey" '.wireguard.spublickey=$spublickey' |\
jq --arg cprivatekey1 "$cprivatekey1" '.wireguard.cprivatekey1=$cprivatekey1' |\
jq --arg cprivatekey2 "$cprivatekey2" '.wireguard.cprivatekey2=$cprivatekey2' |\
jq --arg cprivatekey3 "$cprivatekey3" '.wireguard.cprivatekey3=$cprivatekey3' |\
jq --arg cprivatekey4 "$cprivatekey4" '.wireguard.cprivatekey4=$cprivatekey4' |\
jq --arg cprivatekey5 "$cprivatekey5" '.wireguard.cprivatekey5=$cprivatekey5' |\
jq --arg cprivatekey6 "$cprivatekey6" '.wireguard.cprivatekey6=$cprivatekey6' |\
jq --arg cprivatekey7 "$cprivatekey7" '.wireguard.cprivatekey7=$cprivatekey7' |\
jq --arg cprivatekey8 "$cprivatekey8" '.wireguard.cprivatekey8=$cprivatekey8' |\
jq --arg cpublickey1 "$cpublickey1" '.wireguard.cpublickey1=$cpublickey1' |\
jq --arg cpublickey2 "$cpublickey2" '.wireguard.cpublickey2=$cpublickey2' |\
jq --arg cpublickey3 "$cpublickey3" '.wireguard.cpublickey3=$cpublickey3' |\
jq --arg cpublickey4 "$cpublickey4" '.wireguard.cpublickey4=$cpublickey4' |\
jq --arg cpublickey5 "$cpublickey5" '.wireguard.cpublickey5=$cpublickey5' |\
jq --arg cpublickey6 "$cpublickey6" '.wireguard.cpublickey6=$cpublickey6' |\
jq --arg cpublickey7 "$cpublickey7" '.wireguard.cpublickey7=$cpublickey7' |\
jq --arg cpublickey8 "$cpublickey8" '.wireguard.cpublickey8=$cpublickey8' > /tmp/0conf_temp && mv -f /tmp/0conf_temp /usr/local/bin/0conf
chmod 666 /usr/local/bin/0conf

rm -rf /etc/wireguard/*key*
cd ~
