#!/bin/bash
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
statusUpdated=$(green "[  updated  ]")

/opt/de_GWD/ui-saveSmartDNS

/opt/de_GWD/ui-saveNode

if [[ $(jq -r '.dns.DNSsplit' /opt/de_GWD/0conf) = "chnw" ]]; then
  /opt/de_GWD/ui-dnsCHNW >/dev/null 2>&1
elif [[ $(jq -r '.dns.DNSsplit' /opt/de_GWD/0conf) = "gfw" ]]; then
  /opt/de_GWD/ui-dnsGFW >/dev/null 2>&1
fi

echo "$statusUpdated DNS"