#!/bin/bash
if [[ $(jq -r '.dns.DNSsplit' /usr/local/bin/0conf) = "gfw" ]]; then
  output=`/usr/local/bin/ui-changeNLgfw`
else
  output=`/usr/local/bin/ui-changeNLchnw`
fi

ipset -F v2node
for IPv2node in $(cat /usr/local/bin/IPv2node); do
  ipset add v2node $IPv2node
done



/usr/local/bin/ui-saveListBW

if [[ -n $(cat /usr/local/bin/IPlistB) ]]; then
  ipset -F listB
  for iplistB in $(cat /usr/local/bin/IPlistB); do
    ipset add listB $iplistB
  done
fi

if [[ -n $(cat /usr/local/bin/IPlistW) ]]; then
  ipset -F listW
  for iplistW in $(cat /usr/local/bin/IPlistW); do
    ipset add listW $iplistW
  done
fi
