#!/bin/bash
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
statusInstalled=$(green "[ installed ]")

date -s "$(wget -qSO- --max-redirect=0 baidu.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
hwclock -w

cd ~
wget --no-check-certificate -c --tries=10 https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat
if [[ $(ls -l ~/geosite.dat | awk '{print$5}') -gt 240000 ]]; then
mv -f ~/geosite.dat /opt/de_GWD/v2dns/geosite.dat
fi

wget --no-check-certificate -c --tries=10 https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geoip.dat
if [[ $(ls -l ~/geoip.dat | awk '{print$5}') -gt 240000 ]]; then
cp -f ~/geoip.dat /opt/de_GWD/v2dns/geoip.dat
cp -f ~/geoip.dat /opt/de_GWD/vtrui/geoip.dat
rm -rf ~/geoip.dat
fi

curl -fkSL --retry 10 -m 1800 https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt > /opt/de_GWD/IPchnroute
if [[ $(ls -l /opt/de_GWD/IPchnroute | awk '{print$5}') -gt 80000 ]]; then
cp -f /opt/de_GWD/IPchnroute /opt/de_GWD/chnrouteSET
sed -i 's/^/add chnroute &/g' /opt/de_GWD/chnrouteSET
sed -i '1i\create chnroute hash:net family inet hashsize 2048 maxelem 65535' /opt/de_GWD/chnrouteSET

ipset -F chnroute >/dev/null 2>&1
for IPchnroute in $(cat /opt/de_GWD/IPchnroute); do
  ipset add chnroute $IPchnroute
done
fi

echo "$statusInstalled IP & Domain rules"