#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'
architecture=$(dpkg --print-architecture)
export DEBIAN_FRONTEND=noninteractive
cat << EOF >/etc/apt/apt.conf.d/01InstallLess
APT::Get::Assume-Yes "true";
APT::Install-Recommends "false";
APT::Install-Suggests "false";
EOF
cat << EOF >/etc/apt/apt.conf.d/71debconf
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
EOF



apt-key del 2FB2CD80 >/dev/null 2>&1
apt-key del 33F8024D >/dev/null 2>&1
apt-key del E734E623 >/dev/null 2>&1
rm -rf /etc/apt/trusted.gpg.d/liquorix-keyring.gpg
rm -rf /usr/share/keyrings/xanmod-kernel-archive-keyring.gpg
rm -rf /etc/apt/sources.list.d/liquorix.list
rm -rf /etc/apt/sources.list.d/xanmod-kernel.list



[[ -n $(dpkg -l | awk '{print$2}' | grep '^os-prober') ]] && apt remove --purge os-prober

unset aptPKG
[[ -z $(dpkg -l | awk '{print$2}' | grep '^gnupg2$') ]] && aptPKG+=(gnupg2)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^curl$') ]] && aptPKG+=(curl)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^python3$') ]] && aptPKG+=(python3)
[[ -z $(which 'update-grub') ]] && [[ -d "/sys/firmware/efi" ]] && aptPKG+=(grub-efi)
[[ -z $(which 'update-grub') ]] && [[ ! -d "/sys/firmware/efi" ]] && aptPKG+=(grub2-common)
[[ -n $aptPKG ]] && apt update && apt install -y $(echo ${aptPKG[@]})
mkdir -p /boot/grub
rm -f /var/cache/apt/archives/lock
rm -f /var/lib/apt/lists/lock
rm -f /var/lib/dpkg/lock
rm -f /var/lib/dpkg/lock-frontend
dpkg --configure -a



mkdir -p /opt/de_GWD
cat << "EOF" >/etc/rc_kernel.local
#!/bin/bash
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

sed -i '/net.ipv4.tcp_congestion_control/d' /etc/sysctl.conf
sed -i "/net.core.default_qdisc/d" /etc/sysctl.conf
echo "net.ipv4.tcp_congestion_control = bbr" >>/etc/sysctl.conf
echo "net.core.default_qdisc = cake" >>/etc/sysctl.conf
sysctl -p >/dev/null 2>&1

rm -f /var/cache/apt/archives/lock
rm -f /var/lib/apt/lists/lock
rm -f /var/lib/dpkg/lock
rm -f /var/lib/dpkg/lock-frontend
dpkg --configure -a

dpkg --list | grep linux-image | awk '{print $2}' | grep -Fv $(uname -r) | while read line; do
apt autoremove --purge -y $line
done

dpkg --list | grep linux-headers | awk '{print $2}' | grep -Fv $(uname -r) | while read line; do
apt autoremove --purge -y $line
done
EOF
chmod +x /etc/rc_kernel.local

crontab -l 2>/dev/null >/tmp/now.cron
sed -i '/\/opt\/de_GWD\/clearKernel/d' /tmp/now.cron
sed -i '/\/etc\/rc_kernel.local/d' /tmp/now.cron
echo '@reboot sleep 15 && /etc/rc_kernel.local' >>/tmp/now.cron
crontab /tmp/now.cron
rm -rf /tmp/now.cron




cleanOldKernels() {
  local kernel_type=$1
  
if [[ $kernel_type == "zabbly" ]]; then
  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /etc/apt/keyrings/xanmod.gpg
  rm -rf /etc/apt/sources.list.d/liquorix-kernel.list
  rm -rf /etc/apt/keyrings/liquorix.gpg
elif [[ $kernel_type == "xanmod" ]]; then
  rm -rf /etc/apt/sources.list.d/zabbly-kernel.list
  rm -rf /etc/apt/keyrings/zabbly.gpg
  rm -rf /etc/apt/sources.list.d/liquorix-kernel.list
  rm -rf /etc/apt/keyrings/liquorix.gpg
elif [[ $kernel_type == "liquorix" ]]; then
  rm -rf /etc/apt/sources.list.d/zabbly-kernel.list
  rm -rf /etc/apt/keyrings/zabbly.gpg
  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /etc/apt/keyrings/xanmod.gpg
fi
  
  dpkg --list | awk '{print $2}' | grep 'linux-image' | sed "/$kernel_type/d" | while read line; do
    apt autoremove --purge -y $line
  done

  dpkg --list | awk '{print $2}' | grep 'linux-headers' | sed "/$kernel_type/d" | while read line; do
    apt autoremove --purge -y $line
  done
  
  apt autoremove --purge -y && apt clean -y && apt autoclean -y
  
  update-initramfs -u -k all
  update-grub
}



installZabbly(){
echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Zabbly kernel${cRES}\r\c"
if [[ $architecture != "amd64" ]]; then
  echo -e "${RED}only work on x86_64${cRES}"
elif [[ $architecture == "amd64" ]]; then
curl -fsSLo /tmp/zabbly.gpg.key https://pkgs.zabbly.com/key.asc
cat /tmp/zabbly.gpg.key | gpg --dearmor >/etc/apt/keyrings/zabbly.gpg
echo "deb [signed-by=/etc/apt/keyrings/zabbly.gpg] http://pkgs.zabbly.com/kernel/stable $(cat /etc/os-release | grep VERSION= | cut -d'(' -f2 | cut -d')' -f1) main" >/etc/apt/sources.list.d/zabbly-kernel.list

apt update && apt install linux-zabbly

if [[ -n $(dpkg --list | grep linux-image | grep zabbly) ]]; then
  cleanOldKernels "zabbly"

  echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Zabbly kernel${cRES}"
  reboot
  exit
else
  echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Zabbly kernel ${RED}Install Failed${cRES}"

  dpkg --list | awk '{print $2}' | grep zabbly | while read line; do
  apt autoremove --purge $line
  done

  rm -rf /etc/apt/sources.list.d/zabbly-kernel.list
  rm -rf /etc/apt/keyrings/zabbly.gpg
  echo -e "${WHITE}[ ${YELLOW}! ${WHITE}]\c" && echo -e "\t${YELLOW}Clear up & Exit${cRES}"
  exit
fi
fi
}



installXanMod(){
echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}XanMod kernel${cRES}\r\c"
if [[ $architecture != "amd64" ]]; then
  echo -e "${RED}only work on x86_64${cRES}"
elif [[ $architecture == "amd64" ]]; then
curl -fsSLo /tmp/xanmod.gpg.key https://dl.xanmod.org/archive.key
cat /tmp/xanmod.gpg.key | gpg --dearmor >/etc/apt/keyrings/xanmod.gpg
echo "deb [signed-by=/etc/apt/keyrings/xanmod.gpg] http://deb.xanmod.org releases main" >/etc/apt/sources.list.d/xanmod-kernel.list

apt update && apt install linux-xanmod-edge-x64v3

if [[ -n $(dpkg --list | grep linux-image | grep xanmod) ]]; then
  # 清理旧内核
  cleanOldKernels "xanmod"

  echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}XanMod kernel${cRES}"
  reboot
  exit
else
  echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}XanMod kernel ${RED}Install Failed${cRES}"

  dpkg --list | awk '{print $2}' | grep xanmod | while read line; do
  apt autoremove --purge $line
  done

  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /etc/apt/keyrings/xanmod.gpg
  echo -e "${WHITE}[ ${YELLOW}! ${WHITE}]\c" && echo -e "\t${YELLOW}Clear up & Exit${cRES}"
  exit
fi
fi
}



installLiquorix(){
echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Liquorix kernel${cRES}\r\c"
if [[ $architecture != "amd64" ]]; then
  echo -e "${RED}only work on x86_64${cRES}"
elif [[ $architecture == "amd64" ]]; then
curl -fsSLo /tmp/liquorix.gpg.key https://liquorix.net/liquorix-keyring.gpg
cat /tmp/liquorix.gpg.key | gpg --dearmor >/etc/apt/keyrings/liquorix.gpg
echo "deb [signed-by=/etc/apt/keyrings/liquorix.gpg] http://liquorix.net/debian $(cat /etc/os-release | grep VERSION= | cut -d'(' -f2 | cut -d')' -f1) main" >/etc/apt/sources.list.d/liquorix-kernel.list

apt update && apt install linux-image-liquorix-amd64 linux-headers-liquorix-amd64

if [[ -n $(dpkg --list | grep linux-image | grep liquorix) ]]; then
  cleanOldKernels "liquorix"

  echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Liquorix kernel${cRES}"
  reboot
  exit
else
  echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Liquorix kernel ${RED}Install Failed${cRES}"

  dpkg --list | awk '{print $2}' | grep liquorix | while read line; do
  apt autoremove --purge $line
  done

  rm -rf /etc/apt/sources.list.d/liquorix-kernel.list
  rm -rf /etc/apt/keyrings/liquorix.gpg
  echo -e "${WHITE}[ ${YELLOW}! ${WHITE}]\c" && echo -e "\t${YELLOW}Clear up & Exit${cRES}"
  exit
fi
fi
}



echo -e "${GREEN}======================================== ${cRES}"
echo -e "${GREEN}[1]: Install Zabbly kernel and reboot ${cRES}"
echo -e "${GREEN}[2]: Install XanMod kernel and reboot ${cRES}"
echo -e "${GREEN}[3]: Install Liquorix kernel and reboot ${cRES}"
echo -e "${GREEN}======================================== ${cRES}"
read -s -n 1 kernelSwitch

case $kernelSwitch in
  "1")
      installZabbly
    ;;
  "2")
      installXanMod
    ;;
  "3")
      installLiquorix
esac