#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'
architecture=$(dpkg --print-architecture)



installBBRplus(){
mkdir -p /boot/grub
[[ -z $(which 'jq') ]] && apt install jq
[[ -z $(which 'update-grub') ]] && [[ -d "/sys/firmware/efi" ]] && apt install -y grub-efi && grub-mkconfig -o /boot/grub/grub.cfg
[[ -z $(which 'update-grub') ]] && [[ ! -d "/sys/firmware/efi" ]] && apt install -y grub2-common && grub-mkconfig -o /boot/grub/grub.cfg

rm -rf /tmp/linux-image*
rm -rf /tmp/linux-headers*

curl -sSL https://api.github.com/repos/UJX6N/bbrplus-5.16/releases/latest | jq -r '.assets[].browser_download_url | select(contains(. | "/Debian"))' | while read line
do
[[ $line =~ "linux-headers" ]] && [[ $line =~ $architecture ]] && bbrplusPath="/tmp/linux-headers.deb"
[[ $line =~ "linux-image" ]] && [[ $line =~ $architecture ]] && bbrplusPath="/tmp/linux-image.deb"

wget --show-progress -cqO $bbrplusPath $line
done

dpkg -i /tmp/linux-image.deb
[[ $? -ne 0 ]] && echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}BBRplus linux-image.deb ${RED}Install Failed${cRES}" && exit
dpkg -i /tmp/linux-headers.deb
[[ $? -ne 0 ]] && echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}BBRplus linux-headers.deb ${RED}Install Failed${cRES}" && exit

if [[ -n $(dpkg --list | grep 'linux-image' | grep 'bbrplus') ]]; then
dpkg --list | awk '{print $2}' | grep 'liquorix' | grep 'linux-' | while read line
do
apt -y purge $line
done
  apt-key del 2FB2CD80 >/dev/null 2>&1
  apt-key del 33F8024D >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/liquorix.list
  rm -rf /etc/apt/trusted.gpg.d/liquorix-keyring.gpg
  
dpkg --list | awk '{print $2}' | grep 'xanmod' | grep 'linux-' | while read line
do
apt -y purge $line
done
  apt-key del E734E623 >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /usr/share/keyrings/xanmod-kernel-archive-keyring.gpg

dpkg --list | awk '{print $2}' | grep 'linux-image' | sed "/$BBRPLUS_Ver-bbrplus/d" | while read line
do
apt -y purge $line
done

dpkg --list | awk '{print $2}' | grep 'linux-headers' | sed "/$BBRPLUS_Ver-bbrplus/d" | while read line
do
apt -y purge $line
done
apt --purge autoremove -y && apt clean -y && apt autoclean -y

update-initramfs -u -k all
update-grub

if [[ ! -f "/opt/de_GWD/clearKernel" ]]; then
clearKernel

crontab -l 2>/dev/null >/tmp/now.cron
sed -i '/\/opt\/de_GWD\/clearKernel/d' /tmp/now.cron
echo '@reboot /opt/de_GWD/clearKernel' >>/tmp/now.cron
crontab /tmp/now.cron
rm -rf /tmp/now.cron
fi

echo -e "\r\c" && echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}BBRplus kernel${cRES}"
reboot
exit
else
  echo -e "\r\c" && echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}bbrplus kernel ${RED}Install Failed${cRES}"
  exit
fi
}



installLiquorix(){
if [[ $architecture != "amd64" ]]; then
  echo -e "${RED}only work on x86_64${cRES}"
elif [[ $architecture == "amd64" ]]; then
mkdir -p /boot/grub
[[ -z $(which 'update-grub') ]] && [[ -d "/sys/firmware/efi" ]] && apt update && apt install -y grub-efi && grub-mkconfig -o /boot/grub/grub.cfg
[[ -z $(which 'update-grub') ]] && [[ ! -d "/sys/firmware/efi" ]] && apt update && apt install -y grub2-common && grub-mkconfig -o /boot/grub/grub.cfg

mkdir -p /etc/apt/{sources.list.d,trusted.gpg.d}
curl -sSLo /etc/apt/trusted.gpg.d/liquorix-keyring.gpg https://liquorix.net/liquorix-keyring.gpg
echo "deb http://liquorix.net/debian $(cat /etc/os-release | grep VERSION= | cut -d'(' -f2 | cut -d')' -f1) main" >/etc/apt/sources.list.d/liquorix.list

apt update && apt install -y linux-image-liquorix-amd64 linux-headers-liquorix-amd64

if [[ -n $(dpkg --list | grep linux-image | grep liquorix) ]]; then
  apt-key del E734E623 >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /usr/share/keyrings/xanmod-kernel-archive-keyring.gpg
dpkg --list | awk '{print $2}' | grep 'linux-image' | sed '/liquorix/d' | while read line
do
apt -y purge $line
done

dpkg --list | awk '{print $2}' | grep 'linux-headers' | sed '/liquorix/d' | while read line
do
apt -y purge $line
done
apt --purge autoremove -y && apt clean -y && apt autoclean -y

update-initramfs -u -k all
update-grub

if [[ ! -f "/opt/de_GWD/clearKernel" ]]; then
clearKernel

crontab -l 2>/dev/null >/tmp/now.cron
sed -i '/\/opt\/de_GWD\/clearKernel/d' /tmp/now.cron
echo '@reboot /opt/de_GWD/clearKernel' >>/tmp/now.cron
crontab /tmp/now.cron
rm -rf /tmp/now.cron
fi

echo -e "\r\c" && echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Liquorix kernel${cRES}"
reboot
exit
else
  echo -e "\r\c" && echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}Liquorix kernel ${RED}Install Failed${cRES}"

  dpkg --list | awk '{print $2}' | grep liquorix | while read line
  do
  apt -y purge $line
  done

  apt-key del 2FB2CD80 >/dev/null 2>&1
  apt-key del 33F8024D >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/liquorix.list
  rm -rf /etc/apt/trusted.gpg.d/liquorix-keyring.gpg
  echo -e "\r\c" && echo -e "${WHITE}[ ${YELLOW}! ${WHITE}]\c" && echo -e "\t${YELLOW}Clear up & Exit${cRES}"
  exit
fi
fi
}



installXanMod(){
if [[ $architecture != "amd64" ]]; then
  echo -e "${RED}only work on x86_64${cRES}"
elif [[ $architecture == "amd64" ]]; then
mkdir -p /boot/grub
[[ -z $(which 'update-grub') ]] && [[ -d "/sys/firmware/efi" ]] && apt update && apt install -y grub-efi && grub-mkconfig -o /boot/grub/grub.cfg
[[ -z $(which 'update-grub') ]] && [[ ! -d "/sys/firmware/efi" ]] && apt update && apt install -y grub2-common && grub-mkconfig -o /boot/grub/grub.cfg

mkdir -p /etc/apt/{sources.list.d,trusted.gpg.d}
curl -sSLo- https://dl.xanmod.org/gpg.key | gpg --dearmor >/usr/share/keyrings/xanmod-kernel-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/xanmod-kernel-archive-keyring.gpg] http://deb.xanmod.org releases main" >/etc/apt/sources.list.d/xanmod-kernel.list

apt update && apt install linux-xanmod-lts -y

if [[ -n $(dpkg --list | grep linux-image | grep xanmod) ]]; then
  apt-key del 2FB2CD80 >/dev/null 2>&1
  apt-key del 33F8024D >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/liquorix.list
  rm -rf /etc/apt/trusted.gpg.d/liquorix-keyring.gpg

dpkg --list | awk '{print $2}' | grep 'linux-image' | sed '/xanmod/d' | while read line
do
apt -y purge $line
done

dpkg --list | awk '{print $2}' | grep 'linux-headers' | sed '/xanmod/d' | while read line
do
apt -y purge $line
done
apt --purge autoremove -y && apt clean -y && apt autoclean -y

update-initramfs -u -k all
update-grub

if [[ ! -f "/opt/de_GWD/clearKernel" ]]; then
clearKernel

crontab -l 2>/dev/null >/tmp/now.cron
sed -i '/\/opt\/de_GWD\/clearKernel/d' /tmp/now.cron
echo '@reboot /opt/de_GWD/clearKernel' >>/tmp/now.cron
crontab /tmp/now.cron
rm -rf /tmp/now.cron
fi

echo -e "\r\c" && echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}XanMod kernel${cRES}"
reboot
exit
else
  echo -e "\r\c" && echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}XanMod kernel ${RED}Install Failed${cRES}"

  dpkg --list | awk '{print $2}' | grep xanmod | while read line
  do
  apt -y purge $line
  done

  apt-key del E734E623 >/dev/null 2>&1
  rm -rf /etc/apt/sources.list.d/xanmod-kernel.list
  rm -rf /usr/share/keyrings/xanmod-kernel-archive-keyring.gpg
  echo -e "\r\c" && echo -e "${WHITE}[ ${YELLOW}! ${WHITE}]\c" && echo -e "\t${YELLOW}Clear up & Exit${cRES}"
  exit
fi
fi
}



    echo -e "${GREEN}======================================== ${cRES}"
    echo -e "${GREEN}[1]: Install BBRplus kernel and reboot${cRES}"
    echo -e "${GREEN}[2]: Install Liquorix kernel and reboot${cRES}"
    echo -e "${GREEN}[3]: Install XanMod kernel and reboot${cRES}"
    echo -e "${GREEN}======================================== ${cRES}"
    read -s -n 1 kernelSwitch
    echo -e "\r\c" && echo -e "${WHITE}[...${WHITE}]\c" && echo -e "\t${WHITE}Installing new Kernel${cRES}"

case $kernelSwitch in
  "1")
    installBBRplus
    ;;
  "2")
    installLiquorix
    ;;
  "3")
    installXanMod
    ;;
esac