#!/bin/bash
clear
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }


installDOHser(){
cd ~
wget -O ~/doh.zip https://raw.githubusercontent.com/jacyl4/de_GWD/master/resource/dohamd64.zip
unzip doh.zip
mv -f ~/doh/doh-server /usr/local/bin/doh-server
chmod +x /usr/local/bin/doh-server
rm -rf ~/doh*

mkdir -p /etc/dns-over-https
cat > /etc/dns-over-https/doh-server.conf << EOF
listen = [ "127.0.0.1:8053" ]
path = "/dq"

upstream = [ "udp:127.0.0.1:5390" ]

timeout = 10
tries = 3
verbose = false
log_guessed_client_ip = false
EOF

mkdir -p /etc/NetworkManager/dispatcher.d
cat > /etc/NetworkManager/dispatcher.d/doh-server << "EOF"
#!/bin/bash
case "$2" in
    up)
        /usr/bin/systemctl is-active doh-server.service > /dev/null && /usr/bin/systemctl restart doh-server.service
        ;;
    down)
        /usr/bin/systemctl is-active doh-server.service > /dev/null && /usr/bin/systemctl restart doh-server.service
        ;;
    *)
        exit 0
        ;;
esac
EOF
chmod +x /etc/NetworkManager/dispatcher.d/doh-server

touch /run/doh-server.pid
cat > /lib/systemd/system/doh-server.service << "EOF"
[Unit]
Description=DNS-over-HTTPS server
After=network.target
Wants=network.target

[Service]
Type=simple
PIDFile=/run/doh-server.pid
AmbientCapabilities=CAP_NET_BIND_SERVICE
ExecStart=/usr/local/bin/doh-server -conf /etc/dns-over-https/doh-server.conf
Restart=always
RestartSec=2s
LimitNPROC=1000000
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable doh-server
systemctl restart doh-server
}



v2rayADD(){
read -d '' vtruiIn << EOF
	{
    "port": 11811,
    "listen": "127.0.0.1",
    "protocol": "vmess",
    "sniffing": {"enabled": true, "destOverride": ["http", "tls"]},
    "settings": {
      "clients": [{
        "id": "00000000-0000-0000-0000-000000000000",
        "level": 1,
        "alterId": 64
        }]
      },
    "streamSettings": {
      "network": "ws",
      "wsSettings": {
        "path": "/0000"
        }
      }
    }
EOF

jq --argjson vtruiIn "$vtruiIn" '.inbounds[2] = $vtruiIn' /etc/vtrui/config.json |\
jq --arg uuidnum "$clifwd_uuidnum" '.inbounds[2].settings.clients[0].id=$uuidnum' |\
jq --arg v2path "$clifwd_v2path" '.inbounds[2].streamSettings.wsSettings.path=$v2path' > /etc/vtrui/temp.json && mv -f /etc/vtrui/temp.json /etc/vtrui/config.json
}



iptablesProxyADD(){
sed -i '/dport 53 -s/d' ~/teip
sed -i '/dport 53 -i/d' ~/teip

addRule1="iptables -A INPUT -p udp --dport 53 -s 127.0.0.1,172.17.0.0/24,172.16.66.0/24 -j ACCEPT"
addRule2="iptables -A INPUT -p tcp --dport 53 -s 127.0.0.1,172.17.0.0/24,172.16.66.0/24 -j ACCEPT"

addRule3="iptables -A INPUT -p udp --dport 53 -i $ethernetnum -j DROP"
addRule4="iptables -A INPUT -p tcp --dport 53 -i $ethernetnum -j DROP"

sed -i "/iptables -t mangle -N V2PROXY/i$addRule1" ~/teip
sed -i "/iptables -t mangle -N V2PROXY/i$addRule2" ~/teip
sed -i "/iptables -t mangle -N V2PROXY/i$addRule3" ~/teip
sed -i "/iptables -t mangle -N V2PROXY/i$addRule4" ~/teip

systemctl restart iptables-proxy
}



nginxWebConfADD(){
cat > /etc/nginx/conf.d/default.conf<< EOF
server {
  listen $httpPORT;
  server_name $vpsdomain;
  return 301 https://\$server_name\$request_uri;
}

server {
  listen $httpsPORT ssl http2 spdy fastopen=64 reuseport;
  server_name $vpsdomain;
  root /var/www/html;
  index index.php index.html index.htm;

  ssl_certificate /var/www/ssl/fullchain.cer;
  ssl_certificate_key /var/www/ssl/$(echo $vpsdomain | awk -F. '{print $2"."$3}').key;
  ssl_dhparam /var/www/ssl/dhparam.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers TLS13+AESGCM+AES128:TLS13+AESGCM+AES256:TLS13+CHACHA20:EECDH+ECDSA+AESGCM+AES128:EECDH+ECDSA+CHACHA20:EECDH+ECDSA+AESGCM+AES256:EECDH+ECDSA+AES128+SHA:EECDH+ECDSA+AES256+SHA:EECDH+aRSA+AESGCM+AES128:EECDH+aRSA+CHACHA20:EECDH+aRSA+AESGCM+AES256:EECDH+aRSA+AES128+SHA:EECDH+aRSA+AES256+SHA:RSA+AES128+SHA:RSA+AES256+SHA:RSA+3DES;
  ssl_session_timeout 10m;
  ssl_session_cache shared:le_nginx_SSL:10m;
  ssl_buffer_size 1400;

  ssl_early_data on;
  proxy_set_header Early-Data \$ssl_early_data;

  ssl_stapling on;
  ssl_stapling_verify on;
  ssl_stapling_file /var/www/ssl/ocsp.resp;
  resolver 1.1.1.1 valid=600s;
  resolver_timeout 5s;

location ~* \.php$ {
  fastcgi_pass            unix:/run/php/php7.3-fpm.sock;
  fastcgi_index           index.php;
  fastcgi_split_path_info ^(.+\.php)(.*)$;
  include                 fastcgi_params;
  fastcgi_param           SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
}

location /dq {
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_pass              http://127.0.0.1:8053/dq;
}

location $v2path {
  proxy_http_version      1.1;
  proxy_set_header Host \$http_host;
  proxy_set_header Upgrade WebSocket;
  proxy_set_header Connection "upgrade";
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_read_timeout      86400;
  keepalive_requests      25600;
  keepalive_timeout       300 300;
  proxy_redirect          off;
  proxy_buffering         off;
  proxy_pass              http://127.0.0.1:11811;
}

}
EOF

mkdir -p /var/www/ssl
chown -R www-data:www-data /var/www/ssl
chmod -R 600 /var/www/ssl

docker stop nginx > /dev/null 2>&1
docker rm nginx > /dev/null 2>&1

docker run -d --name=nginx --net=host --restart=always \
-v /etc/localtime:/etc/localtime \
-v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
-v /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf \
-v /var/www/ssl/:/var/www/ssl/ \
-v /var/www/html/:/var/www/html/ \
-v /run/php/php7.3-fpm.sock:/run/php/php7.3-fpm.sock \
jacyl4/nginx_tls1.3:latest
}



postInstall(){
mkdir -p /var/www/html/gwd

svn export https://github.com/jacyl4/de_GWD/trunk/resource/ui-script
svn export https://github.com/jacyl4/de_GWD/trunk/resource/ui-web

grep ~/ui-script -rl /usr/local/bin > /tmp/binFILE
for binFILE in $(cat /tmp/binFILE); do
  sed -i 's:/var/www/html:/var/www/html/gwd:g' $binFILE
done

grep ~/ui-web -rl /var/www/html > /tmp/htmlFILE
for htmlFile in $(cat /tmp/htmlFILE); do
  sed -i 's:/var/www/html:/var/www/html/gwd:g' $htmlFile
done

rsync -Ir ~/ui-script/* /usr/local/bin
rsync -Ir ~/ui-web/* /var/www/html/gwd
rm -rf ~/ui-*

wget https://raw.githubusercontent.com/jacyl4/de_GWD/master/version.php
mv -f ~/version.php /var/www/html/gwd/version.php

chown -R www-data:www-data /var/www/html
chmod -R 755 /var/www/html
chmod +x /usr/local/bin/*

cat > /usr/local/bin/Q4am << "EOF"
#!/bin/bash
wget -c https://raw.githubusercontent.com/jacyl4/de_GWD/master/resource/dlc.dat
wget -c https://raw.githubusercontent.com/ToutyRater/V2Ray-SiteDAT/master/geofiles/h2y.dat                
curl -L 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > ~/chnroute.txt
mv -f ~/dlc.dat /usr/bin/vtrui/geosite.dat
mv -f ~/h2y.dat /usr/bin/vtrui/h2y.dat
mv -f ~/chnroute.txt /usr/local/bin/chnroute.txt

{
echo "create chnroute hash:net family inet hashsize 2048 maxelem 65535"
chnroute=`cat /usr/local/bin/chnroute.txt`
for chnroute in $chnroute ; do
 echo "add chnroute $chnroute"
done
} > /usr/local/bin/chnrouteset

ipset -F chnroute
for ipchnroute in $(cat /usr/local/bin/chnroute.txt); do
  ipset add chnroute $ipchnroute
done
EOF
chmod +x /usr/local/bin/Q4am
/usr/local/bin/Q4am

cat > /usr/local/bin/Q4H << "EOF"
#!/bin/bash
date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"
hwclock -w

rm -rf ~/clifwd*
rm -rf /var/log/*1*
rm -rf /var/log/*2*
rm -rf /var/log/*.gz
rm -rf /tmp/nodecheck*
rm -rf /var/www/html/log.log

/usr/local/bin/ui-listBWresolve > /dev/null 2>&1
EOF
chmod +x /usr/local/bin/Q4H
/usr/local/bin/Q4H

cat > ~/now.cron << EOF
0 4 * * * /usr/local/bin/Q4am
0 */4 * * * /usr/local/bin/Q4H
EOF
crontab ~/now.cron
rm -rf ~/now.cron


if [[ ! -f "/etc/wireguard/sprivatekey" ]]; then
mkdir -p /etc/wireguard
/usr/local/bin/ui-WGchangeKey >/dev/null 2>&1
fi

/usr/local/bin/ui-NodeDThide >/dev/null 2>&1
/usr/local/bin/ui-nodeResolve >/dev/null 2>&1
/usr/local/bin/ui-changeDOH >/dev/null 2>&1

sed -i "/$doh/d" /etc/hosts
}



installCliFwd(){
    green "========================="
    green " V2ray UUID"
    green "========================="
    read uuidnum

    green "========================="
    green " Path"
    green "========================="
    read v2path

    green "==========================="
    green " domain"
    green "==========================="
    read vpsdomain

    green "==========================="
    green " http port"
    green "==========================="
    read httpPORT

    green "==========================="
    green " https port"
    green "==========================="
    read httpsPORT



mv -f /var/www/html/*.txt /var/www/html/gwd
cd /var/www/html
shopt -s extglob
rm -rf !(gwd)
shopt -u extglob
cd ~


cd ~

installDOHser

v2rayADD

iptablesProxyADD

nginxWebConf

mkdir -p /var/www/ssl
chown -R www-data:www-data /var/www/ssl
chmod -R 600 /var/www/ssl

docker stop nginx > /dev/null 2>&1
docker rm nginx > /dev/null 2>&1

docker run -d --name=nginx --net=host --restart=always \
-v /etc/localtime:/etc/localtime \
-v /etc/nginx/nginx.conf:/etc/nginx/nginx.conf \
-v /etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf \
-v /var/www/ssl/:/var/www/ssl/ \
-v /var/www/html/:/var/www/html/ \
-v /run/php/php7.3-fpm.sock:/run/php/php7.3-fpm.sock \
jacyl4/nginx_tls1.3:latest

rm -rf ~/clifwd
touch "/usr/local/bin/ui-aclifwd"
}



makeSSL(){
    green "==========================="
    green " domain (no www)"
    green "==========================="
    read vpsdomain

    green "==========================="
    green " Cloudflare API KEY"
    green "==========================="
    read CFapikey

    green "==========================="
    green " Cloudflare Email"
    green "==========================="
    read CFemail

apt update && apt install --no-install-recommends --no-install-suggests -y socat

cd ~
mkdir -p /var/www/ssl
rm -rf /var/www/ssl/*

export CF_Key="$CFapikey"
export CF_Email="$CFemail"

curl https://get.acme.sh | sh
~/.acme.sh/acme.sh --issue --dns dns_cf -d $vpsdomain -d *.$vpsdomain --keylength ec-256
~/.acme.sh/acme.sh --installcert -d $vpsdomain --ecc \
               --keypath        /var/www/ssl/$vpsdomain.key  \
               --fullchain-file /var/www/ssl/fullchain.cer \
               --reloadcmd     "docker restart nginx > /dev/null 2>&1"
openssl dhparam -out /var/www/ssl/dhparam.pem 2048

cat > /var/www/ssl/update_ocsp_cache << EOF
#!/bin/bash
wget -O intermediate.pem https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
wget -O root.pem https://ssl-tools.net/certificates/dac9024f54d8f6df94935fb1732638ca6ad77c13.pem
mv intermediate.pem /var/www/ssl
mv root.pem /var/www/ssl
cat /var/www/ssl/intermediate.pem > /var/www/ssl/bundle.pem
cat /var/www/ssl/root.pem >> /var/www/ssl/bundle.pem

openssl ocsp -no_nonce \
    -issuer  /var/www/ssl/intermediate.pem \
    -cert    /var/www/ssl/fullchain.cer \
    -CAfile  /var/www/ssl/bundle.pem \
    -VAfile  /var/www/ssl/bundle.pem \
    -url     http://ocsp.int-x3.letsencrypt.org \
    -respout /var/www/ssl/ocsp.resp
EOF
chmod +x /var/www/ssl/update_ocsp_cache
/var/www/ssl/update_ocsp_cache

crontab -l > now.cron
if [[ "$(crontab -l | grep 'update_ocsp_cache' | awk '{print $6}')" != "/var/www/ssl/update_ocsp_cache" ]]; then
echo '0 0 * * 7 /var/www/ssl/update_ocsp_cache' >> now.cron
fi
crontab now.cron
rm -rf now.cron
}



clifwdUpdate(){
source /etc/profile

cd ~

checkDNS=$(/usr/local/bin/ui-checkDNS)
checkDDNScf=$(/usr/local/bin/ui-checkDDNScf)
checkWG=$(/usr/local/bin/ui-checkWG)
checkV2ad=$(/usr/local/bin/ui-checkV2ad)

piholepw=$(awk '/WEBPASSWORD/' /etc/pihole/setupVars.conf | cut -d = -f2)

domain=$(jq -r '.outbounds[0].settings.vnext[0].address' /etc/vtrui/config.json)
port=$(jq -r '.outbounds[0].settings.vnext[0].port' /etc/vtrui/config.json)
uuidnum=$(jq -r '.outbounds[0].settings.vnext[0].users[0].id' /etc/vtrui/config.json)
v2path=$(jq -r '.outbounds[0].streamSettings.wsSettings.path' /etc/vtrui/config.json)

ethernetnum=$(ip --oneline link show up | grep -v "lo" | awk '{print $2}' | cut -d':' -f1 | cut -d'@' -f1 | awk 'NR==1{print}')
localaddr=$(ip a | grep "$ethernetnum" | awk '{print $2}' | awk 'END {print}' | cut -d'/' -f1)

clifwd_uuidnum=$(jq -r '.inbounds[2].settings.clients[0].id' /etc/vtrui/config.json)
clifwd_v2path=$(jq -r '.inbounds[2].streamSettings.wsSettings.path' /etc/vtrui/config.json)
vpsdomain=$(awk '/server_name/' /etc/nginx/conf.d/default.conf | awk 'END{print$2}' | sed 's/.$//')
httpPORT=$(awk '/listen/' /etc/nginx/conf.d/default.conf | awk 'NR==1{print$2}' | sed 's/.$//')
httpsPORT=$(awk '/listen/' /etc/nginx/conf.d/default.conf | awk 'NR==2{print$2}')

wget -O ~/clifwd https://raw.githubusercontent.com/jacyl4/de_GWD/master/client_do

cp -f ~/clifwd ~/clifwd_preInstall
sed -i '$d' ~/clifwd_preInstall
echo "preInstall" >>  ~/clifwd_preInstall

cp -f ~/clifwd ~/clifwd_installDOH
sed -i '$d' ~/clifwd_installDOH
echo "installDOH" >>  ~/clifwd_installDOH

cp -f ~/clifwd ~/clifwd_installV2ray
sed -i '$d' ~/clifwd_installV2ray
echo "installV2ray" >>  ~/clifwd_installV2ray

cp -f ~/clifwd ~/clifwd_installIptablesProxy
sed -i '$d' ~/clifwd_installIptablesProxy
echo "installIptablesProxy" >>  ~/clifwd_installIptablesProxy

cp -f ~/clifwd ~/clifwd_installWG
sed -i '$d' ~/clifwd_installWG
echo "installWG" >>  ~/clifwd_installWG

cp -f ~/clifwd ~/clifwd_dockerNginx
sed -i '$d' ~/clifwd_dockerNginx
echo "dockerNginx" >>  ~/clifwd_dockerNginx

cp -f ~/clifwd ~/clifwd_installPihole
sed -i '$d' ~/clifwd_installPihole
echo "installPihole" >>  ~/clifwd_installPihole

cp -f ~/clifwd ~/clifwd_postInstall
sed -i '$d' ~/clifwd_postInstall
echo "postInstall" >>  ~/clifwd_postInstall

chmod +x ~/clifwd*

~/clifwd_preInstall

~/clifwd_installDOH

~/clifwd_installV2ray

~/clifwd_installIptablesProxy

iptablesProxyADD

~/clifwd_installWG

~/clifwd_dockerNginx

~/clifwd_installPihole

v2rayADD

installDOHser

nginxWebConfADD

~/clifwd_postInstall

if [[ $checkDNS = "GFWlist" ]]; then
/usr/local/bin/ui-changeNLgfw
else
/usr/local/bin/ui-changeNLchnw
fi

if [[ $checkDDNScf = "on" ]]; then
/usr/local/bin/ui-ddnsUpdateOnCF
fi

if [[ $checkWG = "on" ]]; then
/usr/local/bin/ui-WGon
fi

if [[ $checkV2ad = "on" ]]; then
/usr/local/bin/ui-v2adADD
fi

if [[ -f "/usr/local/bin/ui-amarked" ]]; then
/usr/local/bin/ui-markThis
fi

echo "" > /usr/local/bin/ui-aclifwd
}


start_menu(){

    green  "1. de_GWD clifwd install"
    green  "2. make SSL"
    yellow "0. de_GWD clifwd Update"
    red    "CTRL+C EXIT"
    echo
    read -p "Select:" num
    case "$num" in
    1)
    installCliFwd
    start_menu
    ;;
    2)
    makeSSL
    start_menu
    ;;
    0)
    clifwdUpdate
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu