#!/bin/bash
sed -i "/net.ipv4.ip_forward =/c\net.ipv4.ip_forward = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.all.rp_filter =/c\net.ipv4.conf.all.rp_filter = 0" /etc/sysctl.conf
sed -i "/net.ipv4.conf.default.rp_filter =/c\net.ipv4.conf.default.rp_filter = 0" /etc/sysctl.conf
sed -i "/net.ipv4.conf.all.send_redirects =/c\net.ipv4.conf.all.send_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.default.send_redirects =/c\net.ipv4.conf.default.send_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.all.accept_redirects =/c\net.ipv4.conf.all.accept_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.default.accept_redirects =/c\net.ipv4.conf.default.accept_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.all.secure_redirects =/c\net.ipv4.conf.all.secure_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.default.secure_redirects =/c\net.ipv4.conf.default.secure_redirects = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.all.accept_source_route =/c\net.ipv4.conf.all.accept_source_route = 1" /etc/sysctl.conf
sed -i "/net.ipv4.conf.default.accept_source_route =/c\net.ipv4.conf.default.accept_source_route = 1" /etc/sysctl.conf
sysctl -p >/dev/null
systemctl restart systemd-sysctl

sed -i '/--dport 53 -i/d' /opt/de_GWD/iptables-proxy-up
sed -i '/--dport 53 -i/d' /opt/de_GWD/ui-onUDP
sed -i '/--dport 53 -i/d' /opt/de_GWD/ui-offUDP
systemctl restart iptables-proxy
