#!/bin/bash
address=$(jq -r --argjson domainNUM "$1" '.v2node | to_entries[] | select(.key == $domainNUM) | .value.domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')
tls=$(jq -r --argjson domainNUM "$1" '.v2node | to_entries[] | select(.key == $domainNUM) | .value.tls' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')
uuid=$(jq -r --argjson domainNUM "$1" '.v2node | to_entries[] | select(.key == $domainNUM) | .value.uuid' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')
path=$(jq -r --argjson domainNUM "$1" '.v2node | to_entries[] | select(.key == $domainNUM) | .value.path' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')

domain=$(echo -e $address | cut -d: -f1)
port=$(echo -e $address | cut -d: -f2 | grep '^[[:digit:]]*$')
[[ -z $port ]] && port="443"
[[ -z $tls ]] && tls=$domain

jq --arg domain "$domain" '.v2nodeDIV.nodeDT.domain=$domain' /opt/de_GWD/0conf |\
jq --arg tls "$tls" '.v2nodeDIV.nodeDT.tls=$tls' |\
jq --arg port "$port" '.v2nodeDIV.nodeDT.port=$port' |\
jq --arg uuid "$uuid" '.v2nodeDIV.nodeDT.uuid=$uuid' |\
jq --arg path "$path" '.v2nodeDIV.nodeDT.path=$path' | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

if [[ -z $path ]]; then
OBdt=`cat << EOF
    {
      "tag": "divertTraffic",
      "protocol": "vless",
      "settings": {
        "vnext": [
          {
            "address": "$domain",
            "port": $port,
            "users": [
              {
                "id": "$uuid",
                "encryption": "none",
                "flow": "xtls-rprx-splice",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "serverName": "$tls",
          "allowInsecure": false
        },
        "sockopt": {
          "mark": 255,
          "domainStrategy": "UseIP"
        }
      }
    }
EOF
`
else
OBdt=`cat << EOF
{
      "tag": "divertTraffic",
      "protocol": "vless",
      "mux":{"enabled":true,"concurrency":1},
      "settings": {
        "vnext": [
          {
            "address": "$domain",
            "port": $port,
            "users": [
              {
                "id": "$uuid",
                "encryption": "none",
                "level": 1
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws",
        "wsSettings": {
          "path": "$path"
        },
        "security": "tls",
        "tlsSettings": {
          "serverName": "$tls",
          "allowInsecure": false
        },
        "sockopt": {
          "mark": 255,
          "domainStrategy": "UseIP"
        }
      }
}
EOF
`
fi

jq 'del(.outbounds[] | select(.tag == "divertTraffic"))' /opt/de_GWD/vtrui/config.json |\
jq --argjson OBdt "$OBdt" '.outbounds+=[$OBdt]' | sponge /opt/de_GWD/vtrui/config.json
chmod 666 /opt/de_GWD/vtrui/config.json

systemctl restart vtrui
