#!/bin/bash
sed -i '/DoGs_START/,/DoGs_END/d' /opt/de_GWD/coredns/corefile
if [[ $(ls /opt/de_GWD/coredns/corefile | wc -l) -le 10 ]]; then
systemctl disable coredns >/dev/null 2>&1
systemctl stop coredns
else
systemctl restart coredns
fi
