#!/bin/bash
jq --argjson directApple '["geosite:apple"]' 'del(.routing.rules[] | select(.domain == $directApple))' /opt/de_GWD/vtrui/config.json |\
jq --argjson directSteam '["geosite:category-games@cn"]' 'del(.routing.rules[] | select(.domain == $directSteam))' | sponge /opt/de_GWD/vtrui/config.json

DNSdirectOFF=$(jq -r '.dns.servers[3].domains - ["geosite:apple","geosite:apple-cn","domain:icloud.com","domain:icloud-content.com","geosite:category-games@cn"]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
jq --argjson DNSdirectOFF "$DNSdirectOFF" '.dns.servers[3].domains=$DNSdirectOFF' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json

if [[ $(jq -r '.v2nodeDIV.directApple' /opt/de_GWD/0conf 2>/dev/null) == "on" ]]; then
jq --arg directApple "geosite:apple" '.dns.servers[3].domains+=[$directApple]' /opt/de_GWD/v2dns/config.json |\
jq --arg directApple "geosite:apple-cn" '.dns.servers[3].domains+=[$directApple]' |\
jq --arg directApple "domain:icloud.com" '.dns.servers[3].domains+=[$directApple]' |\
jq --arg directApple "domain:icloud-content.com" '.dns.servers[3].domains+=[$directApple]' | sponge /opt/de_GWD/v2dns/config.json

tag="direct"
routingDomain='["geosite:apple"]'
/opt/de_GWD/ui-V2routingDomain $tag $routingDomain
fi

if [[ $(jq -r '.v2nodeDIV.directSteam' /opt/de_GWD/0conf 2>/dev/null) == "on" ]]; then
jq --arg directSteam "geosite:category-games@cn" '.dns.servers[3].domains+=[$directSteam]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json

tag="direct"
routingDomain='["geosite:category-games@cn"]'
/opt/de_GWD/ui-V2routingDomain $tag $routingDomain
fi

if [[ $1 == "r" ]]; then
  systemctl restart v2dns >/dev/null
  systemctl restart vtrui >/dev/null
fi
