#!/bin/bash
DoGsPort=$(jq -r '.FORWARD.DoGs.port' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')

doh1=$(jq -r '.dns.doh[0]' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')
doh2=$(jq -r '.dns.doh[1]' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')
[[ -n $doh1 ]] && doh1str="to doh://$doh1"
[[ -n $doh2 ]] && doh2str="to doh://$doh2"

if [[ -n $DoGsPort ]]; then
touch /opt/de_GWD/coredns/corefile
sed -i '/DoGs_START/,/DoGs_END/d' /opt/de_GWD/coredns/corefile
tac /opt/de_GWD/coredns/corefile | awk 'NF>0{x=1}x' | tac | sponge /opt/de_GWD/coredns/corefile >/dev/null 2>&1
cat << EOF >>/opt/de_GWD/coredns/corefile

# DoGs_START
grpc://.:$DoGsPort {
  tls /var/www/ssl/de_GWD.cer /var/www/ssl/de_GWD.key
  dnsredir . {
      $doh1str
      $doh2str
      policy round_robin
      no_ipv6
      bootstrap 127.0.0.1
  }
  template ANY AAAA {
    rcode NXDOMAIN
  }
}
# DoGs_END
EOF

systemctl enable coredns >/dev/null 2>&1
systemctl restart coredns
fi
