#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



localAddrCIDR=$(jq -r '.address.localIP' /opt/de_GWD/0conf | grep -v '^null$')
localAddr=$(echo $localAddrCIDR | cut -d / -f1)
netmask=$(echo $localAddrCIDR | sed -r 's/([0-9]{1,3}\.){3}[0-9]{1,3}//g')

[[ -z $netmask ]] && netmask="/24" && localAddrCIDR="$localAddr$netmask"
netmaskNUM=$(echo $netmask | cut -d / -f2)

dhcpStart=$(jq -r '.address.dhcpStart' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
dhcpEnd=$(jq -r '.address.dhcpEnd' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

if [[ -n $dhcpStart ]] && [[ -n $dhcpEnd ]] && [[ -n $localAddr ]]; then
sed -i '/REV_SERVER=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_CIDR=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_TARGET=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_DOMAIN=/d' /etc/pihole/setupVars.conf
cat << EOF >> /etc/pihole/setupVars.conf
REV_SERVER=false
EOF

sudo pihole -a enabledhcp "$dhcpStart" "$dhcpEnd" "$localAddr" "$netmaskNUM" "lan" >/dev/null 2>&1

/opt/de_GWD/pihole_hotfix

jq '.address.dhcp="on"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf
fi
