#!/bin/bash
/opt/de_GWD/ui-ddns3322updateIP

crontab -l 2>/dev/null >/tmp/now.cron
sed -i '/ui-ddns3322/d' /tmp/now.cron
echo '*/1 * * * * /opt/de_GWD/ui-ddns3322updateIP >/dev/null 2>&1' >>/tmp/now.cron
crontab /tmp/now.cron
rm -rf /tmp/now.cron
