#!/bin/bash
systemctl stop smartdns
>/opt/de_GWD/smartdns/smartdns.cache
systemctl restart smartdns

systemctl restart v2dns

systemctl stop pihole-FTL
rm -rf rm /etc/pihole/pihole-FTL.db
pihole restartdns
