#!/bin/bash
clear
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
cyan()   { echo -e "\033[36m\033[01m $1 \033[0m"; }
white()  { echo -e "\033[37m\033[01m $1 \033[0m"; }
statusWarning=$(yellow "[  warning  ]")



installWGcore(){
uname -r 2>&1 | grep -o '[0-9.]*' | head -n 1 >/tmp/kernelVer
echo "5.6" >>/tmp/kernelVer

if [[ $(cat /tmp/kernelVer |sort -rV | head -n 1) = "5.6" ]]; then
    echo -n "$statusWarning" && red "Update kernel first!"
else
    echo "deb http://deb.debian.org/debian/ unstable main" >/etc/apt/sources.list.d/unstable.list
    printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' >/etc/apt/preferences.d/limit-unstable
    
    unset aptPKG
    [[ -z $(dpkg -l | grep ' wireguard-tools ') ]] && aptPKG+=(wireguard-tools)
    [[ -n $aptPKG ]] && apt update && apt install $(echo ${aptPKG[@]})

    if [[ -z $(jq -r '.wireguard.server.sprivatekey' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$') ]]; then
        /opt/de_GWD/ui-WGgenSkey
    fi
fi

rm -rf /tmp/kernelVer
blue "------------------------"
blue "Install WireGuard [done]"
blue "------------------------"
}


start_menu(){
    green "==============================="
    green "         Wireguard"
    green "==============================="
    green  "1. Install Wireguard"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installWGcore
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu