#!/bin/bash
clear
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
cyan()   { echo -e "\033[36m\033[01m $1 \033[0m"; }
white()  { echo -e "\033[37m\033[01m $1 \033[0m"; }
dockerComposeVer_reserved="1.29.2"

installDocker(){
curl -sSLo- https://download.docker.com/linux/debian/gpg | gpg --dearmor >/usr/share/keyrings/docker-ce-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-ce-archive-keyring.gpg] https://download.docker.com/linux/debian $(cat /etc/os-release | grep VERSION= | cut -d'(' -f2 | cut -d')' -f1) stable" >/etc/apt/sources.list.d/docker.list

unset aptPKG
[[ -z $(dpkg -l | awk '{print$2}' | grep '^docker-ce$') ]] && aptPKG+=(docker-ce)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^docker-ce-cli$') ]] && aptPKG+=(docker-ce-cli)
[[ -z $(dpkg -l | awk '{print$2}' | grep '^containerd.io$') ]] && aptPKG+=(containerd.io)
[[ -n $aptPKG ]] && apt update && apt install $(echo ${aptPKG[@]})

if [[ -n $(dpkg -l | awk '{print$2}' | grep '^docker-ce$') ]] && [[ -n $(dpkg -l | awk '{print$2}' | grep '^containerd.io$') ]] && [[ ! -f "/etc/docker/daemon.json" ]]; then
mkdir -p /etc/docker/
systemctl stop docker containerd
cat << EOF >/etc/docker/daemon.json
{
  "iptables": false
}
EOF
systemctl restart docker
fi

dockerComposeVer=$(curl -sSL "https://api.github.com/repos/docker/compose/releases/latest" | jq -r .tag_name | grep -v '^null$')
[[ -z $dockerComposeVer_reserved ]] && dockerComposeVer=$dockerComposeVer_reserved

curl -L https://github.com/docker/compose/releases/download/$dockerComposeVer/docker-compose-$(uname -s)-$(uname -m) >/usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

blue "---------------------"
blue "Install Docker [done]"
blue "---------------------"
}



uninstallDocker(){
rm -rf /etc/apt/sources.list.d/docker.list
apt --purge remove docker-ce docker-ce-cli containerd.io
rm -rf /usr/local/bin/docker-compose
blue "-----------------------"
blue "Uninstall Docker [done]"
blue "-----------------------"
}



start_menu(){
    green "==============================="
    green "         Docker"
    green "==============================="
    green  "1. Install Docker"
    yellow "2. Uninstall Docker"
    echo ""
    read -p "Select:" num
    case "$num" in
    1)
    installDocker
    start_menu
    ;;
    2)
    uninstallDocker
    start_menu
    ;;
    *)
    clear
    red "Wrong number"
    sleep 1s
    start_menu
    ;;
    esac
}

start_menu