#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Collect V2 node${cRES}\r\c"

cat << EOF >/opt/de_GWD/mosdns/matchers_nodes.yaml
plugin:
  - tag: 'domains_nodes'
    type: query_matcher
    args:
      domain:
EOF

jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1 | xargs -n 1 | sort | uniq | sed '/^\s*$/d' | while read line; do
  yq eval -i ".plugin.[0].args.domain += [\"$line\"]" /opt/de_GWD/mosdns/matchers_nodes.yaml
done



>/opt/de_GWD/nftables/IP_V2NODE
jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1 | sort | uniq | sed '/^\s*$/d' | xargs -n 1 | while read line; do
  dig @127.0.0.1 $line -4p 5332 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | grep -v "127.0.0.1" | sed '/^\s*$/d' | xargs -n 1 >>/opt/de_GWD/nftables/IP_V2NODE
done

sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_V2NODE
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_V2NODE
nft flush set ip de_GWD V2NODE
cat << EOF >/opt/de_GWD/nftables/SET_V2NODE.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set V2NODE {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { $(cat /opt/de_GWD/nftables/IP_V2NODE) }
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_V2NODE.nft
/opt/de_GWD/nftables/SET_V2NODE.nft &

[[ $1 = "r" ]] && systemctl restart mosdns

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Collect V2 node${cRES}"
