#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



echo -e "\r\c" && echo -e "${WHITE}[${cRES}...${WHITE}]\c" && echo -e "\t${WHITE}Collect V2 node${cRES}\c"

localDomains=$(jq -r '.dns.servers[1].domains[]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
localDomains+=" "$(jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1)

jq '.dns.servers[1].domains=[]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
echo $localDomains | xargs -n 1 | sort | uniq | sed '/^\s*$/d' | while read line; do
	jq --arg line $line '.dns.servers[1].domains+=[$line]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json && echo "nameserver /$line/GlobalDNS" >>/opt/de_GWD/smartdns/smartdns.conf &
done
wait

[[ $1 = "r" ]] && systemctl restart smartdns && systemctl restart v2dns

echo -e "\r\c" && echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Collect V2 node${cRES}"
