#!/bin/bash
jq '.v2nodeDIV.nodeNF.display="off"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

jq 'del(.routing.rules[] | select(.outboundTag == "netflix"))' /opt/de_GWD/vtrui/config.json |\
jq 'del(.outbounds[] | select(.tag == "netflix"))' | sponge /opt/de_GWD/vtrui/config.json
chmod 666 /opt/de_GWD/vtrui/config.json

if [[ $1 == "r" ]]; then
  systemctl restart vtrui >/dev/null
fi
