#!/bin/bash
customDomain=$(jq -r '.v2nodeDIV.nodeCU.rules' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')

if [[ -n $customDomain ]] && [[ $customDomain != "[]" ]]; then
RoutingCU=`cat << EOF
{
        "type": "field",
        "domain": $customDomain,
        "outboundTag": "custom"
}
EOF
`
jq 'del(.routing.rules[] | select(.outboundTag == "custom"))' /opt/de_GWD/vtrui/config.json |\
jq --argjson RoutingCU "$RoutingCU" '.routing.rules+=[$RoutingCU]' | sponge /opt/de_GWD/vtrui/config.json
chmod 666 /opt/de_GWD/vtrui/config.json
fi

if [[ $1 == "r" ]]; then
	systemctl restart vtrui >/dev/null
fi
