#!/bin/bash
upstreamIP=$(jq -r '.address.upstreamIP' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
localaddrCIDR=$(echo "$(echo $upstreamIP | rev | cut -d'.' -f2-4 | rev).0/24")

pihole -a disabledhcp >/dev/null 2>&1

jq '.address.dhcp="off"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf

sed -i '/REV_SERVER=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_CIDR=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_TARGET=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_DOMAIN=/d' /etc/pihole/setupVars.conf
cat << EOF >> /etc/pihole/setupVars.conf
REV_SERVER=false
EOF
