#!/bin/bash
streamCN=$(jq -r '.dns.servers[3].domains - ["geosite:category-games@cn"]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
jq --argjson streamCN "$streamCN" '.dns.servers[3].domains=$streamCN' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
jq '.dns.STEAMcn="off"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

chmod 666 /opt/de_GWD/v2dns/config.json
chmod 666 /opt/de_GWD/0conf

if [[ $1 == "r" ]]; then
	systemctl restart v2dns >/dev/null
fi
