#!/bin/bash
>/etc/auto.nfs

nfsNUM=$(jq -r '.app.NFS | length' /opt/de_GWD/0conf)

for ((i=0; i<$nfsNUM; i++))
do
NFSpoint=$(jq -r --argjson i "$i" '.app.NFS[$i].NFSpoint' /opt/de_GWD/0conf)
NFSserver=$(jq -r --argjson i "$i" '.app.NFS[$i].NFSserver' /opt/de_GWD/0conf)
NFSaddress=$(jq -r --argjson i "$i" '.app.NFS[$i].NFSaddress' /opt/de_GWD/0conf)
mkdir -p $NFSpoint
echo "$NFSpoint     -rw,soft,rsize=1048576,wsize=1048576    $NFSserver:$NFSaddress" >>/etc/auto.nfs
done

awk '!i[$1]++' /etc/auto.nfs | sponge /etc/auto.nfs

systemctl restart autofs

awk '{print$1}' /etc/auto.nfs | while read line
do
cd $line
done
