#!/bin/bash
ethernetnum=$(find /sys/class/net ! -type d | xargs --max-args=1 realpath | awk -F\/ '/pci/{print $NF}')

systemctl stop wg-quick@wg0 >/dev/null 2>&1
systemctl disable wg-quick@wg0 >/dev/null 2>&1

rm -rf /etc/dnsmasq.d/00-wg.conf
pihole restartdns
