#!/bin/bash
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
cyan()   { echo -e "\033[36m\033[01m $1 \033[0m"; }
white()  { echo -e "\033[37m\033[01m $1 \033[0m"; }
statusUpdated=$(green "[  updated  ]")

localaddr=$(ip -4 a | grep inet | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | head -n 1)
upstreamIP=$(jq -r '.address.upstreamIP' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
localaddrCIDR=$(echo "$(echo $upstreamIP | rev | cut -d'.' -f2-4 | rev).0/24")

dhcpStart=$(jq -r '.address.dhcpStart' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
dhcpEnd=$(jq -r '.address.dhcpEnd' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

if [[ -n $dhcpStart ]] && [[ -n $dhcpEnd ]] && [[ -n $localaddr ]]; then
sudo pihole -a enabledhcp "$dhcpStart" "$dhcpEnd" "$localaddr" "24" "local" >/dev/null 2>&1

/opt/de_GWD/pihole_hotfix

jq '.address.dhcp="on"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
chmod 666 /opt/de_GWD/0conf
fi

sed -i '/REV_SERVER=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_CIDR=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_TARGET=/d' /etc/pihole/setupVars.conf
sed -i '/REV_SERVER_DOMAIN=/d' /etc/pihole/setupVars.conf
cat << EOF >> /etc/pihole/setupVars.conf
REV_SERVER=true
REV_SERVER_CIDR=$localaddrCIDR
REV_SERVER_TARGET=$upstreamIP
REV_SERVER_DOMAIN=
EOF

echo -n "$statusUpdated" && white "DHCP"
