#!/bin/bash
appleCN=$(jq -r '.dns.servers[3].domains - ["geosite:apple","geosite:apple-cn","domain:icloud.com","domain:icloud-content.com"]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
jq --argjson appleCN "$appleCN" '.dns.servers[3].domains=$appleCN' /opt/de_GWD/v2dns/config.json |\
jq --arg APPLE "geosite:apple" '.dns.servers[3].domains+=[$APPLE]' |\
jq --arg APPLE "geosite:apple-cn" '.dns.servers[3].domains+=[$APPLE]' |\
jq --arg APPLE "domain:icloud.com" '.dns.servers[3].domains+=[$APPLE]' |\
jq --arg APPLE "domain:icloud-content.com" '.dns.servers[3].domains+=[$APPLE]' | sponge /opt/de_GWD/v2dns/config.json

jq '.dns.APPLEcn="on"' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

chmod 666 /opt/de_GWD/v2dns/config.json
chmod 666 /opt/de_GWD/0conf

if [[ $1 == "r" ]]; then
	systemctl restart v2dns >/dev/null
fi