#!/bin/bash
appleDirect=$(jq -r '.dns.servers[3].domains - ["geosite:apple","geosite:apple-cn","domain:icloud.com","domain:icloud-content.com"] ' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
jq --argjson appleDirect "$appleDirect" '.dns.servers[3].domains=$appleDirect' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
jq 'del(.dns.APPLEdir)' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf

chmod 666 /opt/de_GWD/v2dns/config.json
chmod 666 /opt/de_GWD/0conf

if [[ $1 == "r" ]]; then
	systemctl restart v2dns >/dev/null
fi
