#!/bin/bash
pingTCPDOH=$(jq -r '.dns.xDNS' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d/ -f1)
echo "$(curl -o /dev/null -sw '%{time_connect}\n' https://$pingTCPDOH) * 1000" | bc | awk '{printf ("%.0f\n",$1)}' 
