#!/bin/bash
sed -i '/PIHOLE_DNS_.*/d' /etc/pihole/setupVars.conf
cat << EOF >>/etc/pihole/setupVars.conf
PIHOLE_DNS_1=127.0.0.1#5331
PIHOLE_DNS_2=127.0.0.1#5331
EOF

sed -i '/server=/d' /etc/dnsmasq.d/01-pihole.conf
cat << EOF >>/etc/dnsmasq.d/01-pihole.conf
server=127.0.0.1#5331
EOF
pihole restartdns

>/etc/resolvconf/resolv.conf.d/head
>/etc/resolvconf/resolv.conf.d/original
>/etc/resolvconf/resolv.conf.d/tail
rm -rf /etc/resolv.conf
rm -rf /run/resolvconf/interface
cat << EOF >/etc/resolvconf/resolv.conf.d/base
nameserver 127.0.0.1
EOF
if [[ -f "/etc/resolvconf/run/resolv.conf" ]]; then
ln -sf /etc/resolvconf/run/resolv.conf /etc/resolv.conf
elif [[ -f "/run/resolvconf/resolv.conf" ]]; then
ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
fi
sed -i '/dns-nameservers /d' /etc/network/interfaces
resolvconf -u

nft delete table ip de_GWD >/dev/null 2>&1
ip rule del table 220 >/dev/null 2>&1
ip route flush table 220 >/dev/null 2>&1
ip route flush cache >/dev/null 2>&1
ip route del local default dev lo table 220 >/dev/null 2>&1
systemctl stop nftables
