#!/bin/bash
pingTCPDOH=$(jq -r '.dns.doh[]' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | awk NR==1 | cut -d/ -f1)
echo "$(curl -o /dev/null -m 5 -kIsw '%{time_connect}\n' https://$pingTCPDOH) * 1000" | bc | awk '{printf ("%.0f\n",$1)}' 
