#!/bin/bash
/opt/de_GWD/ui-smartDNS r

>/etc/resolvconf/resolv.conf.d/head
>/etc/resolvconf/resolv.conf.d/original
>/etc/resolvconf/resolv.conf.d/tail
rm -rf /etc/resolv.conf
rm -rf /run/resolvconf/interface
cat << EOF >/etc/resolvconf/resolv.conf.d/base
nameserver 127.0.0.1
EOF
if [[ -f "/etc/resolvconf/run/resolv.conf" ]]; then
ln -sf /etc/resolvconf/run/resolv.conf /etc/resolv.conf
elif [[ -f "/run/resolvconf/resolv.conf" ]]; then
ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
fi
resolvconf -u

systemctl restart v2dns >/dev/null

sed -i '/PIHOLE_DNS_.*/d' /etc/pihole/setupVars.conf
echo "PIHOLE_DNS_1=127.0.0.1#5350" >>/etc/pihole/setupVars.conf
echo "PIHOLE_DNS_2=127.0.0.1#5350" >>/etc/pihole/setupVars.conf
pihole restartdns

systemctl restart vtrui >/dev/null
systemctl restart nftables >/dev/null