#!/bin/bash
>/etc/resolvconf/resolv.conf.d/head
>/etc/resolvconf/resolv.conf.d/original
>/etc/resolvconf/resolv.conf.d/tail
rm -rf /etc/resolv.conf
rm -rf /run/resolvconf/interface
cat << EOF >/etc/resolvconf/resolv.conf.d/base
nameserver 127.0.0.1
EOF
if [[ -f "/etc/resolvconf/run/resolv.conf" ]]; then
ln -sf /etc/resolvconf/run/resolv.conf /etc/resolv.conf
elif [[ -f "/run/resolvconf/resolv.conf" ]]; then
ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
fi
resolvconf -u

sed -i '/PIHOLE_DNS_.*/d' /etc/pihole/setupVars.conf
echo "PIHOLE_DNS_1=127.0.0.1#5310" >>/etc/pihole/setupVars.conf
echo "PIHOLE_DNS_2=127.0.0.1#5310" >>/etc/pihole/setupVars.conf
pihole restartdns

nft delete table ip de_GWD >/dev/null 2>&1
ip rule del table 220 >/dev/null 2>&1
ip route flush table 220 >/dev/null 2>&1
ip route flush cache >/dev/null 2>&1
ip route del local default dev lo table 220 >/dev/null 2>&1
