#!/bin/bash
pingTCPDoG=$(jq -r '.dns.DoG' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d/ -f1)
echo "$(curl -o /dev/null -m 5 -kIsw '%{time_connect}\n' https://$pingTCPDoG) * 1000" | bc | awk '{printf ("%.0f\n",$1)}' 
