#!/bin/bash
if [[ $(du -sk /var/www/html/restore/de_GWD_bak 2>/dev/null | awk '{print$1}') -gt 1 ]]; then
mv -f /var/www/html/restore/de_GWD_bak /opt/de_GWD/0conf

if [[ -n $(jq -r '.address.alias' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$') ]]; then
 	/opt/de_GWD/ui-markThis
fi

/opt/de_GWD/ui-NodeOne

if [[ $(jq -r '.address.dhcp' /opt/de_GWD/0conf 2>/dev/null) = "on" ]]; then
	/opt/de_GWD/ui-DHCPon
fi

if [[ $(jq -r '.v2nodeDIV.nodeSM.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]]; then
  /opt/de_GWD/ui-NodeSM >/dev/null 2>&1
fi

if [[ $(jq -r '.v2nodeDIV.nodeCU.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]]; then
  /opt/de_GWD/ui-NodeCU >/dev/null 2>&1
fi

if [[ $(jq -r '.v2nodeDIV.nodeDT.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]]; then
  /opt/de_GWD/ui-NodeDT >/dev/null 2>&1
fi

if [[ $(jq -r '.FORWARD.FWD1.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]];then
  /opt/de_GWD/ui-FWD1save >/dev/null 2>&1
fi

if [[ $(jq -r '.FORWARD.Rproxy.client.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]];then
  /opt/de_GWD/ui-RproxyCsave >/dev/null 2>&1
fi

if [[ $(jq -r '.FORWARD.Rproxy.server.status' /opt/de_GWD/0conf 2>/dev/null) = "on" ]];then
  /opt/de_GWD/ui-RproxySsave >/dev/null 2>&1
fi

/opt/de_GWD/ui_4h

systemctl restart nftables
systemctl restart mosdns
systemctl restart vtrui
fi
