#!/bin/bash
localaddr=$(jq -r '.address.localIP' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')
upstreamip=$(jq -r '.address.upstreamIP' /opt/de_GWD/0conf | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

if [[ -n $localaddr ]] && [[ -n $upstreamip ]]; then
	sed -i "/address/c\address $localaddr" /etc/network/interfaces
	sed -i "/gateway/c\gateway $upstreamip" /etc/network/interfaces
	sed -i "/IPV4_ADDRESS=/c\IPV4_ADDRESS=$localaddr/24" /etc/pihole/setupVars.conf
fi

cat << "EOF" >~/clearKernel
#!/bin/bash
PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

dpkg --list | grep linux-image | awk '{print $2}' | grep -Fv $(uname -r) | while read line
do
apt -y --purge autoremove $line
done

dpkg --list | grep linux-headers | awk '{print $2}' | grep -Fv $(uname -r) | while read line
do
apt -y --purge autoremove $line
done

crontab -l 2>/dev/null > ~/now.cron
sed -i '/clearKernel/d' ~/now.cron
crontab ~/now.cron
rm -rf ~/now.cron
rm -rf ~/clearKernel
systemctl restart sshd >/dev/null
EOF
chmod +x ~/clearKernel

crontab -l 2>/dev/null > ~/now.cron
echo '@reboot ~/clearKernel' >> ~/now.cron
crontab ~/now.cron
rm -rf ~/now.cron

sleep 2
reboot