#!/bin/bash
jq -r '.dns.listB[]' /opt/de_GWD/0conf 2>/dev/null | sort | uniq | sed '/^\s*$/d' >/tmp/listBpre
jq -r '.dns.listW[]' /opt/de_GWD/0conf 2>/dev/null | sort | uniq | sed '/^\s*$/d' >/tmp/listWpre

>/opt/de_GWD/nftables/IP_listB
jq 'del(.dns.servers[2].domains)' /tmp/v2dns_config |\
jq '.dns.servers[2].domains+=["domain:raw.githubusercontent.com"]' | sponge /tmp/v2dns_config
if [[ -n $(cat /tmp/listBpre) ]]; then
	sed -i '/listB_START/,/listB_END/d' /etc/smartdns/smartdns.conf
	echo "# listB_START" >>/etc/smartdns/smartdns.conf
	cat /tmp/listBpre | xargs -n 8 | while read listB 
	do
		for listBdomain in $listB
		do
		jq --arg listB "domain:$listBdomain" '.dns.servers[2].domains+=[$listB]' /tmp/v2dns_config | sponge /tmp/v2dns_config
		dig @127.0.0.1 $listBdomain -4p 5321 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | xargs -n1 >>/opt/de_GWD/nftables/IP_listB
		echo "nameserver /$listBdomain/GlobalDNS" >>/etc/smartdns/smartdns.conf
		done
		wait
	done
	echo "# listB_END" >>/etc/smartdns/smartdns.conf
fi
sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listB
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listB
[[ $(du -sk /opt/de_GWD/nftables/IP_listB 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listB_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listB) }"
nft flush set ip de_GWD listB
cat << EOF >/opt/de_GWD/nftables/SET_listB.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listB {
                type ipv4_addr
                flags interval
                auto-merge
                $IP_listB_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listB.nft
/opt/de_GWD/nftables/SET_listB.nft


>/opt/de_GWD/nftables/IP_listW
jq 'del(.dns.servers[3].domains)' /tmp/v2dns_config |\
jq '.dns.servers[3].domains+=["domain:live.com"]' | sponge /tmp/v2dns_config
if [[ -n $(cat /tmp/listWpre) ]]; then
	sed -i '/listW_START/,/listW_END/d' /etc/smartdns/smartdns.conf
	echo "# listW_START" >>/etc/smartdns/smartdns.conf
	cat /tmp/listWpre | xargs -n 8 | while read listW
	do
		for listWdomain in $listW
		do
		jq --arg listW "domain:$listWdomain" '.dns.servers[3].domains+=[$listW]' /tmp/v2dns_config | sponge /tmp/v2dns_config
		dig @127.0.0.1 $listWdomain -4p 5311 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | xargs -n1 >>/opt/de_GWD/nftables/IP_listW
		echo "nameserver /$listWdomain/INTchnDNS" >>/etc/smartdns/smartdns.conf
		done
		wait
	done
	echo "# listW_END" >>/etc/smartdns/smartdns.conf
fi
sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listW
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listW
[[ $(du -sk /opt/de_GWD/nftables/IP_listW 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listW_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listW) }"
nft flush set ip de_GWD listW
cat << EOF >/opt/de_GWD/nftables/SET_listW.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listW {
                type ipv4_addr
                flags interval
                auto-merge
                $IP_listW_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listW.nft
/opt/de_GWD/nftables/SET_listW.nft

[[ -n $(cat /tmp/v2dns_config) ]] && mv -f /tmp/v2dns_config /opt/de_GWD/v2dns/config.json

chmod 666 /opt/de_GWD/0conf

rm -rf /tmp/listBpre
rm -rf /tmp/listWpre
