#!/bin/bash
>/opt/de_GWD/nftables/IP_V2NODE
jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1 | sort | uniq | sed '/^\s*$/d' | xargs -n 8 | while read line
do
  for domainV2node in $line
  do
  dig @127.0.0.1 $domainV2node -4p 5320 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | grep -v "127.0.0.1" | sed '/^\s*$/d' | xargs -n 1 >>/opt/de_GWD/nftables/IP_V2NODE &
  done
  wait
done

sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_V2NODE
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_V2NODE
[[ $(du -sk /opt/de_GWD/nftables/IP_V2NODE 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_V2NODE_elements="elements = { $(cat /opt/de_GWD/nftables/IP_V2NODE) }"
nft flush set ip de_GWD V2NODE
cat << EOF >/opt/de_GWD/nftables/SET_V2NODE.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set V2NODE {
                type ipv4_addr
                flags interval
                auto-merge
                $IP_V2NODE_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_V2NODE.nft
/opt/de_GWD/nftables/SET_V2NODE.nft

localDomains=$(jq -r '.dns.servers[1].domains[]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
localDomains+=" "$(jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1)

jq '.dns.servers[1].domains=[]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
echo $localDomains | xargs -n 1 | sort | uniq | sed '/^\s*$/d' | while read line
do
	jq --arg line $line '.dns.servers[1].domains+=[$line]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
done
chmod 666 /opt/de_GWD/v2dns/config.json
