#!/bin/bash
>/opt/de_GWD/IPv2node
jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1 | sort | uniq | sed '/^\s*$/d' | xargs -n 8 | while read line
do
  for domainV2node in $line
  do
  dig @127.0.0.1 $domainV2node -4p 5321 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | grep -v "127.0.0.1" | sed '/^\s*$/d' | xargs -n 1 >>/opt/de_GWD/IPv2node &
  done
  wait
done

sed -i '/^\s*$/d' /opt/de_GWD/IPv2node
sed -i 's/^/add v2node &/g' /opt/de_GWD/IPv2node
if [[ $(du -sk /opt/de_GWD/IPv2node 2>/dev/null | awk '{print$1}') != 0 ]]; then
mv -f /opt/de_GWD/IPv2node /opt/de_GWD/IPv2nodeSET
ipset -! -R </opt/de_GWD/IPv2nodeSET
fi

localDomains=$(jq -r '.dns.servers[1].domains[]' /opt/de_GWD/v2dns/config.json 2>/dev/null | grep -v '^null$')
localDomains+=" "$(jq -r '.v2node[].domain' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$' | cut -d: -f1)

jq '.dns.servers[1].domains=[]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
echo $localDomains | xargs -n 1 | sort | uniq | sed '/^\s*$/d' | while read line
do
	jq --arg line $line '.dns.servers[1].domains+=[$line]' /opt/de_GWD/v2dns/config.json | sponge /opt/de_GWD/v2dns/config.json
done
chmod 666 /opt/de_GWD/v2dns/config.json
