#!/bin/bash
if [[ $(awk '/listB/ {print;exit}' /opt/de_GWD/0conf) =~ "[" ]]; then
	jq -r '.listB[]' /opt/de_GWD/0conf | sort | uniq | sed '/^\s*$/d' >/tmp/listBpre
elif [[ $(awk '/listB/ {print;exit}' /opt/de_GWD/0conf) =~ "{" ]]; then
	jq -r '.listB | keys[]' /opt/de_GWD/0conf | sort | uniq | sed '/^\s*$/d' >/tmp/listBpre
fi

if [[ $(awk '/listW/ {print;exit}' /opt/de_GWD/0conf) =~ "[" ]]; then
	jq -r '.listW[]' /opt/de_GWD/0conf | sort | uniq | sed '/^\s*$/d' >/tmp/listWpre
elif [[ $(awk '/listW/ {print;exit}' /opt/de_GWD/0conf) =~ "{" ]]; then
	jq -r '.listW | keys[]' /opt/de_GWD/0conf | sort | uniq | sed '/^\s*$/d' >/tmp/listWpre
fi


>/opt/de_GWD/nftables/IP_listB
>/opt/de_GWD/nftables/IP_listW
jq 'del(.dns.servers[2].domains)' /tmp/v2dns_config |\
jq '.dns.servers[2].domains+=["domain:play.googleapi.cn"]' |\
jq '.dns.servers[2].domains+=["domain:raw.githubusercontent.com"]' | sponge /tmp/v2dns_config

if [[ -f "/tmp/listBpre" ]] && [[ -n $(cat /tmp/listBpre) ]]; then
	jq '.listB={}' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
	cat /tmp/listBpre | xargs -n 8 | while read listB 
	do
		for domainlistB in $listB
		do
		jq --arg listB "domain:$domainlistB" '.dns.servers[2].domains+=[$listB]' /tmp/v2dns_config | sponge /tmp/v2dns_config
		unset listBIP
		listBIP+=($(dig @127.0.0.1 $domainlistB -4p 5311 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'))
		listBIP+=($(dig @127.0.0.1 $domainlistB -4p 5321 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'))
		echo ${listBIP[@]} | xargs -n1 >>/opt/de_GWD/nftables/IP_listB
		listBIPvalue=$(jq -n --rawfile listBIP /opt/de_GWD/nftables/IP_listB '$listBIP | split("\n") | map(select(length > 0))')
		jq --arg key "$domainlistB" --arg value "$listBIPvalue" '.listB += {($key):$value}' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
		done
		wait
	done
fi


jq 'del(.dns.servers[3].domains)' /tmp/v2dns_config |\
jq '.dns.servers[3].domains+=["domain:live.com"]' | sponge /tmp/v2dns_config

if [[ -f "/tmp/listWpre" ]] && [[ -n $(cat /tmp/listWpre) ]]; then
	jq '.listW={}' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
	cat /tmp/listWpre | xargs -n 8 | while read listW
	do
		for domainlistW in $listW
		do
		jq --arg listW "domain:$domainlistW" '.dns.servers[3].domains+=[$listW]' /tmp/v2dns_config | sponge /tmp/v2dns_config
		unset listWIP
		listWIP+=($(dig @127.0.0.1 $domainlistW -4p 5311 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'))
		listWIP+=($(dig @127.0.0.1 $domainlistW -4p 5321 +short  | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'))
		echo ${listWIP[@]} | xargs -n1 >>/opt/de_GWD/nftables/IP_listW
		listWIPvalue=$(jq -n --rawfile listWIP /opt/de_GWD/nftables/IP_listW '$listWIP | split("\n") | map(select(length > 0))')
		jq --arg key "$domainlistW" --argjson value "$listWIPvalue" '.listW += {($key):$value}' /opt/de_GWD/0conf | sponge /opt/de_GWD/0conf
		done
		wait
	done
fi

if [[ -n $(cat /tmp/v2dns_config) ]]; then
  mv -f /tmp/v2dns_config /opt/de_GWD/v2dns/config.json
fi

>/opt/de_GWD/nftables/IP_listBlan
jq -r '.listBlan[]' /opt/de_GWD/0conf 2>/dev/null | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' >/opt/de_GWD/nftables/IP_listBlan

>/opt/de_GWD/nftables/IP_listWlan
jq -r '.listWlan[]' /opt/de_GWD/0conf 2>/dev/null | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' >/opt/de_GWD/nftables/IP_listWlan


sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listB
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listB
[[ $(du -sk /opt/de_GWD/nftables/IP_listB 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listB_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listB) }"
nft flush set ip de_GWD listB
cat << EOF >/opt/de_GWD/nftables/SET_listB.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listB {
                type ipv4_addr
                flags interval
				auto-merge
                $IP_listB_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listB.nft
/opt/de_GWD/nftables/SET_listB.nft

sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listW
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listW
[[ $(du -sk /opt/de_GWD/nftables/IP_listW 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listW_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listW) }"
nft flush set ip de_GWD listW
cat << EOF >/opt/de_GWD/nftables/SET_listW.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listW {
                type ipv4_addr
                flags interval
				auto-merge
                $IP_listW_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listW.nft
/opt/de_GWD/nftables/SET_listW.nft

sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listBlan
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listBlan
[[ $(du -sk /opt/de_GWD/nftables/IP_listBlan 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listBlan_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listBlan) }"
nft flush set ip de_GWD listBlan
cat << EOF >/opt/de_GWD/nftables/SET_listBlan.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listBlan {
                type ipv4_addr
                flags interval
				auto-merge
                $IP_listBlan_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listBlan.nft
/opt/de_GWD/nftables/SET_listBlan.nft

sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listWlan
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listWlan
[[ $(du -sk /opt/de_GWD/nftables/IP_listWlan 2>/dev/null | awk '{print$1}') -gt 2 ]] && IP_listWlan_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listWlan) }"
nft flush set ip de_GWD listWlan
cat << EOF >/opt/de_GWD/nftables/SET_listWlan.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listWlan {
                type ipv4_addr
                flags interval
				auto-merge
                $IP_listWlan_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listWlan.nft
/opt/de_GWD/nftables/SET_listWlan.nft

chmod 666 /opt/de_GWD/0conf
