#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'


echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Collect Black and white list${cRES}\r\c"

>/opt/de_GWD/mosdns/domains_listB
>/opt/de_GWD/nftables/IP_listB
jq -r '.dns.listB[]' /opt/de_GWD/0conf 2>/dev/null | sort | uniq | xargs -n 1 | sed '/^\s*$/d' | while read listB; do
  echo $listB >>/opt/de_GWD/mosdns/domains_listB
  dig @127.0.0.1 $listB -4p 5332 +short | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | xargs -n1 >>/opt/de_GWD/nftables/IP_listB
done


sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listB
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listB
[[ -n $(cat /opt/de_GWD/nftables/IP_listB 2>&1 | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}') ]] && IP_listB_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listB) }"
nft flush set ip de_GWD listB
cat << EOF >/opt/de_GWD/nftables/SET_listB.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listB {
                type ipv4_addr
                flags interval
                auto-merge
                $IP_listB_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listB.nft
/opt/de_GWD/nftables/SET_listB.nft




>/opt/de_GWD/mosdns/domains_listW
>/opt/de_GWD/nftables/IP_listW
jq -r '.dns.listW[]' /opt/de_GWD/0conf 2>/dev/null | sort | uniq | xargs -n 1 | sed '/^\s*$/d' | while read listW; do
  echo $listW >>/opt/de_GWD/mosdns/domains_listW
  dig @127.0.0.1 $listW -4p 5331 +short | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | xargs -n1 >>/opt/de_GWD/nftables/IP_listW
done


sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_listW
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_listW
[[ -n $(cat /opt/de_GWD/nftables/IP_listW 2>&1 | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}') ]] && IP_listW_elements="elements = { $(cat /opt/de_GWD/nftables/IP_listW) }"
nft flush set ip de_GWD listW
cat << EOF >/opt/de_GWD/nftables/SET_listW.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set listW {
                type ipv4_addr
                flags interval
                auto-merge
                $IP_listW_elements
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_listW.nft
/opt/de_GWD/nftables/SET_listW.nft

/opt/de_GWD/ui-submitListBWsm

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Collect Black and white list${cRES}"
