#!/bin/bash
updatePort=$(jq -r '.update.updatePort' /opt/de_GWD/0conf)

sed -i "/ExecStart=/c\ExecStart=/usr/bin/ttyd -p $updatePort -o /opt/de_GWD/update" /etc/systemd/system/updateGWD.service
ln -sf /etc/systemd/system/updateGWD.service /lib/systemd/system/updateGWD.service >/dev/null 2>&1
systemctl daemon-reload >/dev/null
