#!/bin/bash
if [[ $(du -sk /opt/de_GWD/update 2>/dev/null | awk '{print$1}') -le 1 ]]; then
updateCMDaddr=$(jq -r '.update.updateCMD' /opt/de_GWD/0conf 2>/dev/null | grep -oP "https://\K[^']+" | sed s'/.$//')

systemctl stop nftables
rm -rf /etc/resolv.conf
cat << EOF >/etc/resolv.conf
nameserver 119.29.29.29
nameserver 182.254.118.118
nameserver 114.114.114.114
EOF

wget -cqO /opt/de_GWD/update $updateCMDaddr
fi
chmod +x /opt/de_GWD/update

updatePort=$(jq -r '.update.updatePort' /opt/de_GWD/0conf)

sed -i "/ExecStart=/c\ExecStart=/usr/bin/tmux new -ds 'updateGWD' /usr/bin/ttyd -p $updatePort -o /opt/de_GWD/update" /etc/systemd/system/updateGWD.service
systemctl daemon-reload >/dev/null
