#!/bin/bash
chmod +x /opt/de_GWD/update
if [[ $(du -sk /opt/de_GWD/update 2>/dev/null | awk '{print$1}') -le 1 ]]; then
updateCMDaddr=$(jq -r '.update.updateCMD' /opt/de_GWD/0conf 2>/dev/null | grep -oP "https://\K[^']+" | sed s'/.$//')
systemctl stop nftables

[[ -n "$(ps -e | grep 'pihole-FTL' )" ]] && systemctl stop pihole-FTL
kill -9 $(ps -e | grep 'pihole' | awk '{print$1}') >/dev/null 2>&1

rm -rf /etc/resolv.conf
cat << EOF >/etc/resolv.conf
nameserver 119.29.29.29
nameserver 180.76.76.76
nameserver 114.114.114.114
nameserver 223.5.5.5
EOF

wget -cqO /opt/de_GWD/update $updateCMDaddr
fi

updatePort=$(jq -r '.update.updatePort' /opt/de_GWD/0conf)

kill $(ps -e | grep 'ttyd' | awk '{print$1}') >/dev/null 2>&1
tmux kill-session -t updateGWD >/dev/null 2>&1
sed -i "/ExecStart=/c\ExecStart=/usr/bin/tmux new -ds 'updateGWD' /usr/bin/ttyd -p $updatePort -o /opt/de_GWD/update" /etc/systemd/system/updateGWD.service
systemctl daemon-reload >/dev/null

