#!/bin/bash
tag=$1
IP=$2

RoutingADD=`cat << EOF
{
        "type": "field",
        "ip": $IP,
        "outboundTag": "$tag"
}
EOF
`

jq --argjson RoutingADD "$RoutingADD" '.routing.rules+=[$RoutingADD]' /opt/de_GWD/vtrui/config.json | sponge /opt/de_GWD/vtrui/config.json

