#!/bin/bash
wanIP=$(curl -sSL http://myip.ipip.net | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

[[ $(echo $wanIP | grep -v '127.0.0.1' | wc -m) -lt 8 ]] && wanIP=$(curl -sSL http://su.baidu.com/cdn-cgi/trace | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}')

echo $wanIP
