#!/bin/bash
unset publicIPurls
publicIPurls+=(http://ifconfig.me)
publicIPurls+=(http://whatismyip.akamai.com)
publicIPurls+=(http://ip.sb)
publicIPurls+=(http://icanhazip.com)

for (( i=0; i<10; ++i)); do
	wanIP=$(curl -4sSLm 1 ${publicIPurls[$RANDOM % ${#publicIPurls[@]}]} 2>/dev/null | grep -Po '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}' | xargs -n1 | awk NR==1 | grep -v '127.0.0.1')
    [[ -n $wanIP ]] && break
    sleep 1
done

echo $wanIP
