#!/bin/bash
systemctl stop wg-quick@wg0 >/dev/null 2>&1
systemctl disable wg-quick@wg0 >/dev/null 2>&1

find /sys/class/net ! -type d | xargs --max-args=1 realpath | grep 'device' | grep -v 'veth' | awk -F'/' '{print$NF}' | xargs -I {} echo "interface={}" >/etc/dnsmasq.d/00-interface.conf

/etc/rc_online.local
