#!/bin/bash
rm -rf /opt/de_GWD/xDNSs
mkdir -p /opt/de_GWD/xDNSs
cp -f /opt/de_GWD/vtrui/vtrui /opt/de_GWD/xDNSs/xDNSs
chmod +x /opt/de_GWD/xDNSs/xDNSs

xDNSsPort=$(jq -r '.FORWARD.xDNSs.port' /opt/de_GWD/0conf 2>/dev/null | grep -v '^null$')

cat << EOF >/opt/de_GWD/xDNSs/config.json
{
  "dns":{
    "tag":"dnsFlow",
    "servers":[{"address":"127.0.0.1","port":53}]
  },
  "routing":{
    "rules":[
      {"type":"field","inboundTag":["xDNSsIN"],"outboundTag":"xDNSsOUT"}
    ]
  },
  "inbounds": [
    {
      "tag": "xDNSsIN",
      "port": $xDNSsPort,
      "protocol": "vless",
      "settings":{
        "decryption": "none",
        "clients":[
          {
            "id":"ccabd6d0-beb2-4b8a-8f94-45f3dc235ebe",
            "flow":"xtls-rprx-direct",
            "level":0
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "certificates": [
            {
              "certificateFile": "/var/www/ssl/de_GWD.cer",
              "keyFile": "/var/www/ssl/de_GWD.key"
            }
          ]
        },
        "sockopt": {
          "tcpFastOpen": true
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "blackhole",
      "settings":{"response":{"type":"http"}}
    },
    {
      "tag": "xDNSsOUT",
      "protocol": "freedom",
      "settings": {
        "redirect": "127.0.0.1:53"
      },
      "streamSettings":{"sockopt":{"tcpFastOpen":true,"tproxy":"off","mark":255}}
    }
  ]
}
EOF

chmod 666 /opt/de_GWD/xDNSs/config.json
chmod 644 /var/www/ssl/*.key

rm -rf /lib/systemd/system/xDNSs.service
cat << "EOF" >/etc/systemd/system/xDNSs.service
[Unit]
Description=xDNS Server
After=network.target nss-lookup.target

[Service]
User=www-data
Type=simple
ExecStart=/opt/de_GWD/xDNSs/xDNSs -c /opt/de_GWD/xDNSs/config.json
AmbientCapabilities=CAP_NET_RAW CAP_NET_ADMIN CAP_NET_BIND_SERVICE
LimitNOFILE=1000000
LimitNPROC=infinity
LimitCORE=infinity
NoNewPrivileges=true
Nice=-9
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=10
IOSchedulingClass=best-effort
IOSchedulingPriority=0
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
EOF

if [[ $(cat /proc/sys/kernel/sched_autogroup_enabled 2>/dev/null) != 1 ]]; then
sed -i '/Nice=/d' /etc/systemd/system/xDNSs.service
sed -i '/CPUSchedulingPolicy=/d' /etc/systemd/system/xDNSs.service
sed -i '/CPUSchedulingPriority=/d' /etc/systemd/system/xDNSs.service
sed -i '/IOSchedulingClass=/d' /etc/systemd/system/xDNSs.service
sed -i '/IOSchedulingPriority=/d' /etc/systemd/system/xDNSs.service
fi

ln -sf /etc/systemd/system/xDNSs.service /lib/systemd/system/xDNSs.service >/dev/null 2>&1
systemctl daemon-reload >/dev/null
systemctl restart xDNSs >/dev/null
systemctl enable xDNSs >/dev/null
