#!/bin/bash
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
cyan()   { echo -e "\033[36m\033[01m $1 \033[0m"; }
white()  { echo -e "\033[37m\033[01m $1 \033[0m"; }
statusUpdated=$(green "[  updated  ]")

serverConnect1=$(curl -Ism 5 google.com | grep 'HTTP')
serverConnect2=$(curl -Ism 5 youtube.com | grep 'HTTP')

if [[ -z $serverConnect1 ]] && [[ -z $serverConnect2 ]]; then
exit
fi

[[ $1 = "u" ]] &&	service cron stop

/opt/de_GWD/tcpTime

checkSum(){
sha256sumL=$(sha256sum $1 2>/dev/null | awk '{print$1}')
if [[ $sha256sumL = $2 ]]; then 
  echo "true"
elif [[ $sha256sumL != $2 ]]; then
  echo "false"
fi
}

geosite_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat.sha256sum | awk '{print$1}')
geoip_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat.sha256sum | awk '{print$1}')
geoipCN_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/Loyalsoldier/geoip/release/cn.dat.sha256sum | awk '{print$1}')
IPchnroute_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute.sha256sum)
SmartDNS_domainCN_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/accelerated-domains.china.conf.sha256sum)
SmartDNS_appleCN_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/apple.china.conf.sha256sum)
SmartDNS_whitelistIP_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/whitelist-ip-chnlist.conf.sha256sum)

if [[ $(checkSum /opt/de_GWD/.repo/geosite.dat $geosite_sha256sum) = "false" ]]; then
rm -rf /tmp/geosite.dat
wget --show-progress -cqO /tmp/geosite.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
  if [[ $(checkSum /tmp/geosite.dat $geosite_sha256sum) = "true" ]]; then
    mv -f /tmp/geosite.dat /opt/de_GWD/.repo/geosite.dat
  else
    red "geosite.dat < Download Failed >"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoip.dat $geoip_sha256sum) = "false" ]]; then
rm -rf /tmp/geoip.dat
wget --show-progress -cqO /tmp/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  if [[ $(checkSum /tmp/geoip.dat $geoip_sha256sum) = "true" ]]; then
    mv -f /tmp/geoip.dat /opt/de_GWD/.repo/geoip.dat
  else
    red "geoip.dat < Download Failed >"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoipCN.dat $geoipCN_sha256sum) = "false" ]]; then
rm -rf /tmp/geoipCN.dat
wget --show-progress -cqO /tmp/geoipCN.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/cn.dat
  if [[ $(checkSum /tmp/geoipCN.dat $geoipCN_sha256sum) = "true" ]]; then
    mv -f /tmp/geoipCN.dat /opt/de_GWD/.repo/geoipCN.dat
  else
    red "geoipCN.dat < Download Failed >"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/IPchnroute $IPchnroute_sha256sum) = "false" ]]; then
rm -rf /tmp/IPchnroute
wget --show-progress -cqO /tmp/IPchnroute https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute
  if [[ $(checkSum /tmp/IPchnroute $IPchnroute_sha256sum) = "true" ]]; then
    mv -f /tmp/IPchnroute /opt/de_GWD/.repo/IPchnroute
  else
    red "IPchnroute < Download Failed >"
  fi
fi

mkdir -p /opt/de_GWD/.repo/SmartDNS_chnlist
if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/accelerated-domains.china.conf $SmartDNS_domainCN_sha256sum) = "false" ]]; then
rm -rf /tmp/accelerated-domains.china.conf
wget --show-progress -cqO /tmp/accelerated-domains.china.conf https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/accelerated-domains.china.conf
  if [[ $(checkSum /tmp/accelerated-domains.china.conf $SmartDNS_domainCN_sha256sum) = "true" ]]; then
    mv -f /tmp/accelerated-domains.china.conf /opt/de_GWD/.repo/SmartDNS_chnlist/accelerated-domains.china.conf
  else
    red "accelerated-domains.china.conf < Download Failed >"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/apple.china.conf $SmartDNS_appleCN_sha256sum) = "false" ]]; then
rm -rf /tmp/apple.china.conf
wget --show-progress -cqO /tmp/apple.china.conf https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/apple.china.conf
  if [[ $(checkSum /tmp/apple.china.conf $SmartDNS_appleCN_sha256sum) = "true" ]]; then
    mv -f /tmp/apple.china.conf /opt/de_GWD/.repo/SmartDNS_chnlist/apple.china.conf
  else
    red "apple.china.conf < Download Failed >"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/whitelist-ip-chnlist.conf $SmartDNS_whitelistIP_sha256sum) = "false" ]]; then
rm -rf /tmp/whitelist-ip-chnlist.conf
wget --show-progress -cqO /tmp/whitelist-ip-chnlist.conf https://raw.githubusercontent.com/jacyl4/chnroute/main/SmartDNS_chnlist/whitelist-ip-chnlist.conf
  if [[ $(checkSum /tmp/whitelist-ip-chnlist.conf $SmartDNS_whitelistIP_sha256sum) = "true" ]]; then
    mv -f /tmp/whitelist-ip-chnlist.conf /opt/de_GWD/.repo/SmartDNS_chnlist/whitelist-ip-chnlist.conf
  else
    red "whitelist-ip-chnlist.conf < Download Failed >"
  fi
fi



if [[ $(checkSum /opt/de_GWD/.repo/geosite.dat $geosite_sha256sum) = "true" ]]; then
  cp -f /opt/de_GWD/.repo/geosite.dat /opt/de_GWD/v2dns/geosite.dat
  cp -f /opt/de_GWD/.repo/geosite.dat /opt/de_GWD/vtrui/geosite.dat
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoip.dat $geoip_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/geoip.dat /opt/de_GWD/vtrui/geoip.dat
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoipCN.dat $geoipCN_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/geoipCN.dat /opt/de_GWD/v2dns/geoipCN.dat
fi

if [[ $(checkSum /opt/de_GWD/.repo/IPchnroute $IPchnroute_sha256sum) = "true" ]]; then
cp -f /opt/de_GWD/.repo/IPchnroute /opt/de_GWD/nftables/IP_CHNROUTE
sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_CHNROUTE
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_CHNROUTE
nft flush set ip de_GWD CHNROUTE
cat << EOF >/opt/de_GWD/nftables/SET_CHNROUTE.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set CHNROUTE {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { $(cat /opt/de_GWD/nftables/IP_CHNROUTE) }
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_CHNROUTE.nft
/opt/de_GWD/nftables/SET_CHNROUTE.nft
fi

if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/accelerated-domains.china.conf $SmartDNS_domainCN_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/SmartDNS_chnlist/accelerated-domains.china.conf /etc/smartdns/accelerated-domains.china.conf
fi

if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/apple.china.conf $SmartDNS_appleCN_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/SmartDNS_chnlist/apple.china.conf /etc/smartdns/apple.china.conf
fi

if [[ $(checkSum /opt/de_GWD/.repo/SmartDNS_chnlist/whitelist-ip-chnlist.conf $SmartDNS_whitelistIP_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/SmartDNS_chnlist/whitelist-ip-chnlist.conf /etc/smartdns/whitelist-ip-chnlist.conf
fi



if [[ -n $(openssl x509 -enddate -noout -in /var/www/ssl/de_GWD.cer -checkend 259200 | grep "Certificate will expire") ]] && [[ -d "/root/.acme.sh" ]]; then
"/root/.acme.sh"/acme.sh --force --set-default-ca  --server letsencrypt
"/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh" >/dev/null 2>&1

sslFolder=$(ls "/root/.acme.sh" | grep '_ecc')
cp -f "/root/.acme.sh"/$sslFolder/fullchain.cer /var/www/ssl/de_GWD.cer
cp -f "/root/.acme.sh"/$sslFolder/*.key /var/www/ssl/de_GWD.key
fi

[[ -f "/var/www/ssl/update_ocsp_cache" ]] && /var/www/ssl/update_ocsp_cache >/dev/null 2>&1

echo -n "$statusUpdated" && white "IP & Domain rules"

[[ $1 = "u" ]] && service cron restart
