#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



echo -e "\r\c" && echo -e "${WHITE}[${cRES}...${WHITE}]\c" && echo -e "\t${WHITE}DNS Crontab Task${cRES}\c"

/opt/de_GWD/ui-smartDNS

/opt/de_GWD/ui-DNSsplit r

[[ $(systemctl is-active 'pihole-FTL') != "active" ]] && systemctl restart pihole-FTL

echo -e "\r\c" && echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}DNS Crontab Task${cRES}"
