#!/bin/bash
RED='\E[1;31m'
GREEN='\E[1;32m'
YELLOW='\E[1;33m'
BLUE='\E[1;34m'
PURPLE='\E[1;35m'
CYAN='\E[1;36m'
WHITE='\E[1;37m'
cRES='\E[0m'



/opt/de_GWD/tcpTime

serverConnect1=$(curl -Is -m 5 google.com | grep 'HTTP')
serverConnect2=$(curl -Is -m 5 youtube.com | grep 'HTTP')
[[ -z $serverConnect1 ]] && [[ -z $serverConnect2 ]] && exit

[[ $1 = "u" ]] && service cron stop

echo -e "${WHITE}[...]\c" && echo -e "\t${WHITE}Update CHN Domain & IP rules${cRES}\r\c"
checkSum(){
sha256sumL=$(sha256sum $1 2>/dev/null | awk '{print$1}')
if [[ $sha256sumL = $2 ]]; then 
  echo "true"
elif [[ $sha256sumL != $2 ]]; then
  echo "false"
fi
}

geosite_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat.sha256sum | awk '{print$1}')
geoip_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat.sha256sum | awk '{print$1}')
IPchnroute_sha256sum=$(curl -sSLo- https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute.sha256sum)

if [[ $(checkSum /opt/de_GWD/.repo/geosite.dat $geosite_sha256sum) = "false" ]]; then
rm -rf /tmp/geosite.dat
wget --show-progress -cqO /tmp/geosite.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
  if [[ $(checkSum /tmp/geosite.dat $geosite_sha256sum) = "true" ]]; then
    mv -f /tmp/geosite.dat /opt/de_GWD/.repo/geosite.dat
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}geosite.dat${RED} Download Failed${cRES}"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoip.dat $geoip_sha256sum) = "false" ]]; then
rm -rf /tmp/geoip.dat
wget --show-progress -cqO /tmp/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  if [[ $(checkSum /tmp/geoip.dat $geoip_sha256sum) = "true" ]]; then
    mv -f /tmp/geoip.dat /opt/de_GWD/.repo/geoip.dat
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}geoip.dat${RED} Download Failed${cRES}"
  fi
fi

if [[ $(checkSum /opt/de_GWD/.repo/IPchnroute $IPchnroute_sha256sum) = "false" ]]; then
rm -rf /tmp/IPchnroute
wget --show-progress -cqO /tmp/IPchnroute https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute
  if [[ $(checkSum /tmp/IPchnroute $IPchnroute_sha256sum) = "true" ]]; then
    mv -f /tmp/IPchnroute /opt/de_GWD/.repo/IPchnroute
  else
    echo -e "${WHITE}[ ${RED}✕ ${WHITE}]\c" && echo -e "\t${WHITE}IPchnroute${RED} Download Failed${cRES}"
  fi
fi



if [[ $(checkSum /opt/de_GWD/.repo/geosite.dat $geosite_sha256sum) = "true" ]]; then
  cp -f /opt/de_GWD/.repo/geosite.dat /opt/de_GWD/mosdns/geosite.dat
  cp -f /opt/de_GWD/.repo/geosite.dat /opt/de_GWD/vtrui/geosite.dat
fi

if [[ $(checkSum /opt/de_GWD/.repo/geoip.dat $geoip_sha256sum) = "true" ]]; then
    cp -f /opt/de_GWD/.repo/geoip.dat /opt/de_GWD/mosdns/geoip.dat
    cp -f /opt/de_GWD/.repo/geoip.dat /opt/de_GWD/vtrui/geoip.dat
fi



if [[ $(checkSum /opt/de_GWD/.repo/IPchnroute $IPchnroute_sha256sum) = "true" ]]; then
cp -f /opt/de_GWD/.repo/IPchnroute /opt/de_GWD/nftables/IP_CHNROUTE
sed -i '/^\s*$/d' /opt/de_GWD/nftables/IP_CHNROUTE
sed -i 's/$/,/g' /opt/de_GWD/nftables/IP_CHNROUTE
nft flush set ip de_GWD CHNROUTE
cat << EOF >/opt/de_GWD/nftables/SET_CHNROUTE.nft
#!/usr/sbin/nft -f
table ip de_GWD {
        set CHNROUTE {
                type ipv4_addr
                flags interval
                auto-merge
                elements = { $(cat /opt/de_GWD/nftables/IP_CHNROUTE) }
        }
}
EOF
chmod +x /opt/de_GWD/nftables/SET_CHNROUTE.nft
/opt/de_GWD/nftables/SET_CHNROUTE.nft &
fi

if [[ -n $(openssl x509 -enddate -noout -in /var/www/ssl/de_GWD.cer -checkend 259200 | grep "Certificate will expire") ]] && [[ -d "/root/.acme.sh" ]]; then
"/root/.acme.sh"/acme.sh --force --set-default-ca  --server letsencrypt
"/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh" >/dev/null 2>&1

sslFolder=$(ls "/root/.acme.sh" | grep '_ecc')
cp -f "/root/.acme.sh"/$sslFolder/fullchain.cer /var/www/ssl/de_GWD.cer
cp -f "/root/.acme.sh"/$sslFolder/*.key /var/www/ssl/de_GWD.key
fi

[[ -f "/var/www/ssl/update_ocsp_cache" ]] && /var/www/ssl/update_ocsp_cache >/dev/null 2>&1

[[ $1 = "u" ]] && service cron restart

echo -e "${WHITE}[ ${GREEN}✓ ${WHITE}]\c" && echo -e "\t${WHITE}Update CHN Domain & IP rules${cRES}"
