#!/bin/bash
red()    { echo -e "\033[31m\033[01m $1 \033[0m"; }
green()  { echo -e "\033[32m\033[01m $1 \033[0m"; }
yellow() { echo -e "\033[33m\033[01m $1 \033[0m"; }
blue()   { echo -e "\033[34m\033[01m $1 \033[0m"; }
cyan()   { echo -e "\033[36m\033[01m $1 \033[0m"; }
white()  { echo -e "\033[37m\033[01m $1 \033[0m"; }
statusUpdated=$(green "[  updated  ]")

if [[ $1 == "u" ]]; then
	service cron stop
fi

/opt/de_GWD/tcpTime

wget --no-check-certificate --show-progress -cqO /tmp/geosite.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geosite.dat
[[ $? -ne 0 ]] && red "Download Failed"

if [[ $(du -sk /tmp/geosite.dat 2>/dev/null | awk '{print$1}') -gt 4400 ]]; then
cp -f /tmp/geosite.dat /opt/de_GWD/v2dns/geosite.dat
cp -f /tmp/geosite.dat /opt/de_GWD/vtrui/geosite.dat
rm -rf /tmp/geosite.dat
fi

wget --no-check-certificate --show-progress -cqO /tmp/geoip.dat https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/geoip.dat
[[ $? -ne 0 ]] && red "Download Failed"

if [[ $(du -sk /tmp/geoip.dat 2>/dev/null | awk '{print$1}') -gt 5000 ]]; then
cp -f /tmp/geoip.dat /opt/de_GWD/v2dns/geoip.dat
cp -f /tmp/geoip.dat /opt/de_GWD/vtrui/geoip.dat
rm -rf /tmp/geoip.dat
fi

wget --no-check-certificate --show-progress -cqO /tmp/IPchnroute https://raw.githubusercontent.com/jacyl4/chnroute/main/IPchnroute
[[ $? -ne 0 ]] && red "Download Failed"

if [[ $(du -sk /tmp/IPchnroute 2>/dev/null | awk '{print$1}') -gt 130 ]]; then
sed -i '/^\s*$/d' /tmp/IPchnroute
sed -i 's/^/add chnroute &/g' /tmp/IPchnroute
mv -f /tmp/IPchnroute /opt/de_GWD/chnrouteSET
ipset -! -R </opt/de_GWD/chnrouteSET
fi

if [[ -z $(openssl x509 -enddate -noout -in /var/www/ssl/de_GWD.cer -checkend 259200 | grep ' not ') ]] && [[ -d "/root/.acme.sh" ]] && [[ $(curl -Is get.acme.sh) =~ "HTTP" ]]; then
"/root/.acme.sh"/acme.sh --force --upgrade  --auto-upgrade
"/root/.acme.sh"/acme.sh --force --set-default-ca  --server letsencrypt
"/root/.acme.sh"/acme.sh --force --cron --home "/root/.acme.sh" >/dev/null 2>&1

sslFolder=$(ls "/root/.acme.sh" | grep '_ecc')
cp -f "/root/.acme.sh"/$sslFolder/fullchain.cer /var/www/ssl/de_GWD.cer
cp -f "/root/.acme.sh"/$sslFolder/*.key /var/www/ssl/de_GWD.key

[[ -d "/opt/de_GWD/vtrui" ]] && systemctl restart vtrui
[[ -d "/opt/de_GWD/vtrui1" ]] && systemctl restart vtrui1
[[ -d "/opt/de_GWD/xDNSs" ]] && systemctl restart xDNSs
[[ -d "/opt/de_GWD/RproxyS" ]] && systemctl restart RproxyS
fi

if [[ $(curl -Is google.com) =~ "HTTP" ]] || [[ $(curl -Is youtube.com) =~ "HTTP" ]]; then
/var/www/ssl/update_ocsp_cache >/dev/null 2>&1
fi

echo
echo -n "$statusUpdated" && white "IP & Domain rules"

if [[ $1 == "u" ]]; then
	service cron restart
fi